// Knowledge base for the Build vs. Buy tool.
// Common "build" scenarios with their SaaS alternatives, pricing, and build estimates.
// The AI uses this to make specific, priced recommendations instead of generic advice.

export interface BuildScenario {
  id: string;
  pattern: string;           // What the user typically describes
  category: string;          // Type of solution
  buildComplexity: 'simple' | 'moderate' | 'complex' | 'very-complex';
  buildHours: { min: number; max: number };  // Estimated dev hours
  buildCost: { min: number; max: number };   // Estimated $ at $100/hr
  ongoingMaintenanceHrs: number;              // Hours/month to maintain
  saasAlternatives: SaasAlternative[];
  keyConsiderations: string[];
}

interface SaasAlternative {
  name: string;
  startingPrice: string;     // Monthly starting price
  pricingNotes: string;      // How it scales
  bestFor: string;
  url: string;
  setupTime: string;         // Time to value
  pros: string[];
  cons: string[];
}

export const BUILD_SCENARIOS: BuildScenario[] = [
  {
    id: 'customer-portal',
    pattern: 'customer portal, client dashboard, self-service portal, customer-facing app',
    category: 'Customer Portal',
    buildComplexity: 'complex',
    buildHours: { min: 400, max: 1200 },
    buildCost: { min: 40000, max: 120000 },
    ongoingMaintenanceHrs: 40,
    saasAlternatives: [
      {
        name: 'Retool',
        startingPrice: '$10/user/mo',
        pricingNotes: 'Scales with internal users, not customers. Free up to 5 users.',
        bestFor: 'Internal + external portals with database connectivity',
        url: 'https://retool.com',
        setupTime: '1-2 weeks',
        pros: ['Fast to build', 'Connects to any DB/API', 'Good for complex forms'],
        cons: ['Per-user pricing', 'Limited custom branding', 'Not truly customer-facing'],
      },
      {
        name: 'Front',
        startingPrice: '$19/seat/mo',
        pricingNotes: 'Per-seat, not per-customer',
        bestFor: 'Shared inbox + customer communication portals',
        url: 'https://front.com',
        setupTime: '2-3 days',
        pros: ['Great for ops teams', 'Shared inbox collaboration', 'Cheaper than building'],
        cons: ['Not a full portal', 'Limited automation', 'Per-seat pricing'],
      },
      {
        name: 'HubSpot',
        startingPrice: '$90/mo (Starter) → $3600/mo (Enterprise)',
        pricingNotes: 'Jumps dramatically at scale. Starter is usable.',
        bestFor: 'CRM + customer portal + marketing in one',
        url: 'https://hubspot.com',
        setupTime: '1-3 weeks',
        pros: ['All-in-one platform', 'Free CRM tier', 'Customer portal add-on'],
        cons: ['Expensive at scale', 'Limited customization', 'Lock-in risk'],
      },
    ],
    keyConsiderations: [
      'Data security — customer portals handle PII',
      'Custom branding — SaaS tools may not match your brand',
      'Integration with existing systems',
      'Mobile responsiveness — portals are accessed on phones',
    ],
  },
  {
    id: 'internal-dashboard',
    pattern: 'dashboard, admin panel, internal tool, reporting tool, analytics dashboard',
    category: 'Internal Dashboard / Admin Tool',
    buildComplexity: 'moderate',
    buildHours: { min: 80, max: 400 },
    buildCost: { min: 8000, max: 40000 },
    ongoingMaintenanceHrs: 15,
    saasAlternatives: [
      {
        name: 'Retool',
        startingPrice: '$10/user/mo',
        pricingNotes: 'Free up to 5 users. Scales linearly.',
        bestFor: 'Internal admin tools, dashboards, ops workflows',
        url: 'https://retool.com',
        setupTime: '2-5 days',
        pros: ['Fastest path to internal tools', 'SQL + API connections', 'Strong component library'],
        cons: ['Per-user pricing adds up', 'Not for external users', 'Limited offline'],
      },
      {
        name: 'Metabase',
        startingPrice: 'Free (open source) → $85/mo (Pro)',
        pricingNotes: 'Open source is free forever. Pro for cloud/hosted.',
        bestFor: 'SQL-based dashboards + reporting for non-technical users',
        url: 'https://metabase.com',
        setupTime: '1-2 days',
        pros: ['Free open-source version', 'Easy for non-technical users', 'Good dashboards'],
        cons: ['Less flexible than Retool', 'SQL-focused', 'Limited custom UI'],
      },
      {
        name: 'Looker Studio (Google)',
        startingPrice: 'Free',
        pricingNotes: 'Free for individuals. Looker (enterprise) is custom pricing.',
        bestFor: 'Google Analytics + Google Sheets dashboards',
        url: 'https://lookerstudio.google.com',
        setupTime: '1 day',
        pros: ['Free', 'Easy to use', 'Good Google integration'],
        cons: ['Limited data sources', 'Less powerful than Looker', 'No SQL queries'],
      },
      {
        name: 'Hex',
        startingPrice: '$36/user/mo',
        pricingNotes: 'Per-user, with usage-based compute costs',
        bestFor: 'Data teams wanting collaborative notebooks + dashboards',
        url: 'https://hex.tech',
        setupTime: '2-3 days',
        pros: ['Great for data teams', 'SQL + Python + viz in one', 'Collaborative'],
        cons: ['Expensive per user', 'Best for data-savvy teams', 'Newer platform'],
      },
    ],
    keyConsiderations: [
      'Who needs access — 5 people or 500?',
      'Data source complexity — single DB or many APIs?',
      'Custom calculations vs standard aggregations',
      'Export + sharing needs (PDF, scheduled emails)',
    ],
  },
  {
    id: 'cms',
    pattern: 'content management, CMS, blog, marketing site, landing pages, website builder',
    category: 'CMS / Marketing Site',
    buildComplexity: 'moderate',
    buildHours: { min: 120, max: 600 },
    buildCost: { min: 12000, max: 60000 },
    ongoingMaintenanceHrs: 20,
    saasAlternatives: [
      {
        name: 'Webflow',
        startingPrice: '$14/mo (Basic) → $39/mo (CMS)',
        pricingNotes: 'Per-site. CMS plan needed for blog/content.',
        bestFor: 'Marketing sites + CMS without code',
        url: 'https://webflow.com',
        setupTime: '1-2 weeks',
        pros: ['Best visual web design', 'Full control over output', 'CMS included'],
        cons: ['Steep learning curve', 'Per-site pricing', 'Not for apps'],
      },
      {
        name: 'Contentful',
        startingPrice: 'Free (up to 5 users) → $300/mo (Premium)',
        pricingNotes: 'Headless CMS. You still build the frontend.',
        bestFor: 'Headless CMS for multi-platform content delivery',
        url: 'https://contentful.com',
        setupTime: '1-2 weeks',
        pros: ['Headless/API-first', 'Good for multi-platform', 'Free tier'],
        cons: ['Still need to build frontend', 'Pricing jumps at scale', 'Complex setup'],
      },
      {
        name: 'Sanity',
        startingPrice: 'Free (up to 3 users) → $99/mo (Growth)',
        pricingNotes: 'Per-user + usage-based. Free tier is generous.',
        bestFor: 'Headless CMS with real-time collaboration',
        url: 'https://sanity.io',
        setupTime: '1 week',
        pros: ['Great developer experience', 'Real-time editing', 'Generous free tier'],
        cons: ['Need frontend dev', 'Custom query language (GROQ)', 'Pricing scales with usage'],
      },
      {
        name: 'Framer',
        startingPrice: '$10/mo (Mini) → $22/mo (Pro)',
        pricingNotes: 'Per-site. Affordable for simple sites.',
        bestFor: 'Design-led marketing sites + landing pages',
        url: 'https://framer.com',
        setupTime: '2-5 days',
        pros: ['Fast to publish', 'AI features', 'Beautiful templates'],
        cons: ['Less control than Webflow', 'Limited CMS', 'Best for simple sites'],
      },
    ],
    keyConsiderations: [
      'Who manages content — developers or marketers?',
      'Multi-language needs',
      'SEO requirements',
      'Custom design vs templates',
    ],
  },
  {
    id: 'auth',
    pattern: 'authentication, login, auth, user management, SSO, OAuth, sign in, sign up',
    category: 'Authentication',
    buildComplexity: 'very-complex',
    buildHours: { min: 200, max: 800 },
    buildCost: { min: 20000, max: 80000 },
    ongoingMaintenanceHrs: 30,
    saasAlternatives: [
      {
        name: 'Clerk',
        startingPrice: 'Free (up to 10K MAU) → $25/mo+',
        pricingNotes: 'Generous free tier. Scales with MAU.',
        bestFor: 'Modern auth with great DX, multi-factor, organizations',
        url: 'https://clerk.com',
        setupTime: '1-2 hours',
        pros: ['Best developer experience', 'Beautiful pre-built UI', 'Free up to 10K users'],
        cons: ['Newer company', 'Limited enterprise SSO on lower tiers', 'Vendor lock-in'],
      },
      {
        name: 'Auth0 (Okta)',
        startingPrice: 'Free (up to 7K MAU) → $35/mo+',
        pricingNotes: 'Free tier, then per-MAU pricing. Enterprise is custom.',
        bestFor: 'Enterprise-grade auth with SSO, compliance, enterprise features',
        url: 'https://auth0.com',
        setupTime: '2-4 hours',
        pros: ['Industry standard', 'Enterprise SSO + compliance', 'Great documentation'],
        cons: ['Expensive at scale', 'Complex configuration', 'Owned by Okta'],
      },
      {
        name: 'Supabase Auth',
        startingPrice: 'Free (up to 50K MAU) → $25/mo+',
        pricingNotes: 'Included with Supabase. Very generous free tier.',
        bestFor: 'Full-stack devs already using Supabase for DB',
        url: 'https://supabase.com',
        setupTime: '1-2 hours',
        pros: ['50K MAU free', 'Postgres RLS integration', 'Open source'],
        cons: ['Less polished UI', 'Best with Supabase ecosystem', 'Fewer enterprise features'],
      },
      {
        name: 'NextAuth.js (Auth.js)',
        startingPrice: 'Free (open source)',
        pricingNotes: 'Free forever — you self-host.',
        bestFor: 'Next.js apps wanting auth without a vendor',
        url: 'https://authjs.dev',
        setupTime: '2-4 hours',
        pros: ['Free + open source', 'No vendor lock-in', 'Great Next.js integration'],
        cons: ['You maintain it', 'Less features than Clerk/Auth0', 'No managed UI'],
      },
    ],
    keyConsiderations: [
      'NEVER build auth from scratch — security risk',
      'Compliance needs (SOC 2, HIPAA, GDPR)',
      'Enterprise SSO (SAML, OIDC) requirements',
      'Multi-tenant / organization support',
    ],
  },
  {
    id: 'ecommerce',
    pattern: 'e-commerce, online store, shopping cart, checkout, product catalog, shop',
    category: 'E-Commerce',
    buildComplexity: 'complex',
    buildHours: { min: 300, max: 1500 },
    buildCost: { min: 30000, max: 150000 },
    ongoingMaintenanceHrs: 40,
    saasAlternatives: [
      {
        name: 'Shopify',
        startingPrice: '$29/mo (Basic) → $2000/mo (Plus)',
        pricingNotes: 'Plus for $1M+ revenue. Transaction fees on lower tiers.',
        bestFor: 'Any e-commerce store — from MVP to enterprise',
        url: 'https://shopify.com',
        setupTime: '1-3 days',
        pros: ['Best e-commerce platform', 'Handles payments + inventory', 'Huge app ecosystem'],
        cons: ['Transaction fees on lower tiers', 'Limited customization', 'Monthly cost scales'],
      },
      {
        name: 'BigCommerce',
        startingPrice: '$29/mo (Standard) → $299/mo (Pro)',
        pricingNotes: 'No transaction fees. Pro tier for higher volume.',
        bestFor: 'Larger stores wanting no transaction fees',
        url: 'https://bigcommerce.com',
        setupTime: '2-5 days',
        pros: ['No transaction fees', 'More built-in features than Shopify', 'Good for B2B'],
        cons: ['Smaller ecosystem', 'Fewer themes', 'Less popular'],
      },
      {
        name: 'Stripe Checkout',
        startingPrice: '2.9% + 30¢ per transaction',
        pricingNotes: 'No monthly fee. Just transaction fees.',
        bestFor: 'Simple checkout when you already have a frontend',
        url: 'https://stripe.com/checkout',
        setupTime: '2-4 hours',
        pros: ['Just transaction fees', 'Best payment UX', 'Handles compliance (PCI)'],
        cons: ['Not a full store', 'You build the catalog', 'You handle inventory'],
      },
      {
        name: 'Lemon Squeezy',
        startingPrice: '5% + 50¢ per transaction',
        pricingNotes: 'No monthly fee. Higher % but handles tax + compliance.',
        bestFor: 'Selling digital products + software with tax compliance',
        url: 'https://lemonsqueezy.com',
        setupTime: '1-2 hours',
        pros: ['Handles tax + VAT', 'Merchant of record', 'Great for digital products'],
        cons: ['Higher % than Stripe', 'Less customizable', 'Newer platform'],
      },
    ],
    keyConsiderations: [
      'Payment processing — PCI compliance is critical',
      'Inventory management needs',
      'Tax calculation + remittance (sales tax, VAT)',
      'Shipping + fulfillment integration',
    ],
  },
  {
    id: 'payments',
    pattern: 'payments, billing, subscriptions, invoicing, payment processing, charge',
    category: 'Payments / Billing',
    buildComplexity: 'very-complex',
    buildHours: { min: 200, max: 600 },
    buildCost: { min: 20000, max: 60000 },
    ongoingMaintenanceHrs: 25,
    saasAlternatives: [
      {
        name: 'Stripe',
        startingPrice: '2.9% + 30¢ per transaction',
        pricingNotes: 'No monthly fee. Stripe Billing adds 0.5% for subscriptions.',
        bestFor: 'Any payment processing — cards, subscriptions, invoicing',
        url: 'https://stripe.com',
        setupTime: '2-4 hours',
        pros: ['Best developer experience', 'Handles PCI compliance', 'Subscriptions + invoicing'],
        cons: ['Transaction fees add up', 'Chargeback fees', 'Account holds can happen'],
      },
      {
        name: 'Paddle',
        startingPrice: '5% + 50¢ per transaction',
        pricingNotes: 'Higher % but handles tax + compliance as merchant of record.',
        bestFor: 'SaaS companies selling globally — handles tax compliance',
        url: 'https://paddle.com',
        setupTime: '1-2 days',
        pros: ['Merchant of record (handles tax)', 'Global compliance', 'Subscription management'],
        cons: ['Higher % than Stripe', 'Less flexible', 'Slower payouts'],
      },
      {
        name: 'Ramp (corporate cards)',
        startingPrice: 'Free',
        pricingNotes: 'Free corporate cards + expense automation.',
        bestFor: 'Internal expense management (not for collecting payments)',
        url: 'https://ramp.com',
        setupTime: '1 week',
        pros: ['Free', 'AI receipt extraction', 'Cards + AP + expenses'],
        cons: ['For spending, not collecting', 'US-focused', 'Requires switching cards'],
      },
    ],
    keyConsiderations: [
      'PCI compliance — never store card data yourself',
      'Subscription billing complexity (trials, upgrades, proration)',
      'Tax compliance (sales tax, VAT, GST)',
      'Payout timing + bank account requirements',
    ],
  },
  {
    id: 'email-infra',
    pattern: 'email, send email, transactional email, email notifications, email infrastructure',
    category: 'Email Infrastructure',
    buildComplexity: 'moderate',
    buildHours: { min: 60, max: 200 },
    buildCost: { min: 6000, max: 20000 },
    ongoingMaintenanceHrs: 10,
    saasAlternatives: [
      {
        name: 'Resend',
        startingPrice: 'Free (3K/mo) → $20/mo (50K/mo)',
        pricingNotes: 'Generous free tier. Modern API.',
        bestFor: 'Transactional email with great DX',
        url: 'https://resend.com',
        setupTime: '30 minutes',
        pros: ['Best DX', 'React email templates', 'Free 3K/mo'],
        cons: ['Newer company', 'Less enterprise features', 'No marketing email'],
      },
      {
        name: 'Postmark',
        startingPrice: '$15/mo (10K emails)',
        pricingNotes: 'Pay per email. Best deliverability.',
        bestFor: 'Transactional email where deliverability matters most',
        url: 'https://postmarkapp.com',
        setupTime: '30 minutes',
        pros: ['Best deliverability', 'Fast inbound processing', 'Great analytics'],
        cons: ['More expensive than competitors', 'No free tier', 'Separate from marketing email'],
      },
      {
        name: 'SendGrid',
        startingPrice: 'Free (100/day) → $19.95/mo (50K/mo)',
        pricingNotes: 'Free tier for low volume. Scales with volume.',
        bestFor: 'Both transactional + marketing email in one',
        url: 'https://sendgrid.com',
        setupTime: '1 hour',
        pros: ['Free tier', 'Marketing + transactional', 'Well-known'],
        cons: ['Deliverability issues', 'Owned by Twilio', 'UI is dated'],
      },
      {
        name: 'Amazon SES',
        startingPrice: '$0.10 per 1K emails',
        pricingNotes: 'Cheapest option. You build everything else.',
        bestFor: 'High-volume email at lowest cost',
        url: 'https://aws.amazon.com/ses',
        setupTime: '2-4 hours',
        pros: ['Cheapest by far', 'Scales infinitely', 'AWS integration'],
        cons: ['No UI — API only', 'You handle templates', 'Complex setup'],
      },
    ],
    keyConsiderations: [
      'Deliverability — will emails reach the inbox?',
      'Template management — HTML or code?',
      'Inbound email processing (if needed)',
      'Volume — 100/day or 1M/day?',
    ],
  },
  {
    id: 'search',
    pattern: 'search, full-text search, search engine, search bar, faceted search, autocomplete',
    category: 'Search',
    buildComplexity: 'moderate',
    buildHours: { min: 80, max: 300 },
    buildCost: { min: 8000, max: 30000 },
    ongoingMaintenanceHrs: 12,
    saasAlternatives: [
      {
        name: 'Algolia',
        startingPrice: 'Free (10K searches/mo) → $1/mo+',
        pricingNotes: 'Pay per search. Free tier is usable.',
        bestFor: 'Instant search with great UX + typo tolerance',
        url: 'https://algolia.com',
        setupTime: '2-4 hours',
        pros: ['Best search UX', 'Instant results', 'Great autocomplete'],
        cons: ['Expensive at scale', 'Vendor lock-in', 'Limited to their indexes'],
      },
      {
        name: 'Meilisearch',
        startingPrice: 'Free (open source) → $30/mo (Cloud)',
        pricingNotes: 'Open source is free. Cloud for managed.',
        bestFor: 'Self-hostable search with Algolia-like UX',
        url: 'https://meilisearch.com',
        setupTime: '2-4 hours',
        pros: ['Open source', 'Fast', 'Algolia-like features'],
        cons: ['Newer ecosystem', 'Self-hosting overhead', 'Less enterprise support'],
      },
      {
        name: 'Elasticsearch',
        startingPrice: 'Free (open source) → Custom (Elastic Cloud)',
        pricingNotes: 'Open source self-hosted. Cloud is custom pricing.',
        bestFor: 'Complex search at scale with logging + analytics',
        url: 'https://elastic.co',
        setupTime: '1-2 days',
        pros: ['Most powerful', 'Scales massively', 'Open source'],
        cons: ['Complex to operate', 'Resource-heavy', 'Overkill for simple search'],
      },
      {
        name: 'Typesense',
        startingPrice: 'Free (open source) → Cloud pricing varies',
        pricingNotes: 'Open source. Cloud managed option available.',
        bestFor: 'Fast, typo-tolerant search that\'s cheaper than Algolia',
        url: 'https://typesense.org',
        setupTime: '2-4 hours',
        pros: ['Open source', 'Fast', 'Good Algolia alternative'],
        cons: ['Smaller community', 'Self-hosting needed', 'Newer'],
      },
    ],
    keyConsiderations: [
      'Search volume — 100 searches/day or 10M?',
      'Typo tolerance + relevance tuning',
      'Faceted search (filter by category, price, etc.)',
      'Real-time indexing needs',
    ],
  },
  {
    id: 'crm',
    pattern: 'CRM, customer relationship management, sales pipeline, contact management, lead tracking',
    category: 'CRM',
    buildComplexity: 'complex',
    buildHours: { min: 300, max: 1000 },
    buildCost: { min: 30000, max: 100000 },
    ongoingMaintenanceHrs: 35,
    saasAlternatives: [
      {
        name: 'HubSpot',
        startingPrice: 'Free (CRM) → $890/mo (Professional)',
        pricingNotes: 'Free CRM is genuinely useful. Marketing Hub is expensive.',
        bestFor: 'All-in-one CRM + marketing + sales for growing companies',
        url: 'https://hubspot.com',
        setupTime: '1-2 weeks',
        pros: ['Free CRM', 'All-in-one platform', 'Great integrations'],
        cons: ['Expensive at scale', 'Marketing Hub pricing jumps', 'Complexity'],
      },
      {
        name: 'Pipedrive',
        startingPrice: '$14/user/mo (Essential) → $99/user/mo (Enterprise)',
        pricingNotes: 'Per-user. Affordable for small sales teams.',
        bestFor: 'Sales-focused teams wanting simple pipeline management',
        url: 'https://pipedrive.com',
        setupTime: '2-3 days',
        pros: ['Simple + affordable', 'Great for sales', 'Easy to use'],
        cons: ['Less features than HubSpot', 'No marketing automation', 'Per-user pricing'],
      },
      {
        name: 'Salesforce',
        startingPrice: '$25/user/mo (Starter) → $500/user/mo (Unlimited)',
        pricingNotes: 'Per-user. Enterprise is very expensive.',
        bestFor: 'Large enterprises needing customization + governance',
        url: 'https://salesforce.com',
        setupTime: '1-3 months',
        pros: ['Most powerful CRM', 'Highly customizable', 'Enterprise-grade'],
        cons: ['Very expensive', 'Months to implement', 'Complex UI'],
      },
      {
        name: 'Attio',
        startingPrice: 'Free (up to 3 users) → $25/user/mo+',
        pricingNotes: 'Generous free tier. Modern CRM.',
        bestFor: 'Startups wanting a modern, flexible CRM',
        url: 'https://attio.com',
        setupTime: '2-3 days',
        pros: ['Modern + flexible', 'Free tier', 'Great UX'],
        cons: ['Newer company', 'Less proven', 'Smaller ecosystem'],
      },
    ],
    keyConsiderations: [
      'Team size — 3 reps or 300?',
      'Integration needs (email, calendar, marketing)',
      'Custom fields + workflows',
      'Reporting + analytics requirements',
    ],
  },
  {
    id: 'project-mgmt',
    pattern: 'project management, task management, issue tracking, kanban, sprint planning, ticket system',
    category: 'Project Management',
    buildComplexity: 'moderate',
    buildHours: { min: 150, max: 500 },
    buildCost: { min: 15000, max: 50000 },
    ongoingMaintenanceHrs: 18,
    saasAlternatives: [
      {
        name: 'Linear',
        startingPrice: 'Free (up to 250 issues) → $8/user/mo',
        pricingNotes: 'Generous free tier. Per-user pricing.',
        bestFor: 'Software teams wanting fast, opinionated issue tracking',
        url: 'https://linear.app',
        setupTime: '1 hour',
        pros: ['Best UX', 'Fast', 'Great GitHub integration'],
        cons: ['Software-focused', 'Less flexible', 'Newer'],
      },
      {
        name: 'Asana',
        startingPrice: 'Free (up to 10 users) → $11/user/mo',
        pricingNotes: 'Free tier is usable. Per-user pricing.',
        bestFor: 'Non-dev teams wanting project tracking + automation',
        url: 'https://asana.com',
        setupTime: '1-2 days',
        pros: ['Easy to use', 'Good automations', 'Free tier'],
        cons: ['Less powerful for dev', 'Per-user pricing', 'Can get messy'],
      },
      {
        name: 'Monday.com',
        startingPrice: 'Free (2 users) → $9/user/mo',
        pricingNotes: 'Per-user. Free tier is very limited.',
        bestFor: 'Visual boards for PM + CRM + ops tracking',
        url: 'https://monday.com',
        setupTime: '1-2 days',
        pros: ['Very flexible', 'Good automations', 'Visual'],
        cons: ['Per-user pricing adds up', 'Limited free tier', 'Can be overwhelming'],
      },
      {
        name: 'Jira',
        startingPrice: 'Free (up to 10 users) → $8/user/mo',
        pricingNotes: 'Free tier is generous. Per-user.',
        bestFor: 'Software teams wanting customizable issue tracking at scale',
        url: 'https://atlassian.com/software/jira',
        setupTime: '2-5 days',
        pros: ['Most powerful', 'Highly customizable', 'Free up to 10 users'],
        cons: ['Complex setup', 'Dated UI', 'Slow for small teams'],
      },
    ],
    keyConsiderations: [
      'Team type — developers or non-devs?',
      'Custom workflows + fields',
      'Integration with code repos',
      'Reporting needs',
    ],
  },
  {
    id: 'analytics',
    pattern: 'analytics, product analytics, event tracking, user behavior, funnel analysis, metrics dashboard',
    category: 'Product Analytics',
    buildComplexity: 'complex',
    buildHours: { min: 200, max: 800 },
    buildCost: { min: 20000, max: 80000 },
    ongoingMaintenanceHrs: 30,
    saasAlternatives: [
      {
        name: 'PostHog',
        startingPrice: 'Free (1M events/mo) → pay-as-you-go',
        pricingNotes: 'Generous free tier. Open source.',
        bestFor: 'Product analytics + feature flags + session replay',
        url: 'https://posthog.com',
        setupTime: '1-2 hours',
        pros: ['Free 1M events/mo', 'Open source', 'All-in-one (analytics + flags + replay)'],
        cons: ['Newer platform', 'Self-hosting is complex', 'UI less polished than Mixpanel'],
      },
      {
        name: 'Mixpanel',
        startingPrice: 'Free (up to 20M events) → $20/mo+',
        pricingNotes: 'Very generous free tier. Pay for volume.',
        bestFor: 'Product analytics with best-in-class funnels + retention',
        url: 'https://mixpanel.com',
        setupTime: '1-2 hours',
        pros: ['Best funnels + retention', '20M events free', 'Good UX'],
        cons: ['Expensive at scale', 'No feature flags', 'Limited session replay'],
      },
      {
        name: 'Amplitude',
        startingPrice: 'Free (up to 50K events/mo) → Custom',
        pricingNotes: 'Free tier is limited. Enterprise is custom pricing.',
        bestFor: 'Enterprise product analytics with cohort analysis',
        url: 'https://amplitude.com',
        setupTime: '2-4 hours',
        pros: ['Powerful cohort analysis', 'Good for enterprise', 'Strong reporting'],
        cons: ['Limited free tier', 'Expensive at scale', 'Complex setup'],
      },
      {
        name: 'Google Analytics 4',
        startingPrice: 'Free',
        pricingNotes: 'Free forever. GA360 for enterprise.',
        bestFor: 'Web + app analytics for free',
        url: 'https://analytics.google.com',
        setupTime: '1-2 hours',
        pros: ['Free', 'Industry standard', 'AI insights'],
        cons: ['Steep learning curve', 'Privacy concerns', 'Less product-focused'],
      },
    ],
    keyConsiderations: [
      'Event volume — 10K/day or 10M/day?',
      'Funnel + retention analysis needs',
      'Session replay (visual user behavior)',
      'Data ownership + privacy (GDPR)',
    ],
  },
  {
    id: 'scheduling',
    pattern: 'scheduling, booking, appointment, calendar, meeting scheduler, time slot',
    category: 'Scheduling / Booking',
    buildComplexity: 'moderate',
    buildHours: { min: 100, max: 400 },
    buildCost: { min: 10000, max: 40000 },
    ongoingMaintenanceHrs: 15,
    saasAlternatives: [
      {
        name: 'Cal.com',
        startingPrice: 'Free (open source) → $12/user/mo',
        pricingNotes: 'Open source is free. Cloud is per-user.',
        bestFor: 'Self-hostable scheduling with Calendly-like features',
        url: 'https://cal.com',
        setupTime: '30 minutes',
        pros: ['Open source', 'Free self-hosted', 'Good integrations'],
        cons: ['Newer than Calendly', 'Self-hosting overhead', 'Less polished'],
      },
      {
        name: 'Calendly',
        startingPrice: 'Free (1 event type) → $10/user/mo',
        pricingNotes: 'Free tier for basic. Per-user for teams.',
        bestFor: 'Simple meeting scheduling — the industry standard',
        url: 'https://calendly.com',
        setupTime: '15 minutes',
        pros: ['Easiest to use', 'Industry standard', 'Good integrations'],
        cons: ['Per-user pricing', 'Limited free tier', 'Less customizable'],
      },
      {
        name: 'SavvyCal',
        startingPrice: '$12/user/mo',
        pricingNotes: 'Per-user. No free tier but 30-day trial.',
        bestFor: 'Teams wanting better UX than Calendly',
        url: 'https://savvycal.com',
        setupTime: '30 minutes',
        pros: ['Better UX than Calendly', 'Calendar overlays', 'Good for teams'],
        cons: ['No free tier', 'Newer', 'Smaller ecosystem'],
      },
    ],
    keyConsiderations: [
      'Timezone handling',
      'Group scheduling vs 1:1',
      'Integration with existing calendars',
      'Custom availability rules',
    ],
  },
  {
    id: 'forms',
    pattern: 'forms, surveys, questionnaire, feedback form, application form, registration form',
    category: 'Forms / Surveys',
    buildComplexity: 'simple',
    buildHours: { min: 40, max: 150 },
    buildCost: { min: 4000, max: 15000 },
    ongoingMaintenanceHrs: 8,
    saasAlternatives: [
      {
        name: 'Tally',
        startingPrice: 'Free (unlimited forms) → $29/mo (Pro)',
        pricingNotes: 'Free tier is genuinely unlimited. Pro for advanced.',
        bestFor: 'Beautiful forms + surveys — free unlimited tier',
        url: 'https://tally.so',
        setupTime: '15 minutes',
        pros: ['Free unlimited forms', 'Beautiful design', 'Good logic jumps'],
        cons: ['Newer than Typeform', 'Less integrations', 'Pro needed for some features'],
      },
      {
        name: 'Typeform',
        startingPrice: 'Free (10 responses/mo) → $25/mo+',
        pricingNotes: 'Free tier is limited. Per-month for volume.',
        bestFor: 'Conversational forms with great UX',
        url: 'https://typeform.com',
        setupTime: '30 minutes',
        pros: ['Best form UX', 'Many integrations', 'Good templates'],
        cons: ['Expensive at scale', 'Limited free tier', 'Per-response pricing'],
      },
      {
        name: 'Fillout',
        startingPrice: 'Free (1K responses/mo) → $15/mo+',
        pricingNotes: 'Generous free tier. Pay for volume.',
        bestFor: 'Advanced forms with database + scheduling integration',
        url: 'https://fillout.com',
        setupTime: '20 minutes',
        pros: ['Generous free tier', 'Advanced logic', 'Database integration'],
        cons: ['Newer', 'Less known', 'Smaller community'],
      },
      {
        name: 'Google Forms',
        startingPrice: 'Free',
        pricingNotes: 'Free forever with Google account.',
        bestFor: 'Simple forms + surveys for free',
        url: 'https://forms.google.com',
        setupTime: '10 minutes',
        pros: ['Free', 'Easy to use', 'Google Sheets integration'],
        cons: ['Limited design', 'Limited logic', 'No payment collection'],
      },
    ],
    keyConsiderations: [
      'Response volume — 100 or 10K?',
      'Payment collection in forms',
      'Custom branding needs',
      'Conditional logic (skip patterns)',
    ],
  },
  {
    id: 'notification-system',
    pattern: 'notifications, push notifications, in-app notifications, alert system, notification center',
    category: 'Notification System',
    buildComplexity: 'moderate',
    buildHours: { min: 100, max: 400 },
    buildCost: { min: 10000, max: 40000 },
    ongoingMaintenanceHrs: 15,
    saasAlternatives: [
      {
        name: 'Novu',
        startingPrice: 'Free (up to 10K notifications/mo) → pay-as-you-go',
        pricingNotes: 'Generous free tier. Open source.',
        bestFor: 'Multi-channel notifications (email, SMS, push, in-app)',
        url: 'https://novu.co',
        setupTime: '2-4 hours',
        pros: ['Open source', 'Multi-channel', 'Free 10K/mo'],
        cons: ['Newer platform', 'Self-hosting overhead', 'Less polished'],
      },
      {
        name: 'Courier',
        startingPrice: 'Free (10K notifications/mo) → pay-as-you-go',
        pricingNotes: 'Free tier. Pay per notification.',
        bestFor: 'Unified notification API across many providers',
        url: 'https://courier.com',
        setupTime: '2-4 hours',
        pros: ['Multi-provider', 'Good template management', 'Free tier'],
        cons: ['Adds a layer of abstraction', 'Per-notification pricing', 'Newer'],
      },
      {
        name: 'MagicBell',
        startingPrice: 'Free (up to 100 MAU) → $49/mo+',
        pricingNotes: 'Per-MAU pricing. Free for small apps.',
        bestFor: 'In-app notification inbox (like GitHub/Asana notifications)',
        url: 'https://magicbell.com',
        setupTime: '1-2 hours',
        pros: ['Best in-app notification UI', 'Easy to embed', 'Good API'],
        cons: ['Focused on in-app only', 'Per-MAU pricing', 'Newer'],
      },
    ],
    keyConsiderations: [
      'Multi-channel needs (email, SMS, push, in-app)',
      'User preferences + opt-out management',
      'Real-time vs batched delivery',
      'Template management',
    ],
  },
  {
    id: 'file-storage',
    pattern: 'file upload, file storage, image upload, document storage, media management, CDN',
    category: 'File Storage / Media',
    buildComplexity: 'simple',
    buildHours: { min: 40, max: 120 },
    buildCost: { min: 4000, max: 12000 },
    ongoingMaintenanceHrs: 5,
    saasAlternatives: [
      {
        name: 'Cloudinary',
        startingPrice: 'Free (25K transformations/mo) → $89/mo+',
        pricingNotes: 'Generous free tier. Pay for transformations + storage.',
        bestFor: 'Image + video management with transformations + CDN',
        url: 'https://cloudinary.com',
        setupTime: '30 minutes',
        pros: ['Best image transformations', 'CDN included', 'Free tier'],
        cons: ['Complex pricing', 'Overkill for simple storage', 'Vendor lock-in'],
      },
      {
        name: 'UploadThing',
        startingPrice: 'Free (2GB storage) → $10/mo+',
        pricingNotes: 'Simple pricing tiers. Good for Next.js apps.',
        bestFor: 'Simple file uploads in Next.js / React apps',
        url: 'https://uploadthing.com',
        setupTime: '30 minutes',
        pros: ['Easiest file uploads', 'Great DX', 'Good Next.js integration'],
        cons: ['Newer', 'Less features than Cloudinary', 'Limited transformations'],
      },
      {
        name: 'AWS S3',
        startingPrice: '~$0.023/GB/mo',
        pricingNotes: 'Pay per GB stored + transfer. Very cheap.',
        bestFor: 'Raw file storage at scale — you build everything else',
        url: 'https://aws.amazon.com/s3',
        setupTime: '1-2 hours',
        pros: ['Cheapest at scale', 'Infinite storage', 'AWS integration'],
        cons: ['No UI — API only', 'You handle uploads + transformations', 'Complex permissions'],
      },
      {
        name: 'Supabase Storage',
        startingPrice: 'Free (1GB) → $25/mo (100GB)',
        pricingNotes: 'Included with Supabase. Generous free tier.',
        bestFor: 'Already using Supabase — storage is included',
        url: 'https://supabase.com/storage',
        setupTime: '30 minutes',
        pros: ['Integrated with Supabase', 'Good free tier', 'RLS security'],
        cons: ['Best only if using Supabase', 'Less features than Cloudinary', 'Newer'],
      },
    ],
    keyConsiderations: [
      'Storage volume — MB or TB?',
      'Image/video transformation needs',
      'CDN requirements (global delivery)',
      'Access control (public, private, signed URLs)',
    ],
  },
  {
    id: 'feature-flags',
    pattern: 'feature flags, feature toggles, A/B testing, gradual rollout, experiment, canary release',
    category: 'Feature Flags / A/B Testing',
    buildComplexity: 'moderate',
    buildHours: { min: 80, max: 300 },
    buildCost: { min: 8000, max: 30000 },
    ongoingMaintenanceHrs: 10,
    saasAlternatives: [
      {
        name: 'PostHog',
        startingPrice: 'Free (1M events/mo)',
        pricingNotes: 'Feature flags included in free tier.',
        bestFor: 'Feature flags + analytics + session replay in one',
        url: 'https://posthog.com',
        setupTime: '1 hour',
        pros: ['Free feature flags', 'Analytics included', 'Open source'],
        cons: ['Less powerful than LaunchDarkly', 'Newer', 'All-in-one may be overkill'],
      },
      {
        name: 'LaunchDarkly',
        startingPrice: 'Free (up to 3 environments) → $15/seat/mo+',
        pricingNotes: 'Per-seat. Enterprise is custom.',
        bestFor: 'Enterprise feature flag management with governance',
        url: 'https://launchdarkly.com',
        setupTime: '1-2 hours',
        pros: ['Best-in-class', 'Enterprise-grade', 'Great SDKs'],
        cons: ['Expensive at scale', 'Per-seat pricing', 'Overkill for small teams'],
      },
      {
        name: 'GrowthBook',
        startingPrice: 'Free (open source) → Cloud pricing',
        pricingNotes: 'Open source is free. Cloud is per-seat.',
        bestFor: 'A/B testing + feature flags — open source',
        url: 'https://growthbook.io',
        setupTime: '1-2 hours',
        pros: ['Open source', 'A/B testing included', 'Good for data teams'],
        cons: ['Self-hosting overhead', 'Less polished', 'Newer'],
      },
      {
        name: 'ConfigCat',
        startingPrice: 'Free (up to 10K flags/mo) → $99/mo+',
        pricingNotes: 'Generous free tier. Pay for volume.',
        bestFor: 'Simple feature flags with good free tier',
        url: 'https://configcat.com',
        setupTime: '30 minutes',
        pros: ['Generous free tier', 'Easy to use', 'Good SDKs'],
        cons: ['Less features than LaunchDarkly', 'Newer', 'No A/B testing'],
      },
    ],
    keyConsiderations: [
      'A/B testing needs (statistical significance)',
      'Gradual rollout (canary deployments)',
      'Targeting rules (by user, geography, etc.)',
      'Integration with analytics',
    ],
  },
  {
    id: 'chatbot',
    pattern: 'chatbot, AI assistant, customer support bot, conversational AI, help bot, virtual assistant',
    category: 'Chatbot / AI Assistant',
    buildComplexity: 'complex',
    buildHours: { min: 200, max: 800 },
    buildCost: { min: 20000, max: 80000 },
    ongoingMaintenanceHrs: 30,
    saasAlternatives: [
      {
        name: 'Intercom Fin',
        startingPrice: '$0.99 per resolution',
        pricingNotes: 'Pay per resolution. Only pay when Fin resolves a ticket.',
        bestFor: 'SaaS companies wanting AI to resolve support tickets',
        url: 'https://intercom.com/fin',
        setupTime: '1-2 weeks',
        pros: ['Resolves tickets (not just deflects)', 'Only pay for successes', 'Learns from your help center'],
        cons: ['Requires Intercom subscription', 'Best for SaaS', 'Resolution pricing adds up'],
      },
      {
        name: 'Chatbase',
        startingPrice: '$19/mo (Starter)',
        pricingNotes: 'Per-month + per-message. Generous starter tier.',
        bestFor: 'Custom AI chatbot trained on your docs',
        url: 'https://chatbase.co',
        setupTime: '1-2 hours',
        pros: ['Easy to build chatbots', 'Trains on your docs', 'Affordable'],
        cons: ['Quality depends on training data', 'Less powerful than Fin', 'Best for simple bots'],
      },
      {
        name: 'Voiceflow',
        startingPrice: 'Free → $40/mo (Pro)',
        pricingNotes: 'Free tier available. Per-month for teams.',
        bestFor: 'Visual chatbot + voice agent builder',
        url: 'https://voiceflow.com',
        setupTime: '2-5 days',
        pros: ['Visual builder', 'Good for teams', 'Voice + chat support'],
        cons: ['Learning curve', 'Best for support bots', 'Pricing scales with usage'],
      },
    ],
    keyConsiderations: [
      'Can the AI actually resolve tickets or just deflect?',
      'Training data quality — your help center must be good',
      'Human handoff for complex cases',
      'Compliance — AI responses can create liability',
    ],
  },
  {
    id: 'helpdesk',
    pattern: 'helpdesk, ticketing system, support ticket, help desk software, support queue, ticket management',
    category: 'Helpdesk / Ticketing',
    buildComplexity: 'complex',
    buildHours: { min: 300, max: 1000 },
    buildCost: { min: 30000, max: 100000 },
    ongoingMaintenanceHrs: 35,
    saasAlternatives: [
      {
        name: 'Zendesk',
        startingPrice: '$55/agent/mo',
        pricingNotes: 'Per-agent. Enterprise features cost more.',
        bestFor: 'Established support teams at any scale',
        url: 'https://zendesk.com',
        setupTime: '1-2 weeks',
        pros: ['Industry standard', 'Strong AI features', 'Excellent reporting'],
        cons: ['Expensive', 'Complex setup', 'Per-agent pricing'],
      },
      {
        name: 'Intercom',
        startingPrice: '$39/seat/mo',
        pricingNotes: 'Per-seat. Pro + Enterprise tiers available.',
        bestFor: 'SaaS companies wanting chat + helpdesk + AI in one',
        url: 'https://intercom.com',
        setupTime: '1-2 weeks',
        pros: ['AI-first platform', 'All-in-one', 'Good for SaaS'],
        cons: ['Expensive at scale', 'Steeper learning curve', 'Per-seat pricing'],
      },
      {
        name: 'Help Scout',
        startingPrice: '$20/user/mo',
        pricingNotes: 'Per-user. Affordable for small teams.',
        bestFor: 'Small teams wanting a simple, email-like helpdesk',
        url: 'https://helpscout.com',
        setupTime: '1-2 days',
        pros: ['Simple + affordable', 'Great email-like UX', 'Good for small teams'],
        cons: ['Less features than Zendesk', 'Limited AI', 'Not for enterprise'],
      },
      {
        name: 'Front',
        startingPrice: '$19/seat/mo',
        pricingNotes: 'Per-seat. Shared inbox approach.',
        bestFor: 'Ops teams handling shared inboxes (support@, billing@)',
        url: 'https://front.com',
        setupTime: '2-3 days',
        pros: ['Great for ops teams', 'Shared inbox collaboration', 'Cheaper than Zendesk'],
        cons: ['Not a full helpdesk', 'Limited AI features', 'Best for email-first teams'],
      },
    ],
    keyConsiderations: [
      'Volume — 100 tickets/month or 10K?',
      'Channels — email only or chat + phone + social?',
      'SLA management needs',
      'Integration with CRM + knowledge base',
    ],
  },
  {
    id: 'web-scraping',
    pattern: 'web scraping, data extraction, crawler, scraper, data collection, price monitoring, competitor analysis',
    category: 'Web Scraping / Data Collection',
    buildComplexity: 'moderate',
    buildHours: { min: 80, max: 300 },
    buildCost: { min: 8000, max: 30000 },
    ongoingMaintenanceHrs: 20,
    saasAlternatives: [
      {
        name: 'Apify',
        startingPrice: 'Free ($5/mo credit) → $49/mo+',
        pricingNotes: 'Free tier with credits. Pay for compute.',
        bestFor: 'Pre-built scrapers for popular sites + custom actors',
        url: 'https://apify.com',
        setupTime: '1-2 hours',
        pros: ['Pre-built actors for popular sites', 'Scales easily', 'Good free tier'],
        cons: ['Requires some dev knowledge', 'Pricing scales with usage', 'Best for developers'],
      },
      {
        name: 'Browse AI',
        startingPrice: 'Free (50 credits/mo) → $39/mo+',
        pricingNotes: 'Credit-based. No code needed.',
        bestFor: 'Point-and-click scraper builder for non-devs',
        url: 'https://browse.ai',
        setupTime: '30 minutes',
        pros: ['No code needed', 'Monitors on schedule', 'Handles pagination'],
        cons: ['Limited to public data', 'Can break when sites change', 'Credit-based pricing'],
      },
      {
        name: 'Bright Data',
        startingPrice: '$50/mo+',
        pricingNotes: 'Pay for proxies + scraping infrastructure.',
        bestFor: 'Large-scale scraping with proxy rotation + CAPTCHA solving',
        url: 'https://brightdata.com',
        setupTime: '1-2 days',
        pros: ['Scales scraping', 'Proxy network included', 'CAPTCHA solving'],
        cons: ['Expensive', 'Requires dev knowledge', 'Ethical considerations'],
      },
      {
        name: 'ScrapingBee',
        startingPrice: 'Free (1000 credits) → $49/mo+',
        pricingNotes: 'Credit-based. Simple API.',
        bestFor: 'Simple scraping API with proxy + CAPTCHA handling',
        url: 'https://scrapingbee.com',
        setupTime: '30 minutes',
        pros: ['Simple API', 'Handles proxies + CAPTCHAs', 'Good free tier'],
        cons: ['API-only', 'Credit-based pricing', 'Requires dev knowledge'],
      },
    ],
    keyConsiderations: [
      'Scale — 100 pages or 1M?',
      'Frequency — one-time or ongoing monitoring?',
      'Anti-scraping measures (CAPTCHAs, rate limits)',
      'Legal compliance (ToS, GDPR, robots.txt)',
    ],
  },
  {
    id: 'marketing-automation',
    pattern: 'marketing automation, email automation, lead nurturing, drip campaigns, marketing workflow, lifecycle email',
    category: 'Marketing Automation',
    buildComplexity: 'complex',
    buildHours: { min: 250, max: 800 },
    buildCost: { min: 25000, max: 80000 },
    ongoingMaintenanceHrs: 30,
    saasAlternatives: [
      {
        name: 'HubSpot Marketing Hub',
        startingPrice: '$890/mo (Professional)',
        pricingNotes: 'Jumps from free CRM to $890/mo for automation.',
        bestFor: 'All-in-one marketing automation for growing companies',
        url: 'https://hubspot.com/products/marketing',
        setupTime: '2-4 weeks',
        pros: ['All-in-one platform', 'Free CRM tier', 'Strong workflows'],
        cons: ['Expensive ($890/mo for Pro)', 'Pricing jumps dramatically', 'Complex setup'],
      },
      {
        name: 'Customer.io',
        startingPrice: '$150/mo',
        pricingNotes: 'Scales with messages sent.',
        bestFor: 'Product teams wanting behavior-triggered messaging',
        url: 'https://customer.io',
        setupTime: '1-2 weeks',
        pros: ['Best for behavior-triggered messaging', 'Multi-channel', 'Strong visual workflows'],
        cons: ['Focused on product companies', 'Pricing scales with messages', 'Requires dev setup'],
      },
      {
        name: 'Klaviyo',
        startingPrice: 'Free (250 contacts) → $45/mo+',
        pricingNotes: 'Scales with contact count. Generous free tier.',
        bestFor: 'E-commerce email + SMS marketing with AI predictions',
        url: 'https://klaviyo.com',
        setupTime: '3-5 days',
        pros: ['Best for e-commerce', 'Strong Shopify integration', 'Generous free tier'],
        cons: ['E-commerce focused', 'Pricing scales with contacts', 'Less flexible than Customer.io'],
      },
      {
        name: 'ActiveCampaign',
        startingPrice: '$15/mo (Lite) → $145/mo (Enterprise)',
        pricingNotes: 'Per-contact pricing. Affordable entry.',
        bestFor: 'SMBs wanting affordable marketing automation',
        url: 'https://activecampaign.com',
        setupTime: '3-5 days',
        pros: ['Affordable', 'Good automation features', 'CRM included'],
        cons: ['Less powerful than HubSpot', 'Dated UI', 'Per-contact pricing'],
      },
    ],
    keyConsiderations: [
      'Is this for e-commerce or SaaS?',
      'Behavior-triggered vs time-based campaigns?',
      'Multi-channel needs (email, SMS, push, in-app)',
      'Integration with CRM + product analytics',
    ],
  },
  {
    id: 'document-signing',
    pattern: 'document signing, e-signature, contract signing, electronic signature, doc sign, esign',
    category: 'E-Signature / Document Signing',
    buildComplexity: 'moderate',
    buildHours: { min: 100, max: 400 },
    buildCost: { min: 10000, max: 40000 },
    ongoingMaintenanceHrs: 10,
    saasAlternatives: [
      {
        name: 'DocuSign',
        startingPrice: '$10/mo (Personal) → $45/mo (Business Pro)',
        pricingNotes: 'Per-user. Standard for enterprise.',
        bestFor: 'Industry-standard e-signature for any business',
        url: 'https://docusign.com',
        setupTime: '1-2 hours',
        pros: ['Industry standard', 'Legally binding everywhere', 'Enterprise-grade'],
        cons: ['Expensive at scale', 'Per-user pricing', 'Overkill for simple signing'],
      },
      {
        name: 'HelloSign (Dropbox)',
        startingPrice: 'Free (3/mo) → $15/mo+',
        pricingNotes: 'Free tier available. Per-user for teams.',
        bestFor: 'Simple e-signature with good free tier',
        url: 'https://helloSign.com',
        setupTime: '30 minutes',
        pros: ['Free tier (3 docs/mo)', 'Simple + affordable', 'Good API'],
        cons: ['Less features than DocuSign', 'Owned by Dropbox', 'Limited templates on free'],
      },
      {
        name: 'PandaDoc',
        startingPrice: '$19/user/mo → $49/user/mo (Business)',
        pricingNotes: 'Per-user. Includes document creation + signing.',
        bestFor: 'Document creation + e-signature in one',
        url: 'https://pandadoc.com',
        setupTime: '1-2 days',
        pros: ['Document builder + signing', 'Good templates', 'CRM integrations'],
        cons: ['More expensive than HelloSign', 'Per-user pricing', 'Best for sales docs'],
      },
    ],
    keyConsiderations: [
      'Legal compliance — e-signature laws vary by country',
      'Audit trail requirements',
      'Template management for recurring documents',
      'Integration with CRM or contract management',
    ],
  },
  {
    id: 'team-chat',
    pattern: 'team chat, messaging, communication tool, team communication, instant messaging, collaboration tool',
    category: 'Team Communication',
    buildComplexity: 'very-complex',
    buildHours: { min: 500, max: 2000 },
    buildCost: { min: 50000, max: 200000 },
    ongoingMaintenanceHrs: 50,
    saasAlternatives: [
      {
        name: 'Slack',
        startingPrice: 'Free → $7/user/mo (Pro)',
        pricingNotes: 'Free tier with 90-day history. Per-user for paid.',
        bestFor: 'Team communication with integrations + automation',
        url: 'https://slack.com',
        setupTime: '30 minutes',
        pros: ['Industry standard', '2,600+ integrations', 'Workflow Builder'],
        cons: ['Per-user pricing adds up', 'Message history limited on free', 'Notification overload'],
      },
      {
        name: 'Microsoft Teams',
        startingPrice: 'Free → $4/user/mo (M365)',
        pricingNotes: 'Included with Microsoft 365.',
        bestFor: 'Microsoft-centric organizations',
        url: 'https://teams.microsoft.com',
        setupTime: '1-2 days',
        pros: ['Included with M365', 'Video + chat + files', 'Native MS integration'],
        cons: ['Less polished than Slack', 'Best with M365 subscription', 'Limited third-party integrations'],
      },
      {
        name: 'Discord',
        startingPrice: 'Free → $9.99/mo (Nitro)',
        pricingNotes: 'Free for most features. Nitro for perks.',
        bestFor: 'Community-driven teams + gaming companies',
        url: 'https://discord.com',
        setupTime: '30 minutes',
        pros: ['Free for most features', 'Great voice chat', 'Good for communities'],
        cons: ['Not built for business', 'Less professional', 'Limited integrations'],
      },
    ],
    keyConsiderations: [
      'NEVER build team chat from scratch — it\'s a commodity',
      'Integration with existing tools (CRM, project management)',
      'Video calling needs',
      'Data retention + compliance requirements',
    ],
  },
  {
    id: 'booking-system',
    pattern: 'booking system, reservation system, appointment booking, scheduling system, reservation, booking platform',
    category: 'Booking / Reservation System',
    buildComplexity: 'complex',
    buildHours: { min: 300, max: 1000 },
    buildCost: { min: 30000, max: 100000 },
    ongoingMaintenanceHrs: 35,
    saasAlternatives: [
      {
        name: 'Cal.com',
        startingPrice: 'Free (open source) → $12/user/mo',
        pricingNotes: 'Open source is free. Cloud is per-user.',
        bestFor: 'Self-hostable scheduling with Calendly-like features',
        url: 'https://cal.com',
        setupTime: '30 minutes',
        pros: ['Open source', 'Free self-hosted', 'Good integrations'],
        cons: ['Newer than Calendly', 'Self-hosting overhead', 'Less polished'],
      },
      {
        name: 'Calendly',
        startingPrice: 'Free (1 event type) → $10/user/mo',
        pricingNotes: 'Free tier for basic. Per-user for teams.',
        bestFor: 'Simple meeting scheduling — the industry standard',
        url: 'https://calendly.com',
        setupTime: '15 minutes',
        pros: ['Easiest to use', 'Industry standard', 'Good integrations'],
        cons: ['Per-user pricing', 'Limited free tier', 'Less customizable'],
      },
      {
        name: 'Acuity Scheduling',
        startingPrice: '$15/mo → $50/mo',
        pricingNotes: 'Per-month, not per-user. Good for service businesses.',
        bestFor: 'Service businesses (salons, consultants, trainers)',
        url: 'https://acuityscheduling.com',
        setupTime: '1-2 hours',
        pros: ['Built for service businesses', 'Payment collection', 'Good for classes/groups'],
        cons: ['Less flexible than Cal.com', 'Per-month pricing', 'Owned by Squarespace'],
      },
      {
        name: 'FareHarbor',
        startingPrice: 'Custom (percentage-based)',
        pricingNotes: 'Percentage of bookings. Built for tours/activities.',
        bestFor: 'Tour operators + activity businesses',
        url: 'https://fareharbor.com',
        setupTime: '1-2 weeks',
        pros: ['Built for tours/activities', 'Handles inventory + payments', 'Good for complex bookings'],
        cons: ['Percentage-based pricing', 'Niche focus', 'Less flexible'],
      },
    ],
    keyConsiderations: [
      'Is this for meetings (scheduling) or reservations (inventory)?',
      'Payment collection at booking time?',
      'Group/class bookings vs 1:1?',
      'Timezone handling + calendar integration',
    ],
  },
  {
    id: 'inventory',
    pattern: 'inventory management, stock management, warehouse management, inventory tracking, stock control',
    category: 'Inventory Management',
    buildComplexity: 'complex',
    buildHours: { min: 400, max: 1500 },
    buildCost: { min: 40000, max: 150000 },
    ongoingMaintenanceHrs: 40,
    saasAlternatives: [
      {
        name: 'ShipHero',
        startingPrice: 'Custom (~$500/mo+)',
        pricingNotes: 'Per-warehouse + per-user. Enterprise-focused.',
        bestFor: 'E-commerce fulfillment + warehouse management',
        url: 'https://shiphero.com',
        setupTime: '2-4 weeks',
        pros: ['Best WMS for e-commerce', 'Handles picking + packing', 'Integrates with Shopify/Amazon'],
        cons: ['Expensive', 'Complex setup', 'Best for $1M+ revenue'],
      },
      {
        name: 'Fishbowl',
        startingPrice: '$4,395/yr (one-time license)',
        pricingNotes: 'One-time license + annual maintenance. On-premise.',
        bestFor: 'Manufacturers + wholesalers wanting on-premise inventory',
        url: 'https://fishbowlinventory.com',
        setupTime: '2-4 weeks',
        pros: ['One-time pricing', 'On-premise (data stays in-house)', 'Good for manufacturing'],
        cons: ['Upfront cost', 'Dated UI', 'On-premise = you maintain it'],
      },
      {
        name: 'Cin7',
        startingPrice: '$299/mo → $999/mo',
        pricingNotes: 'Per-month. Scales with features + integrations.',
        bestFor: 'Mid-market inventory + order management + B2B',
        url: 'https://cin7.com',
        setupTime: '2-4 weeks',
        pros: ['All-in-one inventory + order management', 'Good integrations', 'B2B + B2C'],
        cons: ['Expensive', 'Complex setup', 'Best for mid-market'],
      },
      {
        name: 'TradeGecko (QuickBooks)',
        startingPrice: '$39/mo → $199/mo',
        pricingNotes: 'Per-month. Now owned by Intuit/QuickBooks.',
        bestFor: 'SMBs wanting simple inventory + QuickBooks integration',
        url: 'https://quickbooks.intuit.com/inventory/',
        setupTime: '1-2 weeks',
        pros: ['Affordable', 'QuickBooks integration', 'Good for SMBs'],
        cons: ['Less powerful than Cin7', 'Owned by Intuit', 'Limited for manufacturing'],
      },
    ],
    keyConsiderations: [
      'Multi-warehouse needs?',
      'Integration with e-commerce platform + accounting',
      'Barcode scanning + mobile app needs',
      'Manufacturing (BOM, work orders) vs simple stock tracking',
    ],
  },
  {
    id: 'learning-platform',
    pattern: 'learning management system, LMS, course platform, online course, training platform, e-learning, education platform',
    category: 'Learning / Course Platform',
    buildComplexity: 'complex',
    buildHours: { min: 400, max: 1200 },
    buildCost: { min: 40000, max: 120000 },
    ongoingMaintenanceHrs: 30,
    saasAlternatives: [
      {
        name: 'Teachable',
        startingPrice: 'Free → $39/mo (Basic) → $119/mo (Pro)',
        pricingNotes: 'Per-month + transaction fees on lower tiers.',
        bestFor: 'Creators selling online courses',
        url: 'https://teachable.com',
        setupTime: '1-2 days',
        pros: ['Easy to use', 'Good for creators', 'Handles payments'],
        cons: ['Transaction fees on lower tiers', 'Limited customization', 'Not for corporate training'],
      },
      {
        name: 'Thinkific',
        startingPrice: 'Free → $36/mo (Basic) → $99/mo (Pro)',
        pricingNotes: 'Free tier available. No transaction fees.',
        bestFor: 'Course creators wanting more control than Teachable',
        url: 'https://thinkific.com',
        setupTime: '1-2 days',
        pros: ['No transaction fees', 'Free tier', 'More customizable than Teachable'],
        cons: ['Less polished UI', 'Fewer marketing features', 'Best for individual creators'],
      },
      {
        name: 'Mighty Networks',
        startingPrice: '$41/mo (Community) → $98/mo (Business)',
        pricingNotes: 'Per-month. Community + courses in one.',
        bestFor: 'Community + courses together (not just courses)',
        url: 'https://mightynetworks.com',
        setupTime: '2-3 days',
        pros: ['Community + courses in one', 'Good for memberships', 'Mobile app included'],
        cons: ['More expensive', 'Less course-focused', 'Learning curve'],
      },
      {
        name: 'Docebo',
        startingPrice: 'Custom (~$900/mo+)',
        pricingNotes: 'Enterprise pricing. Per-user.',
        bestFor: 'Enterprise corporate training + L&D',
        url: 'https://docebo.com',
        setupTime: '4-8 weeks',
        pros: ['Enterprise-grade', 'AI-powered learning', 'Good for large orgs'],
        cons: ['Very expensive', 'Months to implement', 'Overkill for small teams'],
      },
    ],
    keyConsiderations: [
      'Creator courses vs corporate training?',
      'Community features (discussions, groups)?',
      'Certification + compliance tracking?',
      'Integration with HRIS or CRM',
    ],
  },
  {
    id: 'community-platform',
    pattern: 'community platform, forum, discussion board, online community, community management, member portal',
    category: 'Community Platform',
    buildComplexity: 'complex',
    buildHours: { min: 300, max: 1000 },
    buildCost: { min: 30000, max: 100000 },
    ongoingMaintenanceHrs: 25,
    saasAlternatives: [
      {
        name: 'Circle',
        startingPrice: '$39/mo (Basic) → $99/mo (Pro)',
        pricingNotes: 'Per-month. Scales with members + features.',
        bestFor: 'Modern community platform for creators + brands',
        url: 'https://circle.so',
        setupTime: '1-2 days',
        pros: ['Best modern community platform', 'Good UX', 'Integrates with course tools'],
        cons: ['Per-month pricing', 'Limited customization', 'Newer'],
      },
      {
        name: 'Discord',
        startingPrice: 'Free → $9.99/mo (Nitro)',
        pricingNotes: 'Free for most features. Nitro for perks.',
        bestFor: 'Gaming + tech communities (free + real-time)',
        url: 'https://discord.com',
        setupTime: '30 minutes',
        pros: ['Free', 'Real-time chat', 'Great for tech communities'],
        cons: ['Not built for business', 'Less structured', 'Hard to search history'],
      },
      {
        name: 'Slack (communities)',
        startingPrice: 'Free → $7/user/mo',
        pricingNotes: 'Free tier with 90-day history.',
        bestFor: 'Professional communities (shared Slack workspace)',
        url: 'https://slack.com',
        setupTime: '30 minutes',
        pros: ['Familiar to professionals', 'Free tier', 'Many integrations'],
        cons: ['90-day history limit on free', 'Not purpose-built for communities', 'Notification overload'],
      },
      {
        name: 'Geneva',
        startingPrice: 'Free',
        pricingNotes: 'Free for now. Monetization coming.',
        bestFor: 'Close-knit communities wanting chat + forums',
        url: 'https://geneva.com',
        setupTime: '30 minutes',
        pros: ['Free', 'Chat + forums + voice', 'Good for close communities'],
        cons: ['Very new', 'No monetization yet', 'Limited integrations'],
      },
    ],
    keyConsiderations: [
      'Real-time chat vs threaded discussions?',
      'Monetization (paid memberships)?',
      'Content discovery + search',
      'Mobile app importance',
    ],
  },
];

// Helper: find matching scenarios based on user input
export function findMatchingScenarios(userInput: string): BuildScenario[] {
  const input = userInput.toLowerCase();
  const matches = BUILD_SCENARIOS.filter((scenario) => {
    return scenario.pattern
      .split(',')
      .some((keyword) => input.includes(keyword.trim()));
  });
  return matches.length > 0 ? matches : BUILD_SCENARIOS;
}
