// Knowledge base for the AI Token Cost Calculator tool.
// Real pricing data for major LLM providers + intelligence layers
// for cost optimization, model selection, and spend analysis.

export interface ModelPricing {
  id: string;
  provider: string;
  model: string;
  contextWindow: number;         // Max tokens in context
  inputPricePerM: number;        // $ per 1M input tokens
  outputPricePerM: number;       // $ per 1M output tokens
  cachedInputPricePerM?: number; // $ per 1M cached input tokens (if supported)
  batchPricePerM?: number;       // $ per 1M batch input tokens (if supported)
  freeTier: string | null;
  capabilities: string[];        // text, vision, audio, function-calling, etc.
  qualityTier: 'frontier' | 'high' | 'mid' | 'budget';
  latencyMs: number;             // Typical time to first token
  throughputTps: number;         // Tokens per second
  bestFor: string;
  notes: string;
}

// Pricing as of mid-2026. Verify before publishing.
// Sources: provider pricing pages.
export const MODELS: ModelPricing[] = [
  // ============ OPENAI ============
  {
    id: 'gpt-4o',
    provider: 'OpenAI',
    model: 'GPT-4o',
    contextWindow: 128000,
    inputPricePerM: 2.5,
    outputPricePerM: 10,
    cachedInputPricePerM: 1.25,
    freeTier: null,
    capabilities: ['text', 'vision', 'audio', 'function-calling', 'json-mode'],
    qualityTier: 'frontier',
    latencyMs: 800,
    throughputTps: 80,
    bestFor: 'General-purpose AI tasks, multimodal, production apps',
    notes: 'Best all-around model. Cached input is 50% cheaper. Batch API is 50% cheaper.',
  },
  {
    id: 'gpt-4o-mini',
    provider: 'OpenAI',
    model: 'GPT-4o mini',
    contextWindow: 128000,
    inputPricePerM: 0.15,
    outputPricePerM: 0.6,
    cachedInputPricePerM: 0.075,
    freeTier: null,
    capabilities: ['text', 'vision', 'function-calling', 'json-mode'],
    qualityTier: 'budget',
    latencyMs: 400,
    throughputTps: 150,
    bestFor: 'High-volume, cost-sensitive tasks. Classification, extraction, simple chat.',
    notes: 'Best $/quality ratio for most production workloads. 16x cheaper than GPT-4o on input.',
  },
  {
    id: 'o1',
    provider: 'OpenAI',
    model: 'o1',
    contextWindow: 200000,
    inputPricePerM: 15,
    outputPricePerM: 60,
    freeTier: null,
    capabilities: ['text', 'reasoning', 'function-calling'],
    qualityTier: 'frontier',
    latencyMs: 5000,
    throughputTps: 50,
    bestFor: 'Complex reasoning, math, coding, multi-step problems',
    notes: 'Reasoning model. Thinks before answering. Very expensive but solves problems others cannot.',
  },
  {
    id: 'o1-mini',
    provider: 'OpenAI',
    model: 'o1-mini',
    contextWindow: 128000,
    inputPricePerM: 3,
    outputPricePerM: 12,
    freeTier: null,
    capabilities: ['text', 'reasoning'],
    qualityTier: 'high',
    latencyMs: 3000,
    throughputTps: 60,
    bestFor: 'Cost-effective reasoning for coding and math',
    notes: 'Cheaper than o1 but still thinks. Good for code generation + debugging.',
  },
  {
    id: 'o3-mini',
    provider: 'OpenAI',
    model: 'o3-mini',
    contextWindow: 200000,
    inputPricePerM: 1.1,
    outputPricePerM: 4.4,
    cachedInputPricePerM: 0.55,
    freeTier: null,
    capabilities: ['text', 'reasoning', 'function-calling'],
    qualityTier: 'high',
    latencyMs: 2000,
    throughputTps: 100,
    bestFor: 'Fast reasoning at a reasonable price. Best reasoning $/quality ratio.',
    notes: 'Newest reasoning model. Cheaper than o1-mini with better reasoning. Recommended for most reasoning tasks.',
  },

  // ============ ANTHROPIC ============
  {
    id: 'claude-3.5-sonnet',
    provider: 'Anthropic',
    model: 'Claude 3.5 Sonnet',
    contextWindow: 200000,
    inputPricePerM: 3,
    outputPricePerM: 15,
    cachedInputPricePerM: 0.3,
    freeTier: null,
    capabilities: ['text', 'vision', 'function-calling', 'json-mode'],
    qualityTier: 'frontier',
    latencyMs: 1000,
    throughputTps: 70,
    bestFor: 'Long documents, coding, structured extraction, careful reasoning',
    notes: 'Best for long-context tasks (200K tokens). Cached input is 90% cheaper. Prompt caching is a game-changer for RAG.',
  },
  {
    id: 'claude-3.5-haiku',
    provider: 'Anthropic',
    model: 'Claude 3.5 Haiku',
    contextWindow: 200000,
    inputPricePerM: 0.8,
    outputPricePerM: 4,
    freeTier: null,
    capabilities: ['text', 'vision', 'function-calling'],
    qualityTier: 'mid',
    latencyMs: 500,
    throughputTps: 120,
    bestFor: 'Fast, affordable Claude. Good for high-volume tasks needing Claude quality.',
    notes: '10x cheaper input than Sonnet. Same 200K context. Good middle ground between GPT-4o-mini and Sonnet.',
  },
  {
    id: 'claude-3-opus',
    provider: 'Anthropic',
    model: 'Claude 3 Opus',
    contextWindow: 200000,
    inputPricePerM: 15,
    outputPricePerM: 75,
    freeTier: null,
    capabilities: ['text', 'vision', 'function-calling'],
    qualityTier: 'frontier',
    latencyMs: 2000,
    throughputTps: 40,
    bestFor: 'Most capable Claude for complex tasks. Now largely superseded by 3.5 Sonnet.',
    notes: 'Expensive. Use only when you need the absolute best Claude quality and 3.5 Sonnet is not enough. Most users should use 3.5 Sonnet instead.',
  },

  // ============ GOOGLE ============
  {
    id: 'gemini-2.0-flash',
    provider: 'Google',
    model: 'Gemini 2.0 Flash',
    contextWindow: 1000000,
    inputPricePerM: 0.1,
    outputPricePerM: 0.4,
    freeTier: 'Free tier: 15 RPM, 150K tokens/min, 1000 requests/day',
    capabilities: ['text', 'vision', 'audio', 'video', 'function-calling', 'json-mode'],
    qualityTier: 'mid',
    latencyMs: 300,
    throughputTps: 200,
    bestFor: 'Cheapest frontier-quality model. Multimodal. 1M context window.',
    notes: 'Best free tier available. 1M token context is unmatched. Great for high-volume + multimodal.',
  },
  {
    id: 'gemini-2.0-pro',
    provider: 'Google',
    model: 'Gemini 2.0 Pro',
    contextWindow: 2000000,
    inputPricePerM: 1.25,
    outputPricePerM: 5,
    freeTier: 'Free tier: 2 RPM, limited',
    capabilities: ['text', 'vision', 'audio', 'video', 'function-calling'],
    qualityTier: 'frontier',
    latencyMs: 800,
    throughputTps: 100,
    bestFor: 'Massive context (2M tokens). Best for analyzing entire codebases or document sets.',
    notes: '2M token context is the largest available. Use when you need to process entire books or codebases.',
  },
  {
    id: 'gemini-1.5-flash',
    provider: 'Google',
    model: 'Gemini 1.5 Flash',
    contextWindow: 1000000,
    inputPricePerM: 0.075,
    outputPricePerM: 0.3,
    freeTier: 'Free tier: 15 RPM, 150K tokens/min',
    capabilities: ['text', 'vision', 'audio', 'function-calling'],
    qualityTier: 'budget',
    latencyMs: 200,
    throughputTps: 250,
    bestFor: 'Ultra-cheap. Best for massive volume where quality is not critical.',
    notes: 'Cheapest model on the market with a free tier. 2x cheaper than GPT-4o-mini.',
  },

  // ============ GROQ ============
  {
    id: 'groq-llama-3.3-70b',
    provider: 'Groq',
    model: 'Llama 3.3 70B (Groq)',
    contextWindow: 128000,
    inputPricePerM: 0.59,
    outputPricePerM: 0.79,
    freeTier: 'Free tier: 30 RPM, 12K TPM, 14K requests/day',
    capabilities: ['text', 'function-calling', 'json-mode'],
    qualityTier: 'mid',
    latencyMs: 100,
    throughputTps: 500,
    bestFor: 'Fastest inference available. Best for real-time + high-volume apps.',
    notes: '500+ tokens/sec. 5-10x faster than any other provider. Free tier is generous. OpenAI-compatible API.',
  },
  {
    id: 'groq-llama-3.1-8b',
    provider: 'Groq',
    model: 'Llama 3.1 8B (Groq)',
    contextWindow: 128000,
    inputPricePerM: 0.05,
    outputPricePerM: 0.08,
    freeTier: 'Free tier: 30 RPM, 12K TPM, 14K requests/day',
    capabilities: ['text', 'function-calling'],
    qualityTier: 'budget',
    latencyMs: 50,
    throughputTps: 800,
    bestFor: 'Ultra-fast + ultra-cheap. Best for simple tasks at massive scale.',
    notes: 'Fastest + cheapest combination. Quality is lower than 70B but sufficient for classification, extraction, simple chat.',
  },

  // ============ TOGETHER AI ============
  {
    id: 'together-llama-3.3-70b',
    provider: 'Together AI',
    model: 'Llama 3.3 70B (Together)',
    contextWindow: 128000,
    inputPricePerM: 0.88,
    outputPricePerM: 0.88,
    freeTier: '$5 free credit on signup',
    capabilities: ['text', 'function-calling', 'json-mode'],
    qualityTier: 'mid',
    latencyMs: 300,
    throughputTps: 150,
    bestFor: 'Self-hosted alternative. Open-source models with managed infrastructure.',
    notes: 'Same model as Groq but different infra. Slower but more reliable for production. 200+ models available.',
  },
  {
    id: 'together-qwen-2.5-72b',
    provider: 'Together AI',
    model: 'Qwen 2.5 72B (Together)',
    contextWindow: 32768,
    inputPricePerM: 0.88,
    outputPricePerM: 0.88,
    freeTier: '$5 free credit on signup',
    capabilities: ['text', 'function-calling'],
    qualityTier: 'mid',
    latencyMs: 300,
    throughputTps: 150,
    bestFor: 'Strong multilingual + coding. Alternative to Llama for non-English tasks.',
    notes: 'Qwen models are best-in-class for Chinese, Japanese, Korean. Good coding model.',
  },

  // ============ MISTRAL ============
  {
    id: 'mistral-large',
    provider: 'Mistral',
    model: 'Mistral Large 2',
    contextWindow: 128000,
    inputPricePerM: 2,
    outputPricePerM: 6,
    freeTier: 'Free tier on La Plateforme',
    capabilities: ['text', 'function-calling', 'json-mode'],
    qualityTier: 'high',
    latencyMs: 600,
    throughputTps: 80,
    bestFor: 'European data residency. Strong multilingual. Good function calling.',
    notes: 'EU-hosted. Good for GDPR-sensitive apps. Quality close to GPT-4o but cheaper.',
  },
  {
    id: 'mistral-small',
    provider: 'Mistral',
    model: 'Mistral Small 3',
    contextWindow: 32000,
    inputPricePerM: 0.2,
    outputPricePerM: 0.6,
    freeTier: 'Free tier on La Plateforme',
    capabilities: ['text', 'function-calling'],
    qualityTier: 'budget',
    latencyMs: 300,
    throughputTps: 150,
    bestFor: 'Budget European option. Good for EU compliance at low cost.',
    notes: '10x cheaper than Large. Good for high-volume EU workloads.',
  },

  // ============ COHERE ============
  {
    id: 'cohere-command-r-plus',
    provider: 'Cohere',
    model: 'Command R+',
    contextWindow: 128000,
    inputPricePerM: 2.5,
    outputPricePerM: 10,
    freeTier: 'Free trial credits',
    capabilities: ['text', 'function-calling', 'rag'],
    qualityTier: 'high',
    latencyMs: 800,
    throughputTps: 60,
    bestFor: 'RAG applications. Best embeddings + reranking in one platform.',
    notes: 'Purpose-built for enterprise RAG. If your app is search/retrieval heavy, Cohere is purpose-built for it.',
  },
  {
    id: 'cohere-command-r',
    provider: 'Cohere',
    model: 'Command R',
    contextWindow: 128000,
    inputPricePerM: 0.15,
    outputPricePerM: 0.6,
    freeTier: 'Free trial credits',
    capabilities: ['text', 'function-calling', 'rag'],
    qualityTier: 'mid',
    latencyMs: 500,
    throughputTps: 100,
    bestFor: 'Budget RAG. Same RAG features as R+ but cheaper.',
    notes: '17x cheaper than R+ on input. Good for high-volume RAG workloads.',
  },

  // ============ DEEPSEEK ============
  {
    id: 'deepseek-v3',
    provider: 'DeepSeek',
    model: 'DeepSeek V3',
    contextWindow: 64000,
    inputPricePerM: 0.27,
    outputPricePerM: 1.1,
    cachedInputPricePerM: 0.07,
    freeTier: 'Free tier (limited)',
    capabilities: ['text', 'function-calling', 'json-mode', 'reasoning'],
    qualityTier: 'high',
    latencyMs: 800,
    throughputTps: 60,
    bestFor: 'Frontier-quality at budget prices. Best $/quality ratio overall.',
    notes: 'Quality rivals GPT-4o at 10x lower cost. Cached input is incredibly cheap ($0.07/M). Chinese-hosted.',
  },
  {
    id: 'deepseek-r1',
    provider: 'DeepSeek',
    model: 'DeepSeek R1',
    contextWindow: 64000,
    inputPricePerM: 0.55,
    outputPricePerM: 2.19,
    cachedInputPricePerM: 0.14,
    freeTier: 'Free tier (limited)',
    capabilities: ['text', 'reasoning', 'function-calling'],
    qualityTier: 'frontier',
    latencyMs: 3000,
    throughputTps: 50,
    bestFor: 'Reasoning at a fraction of o1 cost. Open weights.',
    notes: 'Reasoning model rivaling o1 at 25x lower cost. Open weights available for self-hosting.',
  },

  // ============ AMAZON ============
  {
    id: 'amazon-nova-pro',
    provider: 'Amazon',
    model: 'Nova Pro',
    contextWindow: 300000,
    inputPricePerM: 0.8,
    outputPricePerM: 3.2,
    freeTier: 'Free tier on AWS',
    capabilities: ['text', 'vision', 'function-calling'],
    qualityTier: 'high',
    latencyMs: 600,
    throughputTps: 100,
    bestFor: 'AWS-native teams. Good multimodal at reasonable price.',
    notes: 'Amazon latest model. Good if you are already on AWS. 300K context.',
  },
  {
    id: 'amazon-nova-lite',
    provider: 'Amazon',
    model: 'Nova Lite',
    contextWindow: 300000,
    inputPricePerM: 0.06,
    outputPricePerM: 0.24,
    freeTier: 'Free tier on AWS',
    capabilities: ['text', 'vision', 'function-calling'],
    qualityTier: 'budget',
    latencyMs: 300,
    throughputTps: 200,
    bestFor: 'Ultra-cheap AWS option. Good for high-volume AWS workloads.',
    notes: 'One of the cheapest models available. Good multimodal for the price.',
  },
];

// ============ COST OPTIMIZATION TIPS ============
export const OPTIMIZATION_TIPS = [
  {
    title: 'Use prompt caching',
    description: 'If you send the same system prompt or context repeatedly, cached input is 50-90% cheaper. Anthropic offers 90% discount on cached input. OpenAI offers 50%.',
    providers: ['OpenAI', 'Anthropic', 'DeepSeek'],
    savings: '50-90%',
  },
  {
    title: 'Use batch API for non-real-time tasks',
    description: 'OpenAI and Anthropic offer 50% discount for batch processing (non-urgent). Submit requests in bulk, get results within 24 hours.',
    providers: ['OpenAI', 'Anthropic'],
    savings: '50%',
  },
  {
    title: 'Right-size your model',
    description: 'Most tasks do not need GPT-4o or Claude Sonnet. Use GPT-4o-mini or Claude Haiku for 90% of tasks. Reserve frontier models for complex reasoning. A typical split: 80% mini/haiku, 15% mid-tier, 5% frontier.',
    providers: ['All'],
    savings: '70-90%',
  },
  {
    title: 'Use Groq for speed-sensitive tasks',
    description: 'Groq runs Llama models at 500+ tokens/sec. If latency matters (chat, real-time), Groq is 5-10x faster than any other provider. Same model, different infra.',
    providers: ['Groq'],
    savings: 'N/A (speed, not cost)',
  },
  {
    title: 'Cache aggressively on the client side',
    description: 'Cache common queries in Redis or your database. If a user asks the same question twice, serve from cache instead of calling the API. Cache hit rate of 30% cuts costs by 30%.',
    providers: ['All'],
    savings: '20-40%',
  },
  {
    title: 'Use DeepSeek for frontier quality at budget prices',
    description: 'DeepSeek V3 rivals GPT-4o quality at 10x lower cost. R1 rivals o1 at 25x lower cost. If data residency allows, this is the best $/quality ratio available.',
    providers: ['DeepSeek'],
    savings: '90%',
  },
  {
    title: 'Compress your prompts',
    description: 'Long prompts cost more. Remove unnecessary examples, use concise instructions, and leverage structured formats (JSON) instead of natural language for system prompts. A 2000-token prompt can often be compressed to 500 tokens.',
    providers: ['All'],
    savings: '30-60%',
  },
  {
    title: 'Use free tiers for development',
    description: 'Google Gemini 2.0 Flash has a generous free tier (15 RPM, 1000 req/day). Groq has 14K requests/day free. Use these for development and testing, switch to paid for production.',
    providers: ['Google', 'Groq'],
    savings: '100% (during dev)',
  },
  {
    title: 'Route by complexity',
    description: 'Build a router that sends simple queries to cheap models (GPT-4o-mini, Gemini Flash) and complex queries to expensive models (GPT-4o, Claude Sonnet). A simple classifier can route 80% of traffic to the cheap model.',
    providers: ['All'],
    savings: '60-80%',
  },
  {
    title: 'Use open-weights models for high volume',
    description: 'If you process >100M tokens/month, self-hosting Llama 3.3 70B on Together AI or your own GPU is cheaper than any API. Break-even is around 100M tokens/month.',
    providers: ['Together AI', 'Groq', 'self-hosted'],
    savings: '50-80% (at high volume)',
  },
];

// ============ MODEL SELECTION GUIDE ============
export const MODEL_SELECTION_GUIDE = [
  {
    useCase: 'General chatbot / assistant',
    recommended: 'GPT-4o mini or Claude 3.5 Haiku',
    reasoning: 'Best $/quality for conversational AI. Most users cannot tell the difference from frontier models.',
    budget: '$0.15-0.80/M input',
  },
  {
    useCase: 'Document analysis / RAG',
    recommended: 'Claude 3.5 Sonnet (with prompt caching)',
    reasoning: '200K context + 90% cache discount = cheapest for repeated document queries. Best extraction quality.',
    budget: '$0.30/M cached input',
  },
  {
    useCase: 'Coding / code generation',
    recommended: 'Claude 3.5 Sonnet or o3-mini',
    reasoning: 'Sonnet is best for multi-file edits. o3-mini is best for debugging + complex logic.',
    budget: '$3-4.40/M output',
  },
  {
    useCase: 'High-volume classification / extraction',
    recommended: 'Gemini 1.5 Flash or GPT-4o mini',
    reasoning: 'Cheapest options. Gemini Flash has a free tier. GPT-4o mini has best JSON mode.',
    budget: '$0.075-0.15/M input',
  },
  {
    useCase: 'Real-time / low-latency',
    recommended: 'Groq Llama 3.3 70B',
    reasoning: '500+ tokens/sec. 5-10x faster than any other provider. Same model quality.',
    budget: '$0.59/M input',
  },
  {
    useCase: 'Complex reasoning / math',
    recommended: 'o3-mini or DeepSeek R1',
    reasoning: 'o3-mini is best reasoning $/quality. R1 is 4x cheaper but Chinese-hosted.',
    budget: '$0.55-1.10/M input',
  },
  {
    useCase: 'Multimodal (images, audio, video)',
    recommended: 'Gemini 2.0 Flash or GPT-4o',
    reasoning: 'Gemini is cheapest with free tier. GPT-4o has best vision quality.',
    budget: '$0.10-2.50/M input',
  },
  {
    useCase: 'EU data residency',
    recommended: 'Mistral Large 2 or Mistral Small 3',
    reasoning: 'Hosted in EU. GDPR compliant. Quality close to GPT-4o.',
    budget: '$0.20-2.00/M input',
  },
  {
    useCase: 'Maximum context (entire codebase)',
    recommended: 'Gemini 2.0 Pro',
    reasoning: '2M token context. Nothing else comes close. Analyze entire repos.',
    budget: '$1.25/M input',
  },
  {
    useCase: 'Budget unconstrained (best quality)',
    recommended: 'Claude 3.5 Sonnet or GPT-4o',
    reasoning: 'Both are frontier quality. Sonnet is better for long context. GPT-4o is better for multimodal.',
    budget: '$2.50-3.00/M input',
  },
];
