// Knowledge base for the AI Token Cost Calculator tool.
// Comprehensive pricing data for major LLM providers + intelligence layers
// for cost optimization, model selection, and spend analysis.
// Pricing as of mid-2026. Verify before publishing.

export interface ModelPricing {
  id: string;
  provider: string;
  model: string;
  contextWindow: number;
  inputPricePerM: number;
  outputPricePerM: number;
  cachedInputPricePerM?: number;
  batchInputPricePerM?: number;
  batchOutputPricePerM?: number;
  visionPricePerM?: number;
  audioPricePerM?: number;
  freeTier: string | null;
  rateLimitRpm: number;
  rateLimitTpm: number;
  capabilities: string[];
  qualityTier: 'frontier' | 'high' | 'mid' | 'budget';
  qualityScore: number;
  latencyMs: number;
  throughputTps: number;
  bestFor: string;
  hiddenCosts: string[];
  notes: string;
}

export const MODELS: ModelPricing[] = [
  // ============ OPENAI ============
  {
    id: 'gpt-4.1',
    provider: 'OpenAI',
    model: 'GPT-4.1',
    contextWindow: 1000000,
    inputPricePerM: 2,
    outputPricePerM: 8,
    cachedInputPricePerM: 0.5,
    batchInputPricePerM: 1,
    batchOutputPricePerM: 4,
    visionPricePerM: 2,
    freeTier: null,
    rateLimitRpm: 500,
    rateLimitTpm: 800000,
    capabilities: ['text', 'vision', 'function-calling', 'json-mode', 'structured-outputs'],
    qualityTier: 'frontier',
    qualityScore: 92,
    latencyMs: 800,
    throughputTps: 80,
    bestFor: 'Latest flagship. 1M context. Best instruction following + coding. Cached input 75% cheaper.',
    hiddenCosts: ['Vision input billed at text rate but uses more tokens per image', 'Stored completions cost extra', 'Fine-tuning storage $2/GB/month'],
    notes: 'Replaces GPT-4o. 1M context window. Cached input is 75% cheaper (vs 50% on GPT-4o). Batch is 50% cheaper. Best structured outputs support.',
  },
  {
    id: 'gpt-4.1-mini',
    provider: 'OpenAI',
    model: 'GPT-4.1 mini',
    contextWindow: 1000000,
    inputPricePerM: 0.4,
    outputPricePerM: 1.6,
    cachedInputPricePerM: 0.1,
    batchInputPricePerM: 0.2,
    batchOutputPricePerM: 0.8,
    visionPricePerM: 0.4,
    freeTier: null,
    rateLimitRpm: 500,
    rateLimitTpm: 800000,
    capabilities: ['text', 'vision', 'function-calling', 'json-mode', 'structured-outputs'],
    qualityTier: 'high',
    qualityScore: 85,
    latencyMs: 400,
    throughputTps: 150,
    bestFor: 'Best $/quality ratio. 1M context. Use for 80% of production workloads.',
    hiddenCosts: ['Vision input billed at text rate', 'Token usage higher for complex prompts vs GPT-4o-mini'],
    notes: '5x cheaper than GPT-4.1 on input. Same 1M context. Cached input is 75% cheaper. This is the default recommendation for most production apps.',
  },
  {
    id: 'gpt-4.1-nano',
    provider: 'OpenAI',
    model: 'GPT-4.1 nano',
    contextWindow: 1000000,
    inputPricePerM: 0.1,
    outputPricePerM: 0.4,
    cachedInputPricePerM: 0.025,
    batchInputPricePerM: 0.05,
    batchOutputPricePerM: 0.2,
    visionPricePerM: 0.1,
    freeTier: null,
    rateLimitRpm: 500,
    rateLimitTpm: 800000,
    capabilities: ['text', 'vision', 'function-calling', 'json-mode'],
    qualityTier: 'budget',
    qualityScore: 72,
    latencyMs: 200,
    throughputTps: 250,
    bestFor: 'Ultra-cheap. Best for massive volume classification, extraction, simple tasks.',
    hiddenCosts: ['Quality drops on complex reasoning', 'May need more tokens for same output quality'],
    notes: 'Cheapest OpenAI model. 20x cheaper than GPT-4.1 input. Same 1M context. Best for high-volume simple tasks.',
  },
  {
    id: 'o3',
    provider: 'OpenAI',
    model: 'o3',
    contextWindow: 200000,
    inputPricePerM: 10,
    outputPricePerM: 40,
    cachedInputPricePerM: 2.5,
    freeTier: null,
    rateLimitRpm: 100,
    rateLimitTpm: 200000,
    capabilities: ['text', 'reasoning', 'function-calling', 'vision'],
    qualityTier: 'frontier',
    qualityScore: 96,
    latencyMs: 5000,
    throughputTps: 50,
    bestFor: 'Most powerful reasoning model. Best for math, science, complex multi-step problems.',
    hiddenCosts: ['Reasoning tokens are billed as output (expensive)', 'Can use 10-100x more output tokens than non-reasoning models', 'Slow for simple tasks'],
    notes: 'Replaces o1. Reasoning tokens are hidden but billed. A single complex query can cost $0.50+. Use only when other models cannot solve the problem.',
  },
  {
    id: 'o3-mini',
    provider: 'OpenAI',
    model: 'o3-mini',
    contextWindow: 200000,
    inputPricePerM: 1.1,
    outputPricePerM: 4.4,
    cachedInputPricePerM: 0.55,
    batchInputPricePerM: 0.55,
    batchOutputPricePerM: 2.2,
    freeTier: null,
    rateLimitRpm: 500,
    rateLimitTpm: 400000,
    capabilities: ['text', 'reasoning', 'function-calling'],
    qualityTier: 'high',
    qualityScore: 90,
    latencyMs: 2000,
    throughputTps: 100,
    bestFor: 'Cost-effective reasoning. Best reasoning $/quality ratio. Use for coding, debugging, logic.',
    hiddenCosts: ['Reasoning tokens billed as output', 'Slower than non-reasoning models'],
    notes: '9x cheaper than o3 on input. Still thinks before answering. Best reasoning value. Batch API available for 50% off.',
  },
  {
    id: 'o4-mini',
    provider: 'OpenAI',
    model: 'o4-mini',
    contextWindow: 200000,
    inputPricePerM: 1.1,
    outputPricePerM: 4.4,
    cachedInputPricePerM: 0.275,
    freeTier: null,
    rateLimitRpm: 500,
    rateLimitTpm: 400000,
    capabilities: ['text', 'reasoning', 'function-calling', 'vision'],
    qualityTier: 'high',
    qualityScore: 91,
    latencyMs: 1500,
    throughputTps: 110,
    bestFor: 'Latest mini reasoning model. Vision + reasoning. Faster than o3-mini.',
    hiddenCosts: ['Reasoning tokens billed as output', 'Newer model, less battle-tested'],
    notes: 'Newest reasoning model. Supports vision (o3-mini does not). Cached input 75% cheaper. Recommended over o3-mini for visual reasoning tasks.',
  },
  {
    id: 'gpt-4o',
    provider: 'OpenAI',
    model: 'GPT-4o (legacy)',
    contextWindow: 128000,
    inputPricePerM: 2.5,
    outputPricePerM: 10,
    cachedInputPricePerM: 1.25,
    freeTier: null,
    rateLimitRpm: 500,
    rateLimitTpm: 800000,
    capabilities: ['text', 'vision', 'audio', 'function-calling', 'json-mode'],
    qualityTier: 'frontier',
    qualityScore: 89,
    latencyMs: 800,
    throughputTps: 80,
    bestFor: 'Legacy. Migrate to GPT-4.1 for better quality + lower cost + 1M context.',
    hiddenCosts: ['Same price as GPT-4.1 but lower quality and smaller context', 'Audio input billed separately at $0.006/min'],
    notes: 'SUPERSEDED by GPT-4.1. Same price but GPT-4.1 is better in every way. Migrate now. Audio input/output available but expensive.',
  },
  {
    id: 'gpt-4o-mini',
    provider: 'OpenAI',
    model: 'GPT-4o mini (legacy)',
    contextWindow: 128000,
    inputPricePerM: 0.15,
    outputPricePerM: 0.6,
    cachedInputPricePerM: 0.075,
    freeTier: null,
    rateLimitRpm: 500,
    rateLimitTpm: 800000,
    capabilities: ['text', 'vision', 'function-calling', 'json-mode'],
    qualityTier: 'budget',
    qualityScore: 75,
    latencyMs: 400,
    throughputTps: 150,
    bestFor: 'Legacy. Migrate to GPT-4.1 mini for better quality + 1M context at similar price.',
    hiddenCosts: ['Same price as GPT-4.1 nano but lower quality', '128K context vs 1M on GPT-4.1 series'],
    notes: 'SUPERSEDED by GPT-4.1 mini. Slightly more expensive but much better. Migrate now.',
  },

  // ============ ANTHROPIC ============
  {
    id: 'claude-sonnet-4',
    provider: 'Anthropic',
    model: 'Claude Sonnet 4',
    contextWindow: 200000,
    inputPricePerM: 3,
    outputPricePerM: 15,
    cachedInputPricePerM: 0.3,
    batchInputPricePerM: 1.5,
    batchOutputPricePerM: 7.5,
    visionPricePerM: 3,
    freeTier: null,
    rateLimitRpm: 1000,
    rateLimitTpm: 400000,
    capabilities: ['text', 'vision', 'function-calling', 'json-mode', 'extended-thinking'],
    qualityTier: 'frontier',
    qualityScore: 94,
    latencyMs: 1000,
    throughputTps: 80,
    bestFor: 'Best coding + long document analysis. 200K context. Prompt caching is 90% cheaper. Extended thinking mode.',
    hiddenCosts: ['Extended thinking tokens billed as output', 'Batch API requires 24h turnaround', 'Prompt caching has 5-minute TTL (cache miss = full price)'],
    notes: 'Latest Claude. Best at coding and structured extraction. Cached input is 90% cheaper ($0.30/M vs $3/M). Extended thinking mode for complex reasoning. Batch API 50% cheaper.',
  },
  {
    id: 'claude-opus-4',
    provider: 'Anthropic',
    model: 'Claude Opus 4',
    contextWindow: 200000,
    inputPricePerM: 15,
    outputPricePerM: 75,
    cachedInputPricePerM: 1.5,
    batchInputPricePerM: 7.5,
    batchOutputPricePerM: 37.5,
    visionPricePerM: 15,
    freeTier: null,
    rateLimitRpm: 100,
    rateLimitTpm: 100000,
    capabilities: ['text', 'vision', 'function-calling', 'json-mode', 'extended-thinking'],
    qualityTier: 'frontier',
    qualityScore: 97,
    latencyMs: 2000,
    throughputTps: 40,
    bestFor: 'Most capable model available. Use for hardest problems where Sonnet 4 is not enough.',
    hiddenCosts: ['5x more expensive than Sonnet 4', 'Extended thinking tokens very expensive at $75/M output', 'Rate limited heavily (100 RPM)'],
    notes: 'Highest quality model. 5x more expensive than Sonnet 4. Use only for tasks where Sonnet 4 fails. Extended thinking mode available. Batch API 50% cheaper.',
  },
  {
    id: 'claude-haiku-3.5',
    provider: 'Anthropic',
    model: 'Claude 3.5 Haiku',
    contextWindow: 200000,
    inputPricePerM: 0.8,
    outputPricePerM: 4,
    cachedInputPricePerM: 0.08,
    batchInputPricePerM: 0.4,
    batchOutputPricePerM: 2,
    visionPricePerM: 0.8,
    freeTier: null,
    rateLimitRpm: 1000,
    rateLimitTpm: 400000,
    capabilities: ['text', 'vision', 'function-calling'],
    qualityTier: 'mid',
    qualityScore: 82,
    latencyMs: 500,
    throughputTps: 120,
    bestFor: 'Fast + affordable Claude. Same 200K context. Good for high-volume tasks needing Claude quality.',
    hiddenCosts: ['Cached input TTL is 5 minutes', 'No extended thinking mode'],
    notes: '4x cheaper than Sonnet 4 on input. Same 200K context. Cached input is 90% cheaper. Best middle ground between budget and frontier.',
  },

  // ============ GOOGLE ============
  {
    id: 'gemini-2.5-flash',
    provider: 'Google',
    model: 'Gemini 2.5 Flash',
    contextWindow: 1000000,
    inputPricePerM: 0.15,
    outputPricePerM: 0.6,
    cachedInputPricePerM: 0.0375,
    visionPricePerM: 0.15,
    audioPricePerM: 0.15,
    freeTier: 'Free: 15 RPM, 150K TPM, 1500 req/day',
    rateLimitRpm: 2000,
    rateLimitTpm: 1000000,
    capabilities: ['text', 'vision', 'audio', 'video', 'function-calling', 'json-mode'],
    qualityTier: 'high',
    qualityScore: 86,
    latencyMs: 300,
    throughputTps: 200,
    bestFor: 'Best free tier. 1M context. Multimodal (text+image+audio+video). Best for budget + multimodal.',
    hiddenCosts: ['Free tier has daily limits that reset at midnight PT', 'Video processing uses many tokens per minute', 'Cached content has 1-hour TTL'],
    notes: 'Best free tier of any provider. 1M token context. Cached input 75% cheaper. Supports video input (unique). Recommended default for cost-sensitive multimodal apps.',
  },
  {
    id: 'gemini-2.5-pro',
    provider: 'Google',
    model: 'Gemini 2.5 Pro',
    contextWindow: 2000000,
    inputPricePerM: 1.25,
    outputPricePerM: 5,
    cachedInputPricePerM: 0.3125,
    visionPricePerM: 1.25,
    audioPricePerM: 1.25,
    freeTier: 'Free: 2 RPM, limited',
    rateLimitRpm: 1000,
    rateLimitTpm: 1000000,
    capabilities: ['text', 'vision', 'audio', 'video', 'function-calling', 'json-mode'],
    qualityTier: 'frontier',
    qualityScore: 93,
    latencyMs: 800,
    throughputTps: 100,
    bestFor: 'Massive 2M context. Best for entire codebase or document corpus analysis.',
    hiddenCosts: ['2M context can cost $2.50 per single request at full context', 'Video tokens expensive at long durations', 'Free tier extremely limited'],
    notes: 'Largest context window available (2M tokens). Cached input 75% cheaper. Use when you need to process entire books, codebases, or document archives.',
  },

  // ============ GROQ ============
  {
    id: 'groq-llama-4-scout',
    provider: 'Groq',
    model: 'Llama 4 Scout (Groq)',
    contextWindow: 10000000,
    inputPricePerM: 0.11,
    outputPricePerM: 0.34,
    freeTier: 'Free: 30 RPM, 12K TPM, 14K req/day',
    rateLimitRpm: 30,
    rateLimitTpm: 12000,
    capabilities: ['text', 'vision', 'function-calling'],
    qualityTier: 'mid',
    qualityScore: 84,
    latencyMs: 80,
    throughputTps: 500,
    bestFor: 'Fastest model on the planet. 10M context. Vision support. Free tier.',
    hiddenCosts: ['Free tier TPM is low (12K)', 'Rate limited heavily on free tier', '10M context only on paid tier'],
    notes: '500+ tokens/sec. 10M context window (largest available). Vision support. OpenAI-compatible API. Free tier is generous for development.',
  },
  {
    id: 'groq-llama-4-maverick',
    provider: 'Groq',
    model: 'Llama 4 Maverick (Groq)',
    contextWindow: 1000000,
    inputPricePerM: 0.2,
    outputPricePerM: 0.6,
    freeTier: 'Free: 30 RPM, 12K TPM, 14K req/day',
    rateLimitRpm: 30,
    rateLimitTpm: 12000,
    capabilities: ['text', 'vision', 'function-calling'],
    qualityTier: 'high',
    qualityScore: 88,
    latencyMs: 100,
    throughputTps: 500,
    bestFor: 'Frontier-quality open model at budget price. 500+ tps. 1M context. Vision.',
    hiddenCosts: ['Free tier TPM is low', 'Rate limited on free tier'],
    notes: 'Higher quality than Scout. Same 500+ tps speed. 1M context. Vision support. Best open model on fastest inference. OpenAI-compatible.',
  },

  // ============ DEEPSEEK ============
  {
    id: 'deepseek-v3',
    provider: 'DeepSeek',
    model: 'DeepSeek V3',
    contextWindow: 64000,
    inputPricePerM: 0.27,
    outputPricePerM: 1.1,
    cachedInputPricePerM: 0.07,
    freeTier: 'Free tier (limited)',
    rateLimitRpm: 60,
    rateLimitTpm: 60000,
    capabilities: ['text', 'function-calling', 'json-mode'],
    qualityTier: 'high',
    qualityScore: 88,
    latencyMs: 800,
    throughputTps: 60,
    bestFor: 'Frontier quality at 10x lower cost. Cached input incredibly cheap ($0.07/M).',
    hiddenCosts: ['Chinese-hosted (data residency concerns)', 'Rate limited (60 RPM)', 'No vision support', 'API can be unreliable during peak hours'],
    notes: 'Quality rivals GPT-4.1 at 7x lower cost. Cached input is $0.07/M (cheapest available). Open weights for self-hosting. Chinese-hosted.',
  },
  {
    id: 'deepseek-r1',
    provider: 'DeepSeek',
    model: 'DeepSeek R1',
    contextWindow: 64000,
    inputPricePerM: 0.55,
    outputPricePerM: 2.19,
    cachedInputPricePerM: 0.14,
    freeTier: 'Free tier (limited)',
    rateLimitRpm: 60,
    rateLimitTpm: 60000,
    capabilities: ['text', 'reasoning', 'function-calling'],
    qualityTier: 'frontier',
    qualityScore: 93,
    latencyMs: 3000,
    throughputTps: 50,
    bestFor: 'Reasoning rivaling o3 at 18x lower cost. Open weights.',
    hiddenCosts: ['Chinese-hosted', 'Reasoning tokens billed as output', 'Rate limited (60 RPM)', 'Can be slow for complex problems'],
    notes: 'Reasoning model rivaling o3 at 18x lower cost. Open weights for self-hosting. Chinese-hosted. Best reasoning $/quality if data residency allows.',
  },

  // ============ MISTRAL ============
  {
    id: 'mistral-large-2',
    provider: 'Mistral',
    model: 'Mistral Large 2',
    contextWindow: 128000,
    inputPricePerM: 2,
    outputPricePerM: 6,
    freeTier: 'Free tier on La Plateforme',
    rateLimitRpm: 200,
    rateLimitTpm: 500000,
    capabilities: ['text', 'function-calling', 'json-mode'],
    qualityTier: 'high',
    qualityScore: 87,
    latencyMs: 600,
    throughputTps: 80,
    bestFor: 'European data residency. Strong multilingual. Good function calling.',
    hiddenCosts: ['EU hosting can have higher latency for US users', 'Less ecosystem than OpenAI/Anthropic'],
    notes: 'EU-hosted. GDPR compliant. Quality close to GPT-4.1. Good for European enterprises. Open weights available.',
  },
  {
    id: 'mistral-small-3',
    provider: 'Mistral',
    model: 'Mistral Small 3',
    contextWindow: 32000,
    inputPricePerM: 0.2,
    outputPricePerM: 0.6,
    freeTier: 'Free tier on La Plateforme',
    rateLimitRpm: 500,
    rateLimitTpm: 500000,
    capabilities: ['text', 'function-calling'],
    qualityTier: 'budget',
    qualityScore: 76,
    latencyMs: 300,
    throughputTps: 150,
    bestFor: 'Budget EU option. Good for EU compliance at low cost.',
    hiddenCosts: ['32K context is small', 'Less capable than larger models'],
    notes: '10x cheaper than Large 2. Good for high-volume EU workloads. Open weights available.',
  },

  // ============ COHERE ============
  {
    id: 'cohere-command-r-plus',
    provider: 'Cohere',
    model: 'Command R+',
    contextWindow: 128000,
    inputPricePerM: 2.5,
    outputPricePerM: 10,
    freeTier: 'Free trial credits',
    rateLimitRpm: 1000,
    rateLimitTpm: 500000,
    capabilities: ['text', 'function-calling', 'rag'],
    qualityTier: 'high',
    qualityScore: 85,
    latencyMs: 800,
    throughputTps: 60,
    bestFor: 'RAG applications. Best embeddings + reranking in one platform.',
    hiddenCosts: ['Embeddings billed separately ($0.10/M tokens)', 'Reranking billed per search ($2/1K searches)', 'Training custom models costs extra'],
    notes: 'Purpose-built for enterprise RAG. Best embeddings + reranking. If your app is search/retrieval heavy, Cohere is purpose-built for it.',
  },
  {
    id: 'cohere-command-r',
    provider: 'Cohere',
    model: 'Command R',
    contextWindow: 128000,
    inputPricePerM: 0.15,
    outputPricePerM: 0.6,
    freeTier: 'Free trial credits',
    rateLimitRpm: 1000,
    rateLimitTpm: 500000,
    capabilities: ['text', 'function-calling', 'rag'],
    qualityTier: 'mid',
    qualityScore: 78,
    latencyMs: 500,
    throughputTps: 100,
    bestFor: 'Budget RAG. Same RAG features as R+ but 17x cheaper.',
    hiddenCosts: ['Same embedding/reranking costs as R+', 'Lower quality on complex tasks'],
    notes: '17x cheaper than R+ on input. Good for high-volume RAG workloads. Same RAG infrastructure.',
  },

  // ============ AMAZON ============
  {
    id: 'amazon-nova-pro',
    provider: 'Amazon',
    model: 'Nova Pro',
    contextWindow: 300000,
    inputPricePerM: 0.8,
    outputPricePerM: 3.2,
    cachedInputPricePerM: 0.2,
    freeTier: 'Free tier on AWS',
    rateLimitRpm: 1000,
    rateLimitTpm: 500000,
    capabilities: ['text', 'vision', 'function-calling'],
    qualityTier: 'high',
    qualityScore: 84,
    latencyMs: 600,
    throughputTps: 100,
    bestFor: 'AWS-native teams. Good multimodal at reasonable price. 300K context.',
    hiddenCosts: ['AWS data egress costs ($0.09/GB)', 'Cached input only available on AWS', 'Requires AWS account setup'],
    notes: 'Amazon latest. Good if already on AWS. 300K context. Cached input 75% cheaper.',
  },
  {
    id: 'amazon-nova-lite',
    provider: 'Amazon',
    model: 'Nova Lite',
    contextWindow: 300000,
    inputPricePerM: 0.06,
    outputPricePerM: 0.24,
    cachedInputPricePerM: 0.015,
    freeTier: 'Free tier on AWS',
    rateLimitRpm: 1000,
    rateLimitTpm: 500000,
    capabilities: ['text', 'vision', 'function-calling'],
    qualityTier: 'budget',
    qualityScore: 72,
    latencyMs: 300,
    throughputTps: 200,
    bestFor: 'Ultra-cheap AWS option. Good for high-volume AWS workloads.',
    hiddenCosts: ['AWS data egress costs', 'Quality drops on complex tasks'],
    notes: 'One of the cheapest models available. Good multimodal for the price. 300K context.',
  },

  // ============ X (formerly x.ai) ============
  {
    id: 'grok-3',
    provider: 'xAI',
    model: 'Grok 3',
    contextWindow: 131072,
    inputPricePerM: 5,
    outputPricePerM: 15,
    freeTier: 'Free on X (limited)',
    rateLimitRpm: 100,
    rateLimitTpm: 100000,
    capabilities: ['text', 'vision', 'function-calling', 'web-search'],
    qualityTier: 'frontier',
    qualityScore: 90,
    latencyMs: 1000,
    throughputTps: 70,
    bestFor: 'Real-time web search built in. Best for current events + live data.',
    hiddenCosts: ['Expensive ($5/M input)', 'Web search adds latency', 'Rate limited (100 RPM)', 'Limited ecosystem'],
    notes: 'Built-in web search is unique. Good for real-time data. Expensive compared to alternatives. Best when you need live web data without building RAG.',
  },
  {
    id: 'grok-3-mini',
    provider: 'xAI',
    model: 'Grok 3 mini',
    contextWindow: 131072,
    inputPricePerM: 0.3,
    outputPricePerM: 0.5,
    freeTier: 'Free on X (limited)',
    rateLimitRpm: 100,
    rateLimitTpm: 100000,
    capabilities: ['text', 'function-calling', 'web-search'],
    qualityTier: 'mid',
    qualityScore: 80,
    latencyMs: 500,
    throughputTps: 120,
    bestFor: 'Cheaper Grok with web search. Good for real-time on a budget.',
    hiddenCosts: ['Web search adds latency', 'Rate limited', 'Limited ecosystem'],
    notes: '17x cheaper than Grok 3. Still has web search. Good for real-time data on a budget.',
  },

  // ============ REPLICATE (open models) ============
  {
    id: 'replicate-flux-pro',
    provider: 'Replicate',
    model: 'Flux Pro (image)',
    contextWindow: 0,
    inputPricePerM: 0,
    outputPricePerM: 0,
    freeTier: 'Free trial',
    rateLimitRpm: 60,
    rateLimitTpm: 0,
    capabilities: ['image-generation'],
    qualityTier: 'frontier',
    qualityScore: 95,
    latencyMs: 2000,
    throughputTps: 0,
    bestFor: 'Best open-weights image generation. Rivals Midjourney.',
    hiddenCosts: ['$0.055 per image (not per token)', 'High resolution costs more', 'Rate limited'],
    notes: 'Image generation model. Priced per image, not per token. $0.055/image. Best open-weights image model. Self-hostable.',
  },
];

// ============ COST OPTIMIZATION STRATEGIES ============
export const OPTIMIZATION_TIPS = [
  {
    title: 'Use prompt caching (biggest savings)',
    description: 'If you send the same system prompt or context repeatedly, cached input is 75-90% cheaper. Anthropic offers 90% discount ($0.30/M vs $3/M). OpenAI offers 75% ($0.50/M vs $2/M). This is the single biggest cost saver for RAG and chat apps.',
    providers: ['OpenAI', 'Anthropic', 'DeepSeek', 'Google', 'Amazon'],
    savings: '75-90%',
    effort: 'Low',
    appliesTo: 'RAG, chatbots with system prompts, any app with repeated context',
  },
  {
    title: 'Use batch API for non-real-time tasks',
    description: 'OpenAI and Anthropic offer 50% discount for batch processing. Submit up to 100K requests, get results within 24 hours. Perfect for document processing, data enrichment, bulk classification.',
    providers: ['OpenAI', 'Anthropic'],
    savings: '50%',
    effort: 'Low',
    appliesTo: 'Document processing, bulk classification, non-urgent tasks',
  },
  {
    title: 'Right-size your model (80/20 rule)',
    description: '80% of tasks do NOT need frontier models. Use GPT-4.1 nano or Gemini 2.5 Flash for classification/extraction/simple chat. Reserve GPT-4.1/Sonnet 4 for complex reasoning. Typical split: 80% budget, 15% mid, 5% frontier.',
    providers: ['All'],
    savings: '70-90%',
    effort: 'Medium',
    appliesTo: 'All production apps',
  },
  {
    title: 'Use Groq for speed-sensitive tasks',
    description: 'Groq runs Llama models at 500+ tokens/sec. If latency matters (chat, real-time, live transcription), Groq is 5-10x faster than any other provider. Same model, different infra. Free tier: 14K requests/day.',
    providers: ['Groq'],
    savings: 'N/A (speed improvement)',
    effort: 'Low',
    appliesTo: 'Chatbots, real-time apps, live transcription, any latency-sensitive workload',
  },
  {
    title: 'Cache aggressively on the client side',
    description: 'Cache common queries in Redis or your database. If a user asks the same question twice, serve from cache. Embedding-based semantic caching (cache if query is 95% similar) can hit 30-50% cache rate. Tools: Redis, GPTCache, LangChain Cache.',
    providers: ['All'],
    savings: '20-50%',
    effort: 'Medium',
    appliesTo: 'Apps with repeated queries, FAQ bots, support chatbots',
  },
  {
    title: 'Use DeepSeek for frontier quality at budget prices',
    description: 'DeepSeek V3 rivals GPT-4.1 quality at 7x lower cost. R1 rivals o3 at 18x lower cost. Cached input is $0.07/M (cheapest available). If data residency allows, this is the best $/quality ratio. Open weights for self-hosting.',
    providers: ['DeepSeek'],
    savings: '85-95%',
    effort: 'Low',
    appliesTo: 'Cost-sensitive apps where Chinese hosting is acceptable',
  },
  {
    title: 'Compress your prompts',
    description: 'Long prompts cost more. Remove unnecessary examples, use concise instructions, leverage JSON instead of natural language for system prompts. A 2000-token prompt can often be compressed to 500 tokens. Tools: LangChain PromptCompression, LLMLingua.',
    providers: ['All'],
    savings: '30-60%',
    effort: 'Medium',
    appliesTo: 'Apps with large system prompts or few-shot examples',
  },
  {
    title: 'Use free tiers for development',
    description: 'Google Gemini 2.5 Flash: 1500 req/day free. Groq: 14K req/day free. Use these for development and testing. Switch to paid for production. Save 100% during dev.',
    providers: ['Google', 'Groq'],
    savings: '100% (during dev)',
    effort: 'Low',
    appliesTo: 'Development, testing, prototyping',
  },
  {
    title: 'Route by complexity (model cascade)',
    description: 'Build a router that sends simple queries to cheap models (GPT-4.1 nano, Gemini Flash) and complex queries to expensive models (GPT-4.1, Sonnet 4). A simple classifier can route 80% of traffic to the cheap model. Tools: Portkey, LangRouter, custom classifier.',
    providers: ['All'],
    savings: '60-80%',
    effort: 'High',
    appliesTo: 'Apps with mixed query complexity (chatbots, support, Q&A)',
  },
  {
    title: 'Use open-weights models for high volume',
    description: 'If you process >100M tokens/month, self-hosting Llama 4 on Together AI or your own GPU is cheaper than any API. Break-even is around 100M tokens/month. Together AI: $0.88/M. Self-hosted on H100: ~$0.50/M.',
    providers: ['Together AI', 'self-hosted'],
    savings: '50-80% (at high volume)',
    effort: 'High',
    appliesTo: 'High-volume apps (>100M tokens/month)',
  },
  {
    title: 'Reduce output tokens (output is 4-8x more expensive)',
    description: 'Output tokens cost 4-8x more than input. A model generating 1000 output tokens costs 4-8x more than 1000 input tokens. Constrain output with structured outputs (JSON mode), max_tokens limits, and concise instructions. Every 100 output tokens you eliminate saves 4-8x what 100 input tokens cost.',
    providers: ['All'],
    savings: '20-40%',
    effort: 'Low',
    appliesTo: 'All apps, especially those generating long responses',
  },
  {
    title: 'Use Gemini for multimodal (cheapest vision + audio + video)',
    description: 'Gemini 2.5 Flash processes images, audio, AND video at $0.15/M tokens. GPT-4.1 charges $2/M for vision. DeepSeek has no vision. If you need multimodal, Gemini is 13x cheaper than OpenAI for vision input.',
    providers: ['Google'],
    savings: '85-90% (on multimodal)',
    effort: 'Low',
    appliesTo: 'Apps with image/audio/video input',
  },
  {
    title: 'Use fine-tuned small models instead of large models',
    description: 'Fine-tuning GPT-4o mini ($3/M training) on your domain data can match GPT-4.1 quality at 20x lower inference cost. Break-even: if you use >50K examples, fine-tuning pays for itself within a month.',
    providers: ['OpenAI', 'Mistral', 'Cohere'],
    savings: '80-90%',
    effort: 'High',
    appliesTo: 'Domain-specific tasks (legal, medical, finance) with >1K training examples',
  },
  {
    title: 'Switch from o3 to o3-mini or DeepSeek R1 for reasoning',
    description: 'o3 costs $10/M input + $40/M output. o3-mini costs $1.1/$4.4 (9x cheaper). DeepSeek R1 costs $0.55/$2.19 (18x cheaper). For most reasoning tasks, o3-mini matches o3 quality. Use o3 only for hardest problems.',
    providers: ['OpenAI', 'DeepSeek'],
    savings: '85-95%',
    effort: 'Low',
    appliesTo: 'Reasoning tasks (math, coding, complex logic)',
  },
  {
    title: 'Monitor and set spending limits',
    description: 'Set up billing alerts on every provider. OpenAI: hard limit in settings. Anthropic: spending alerts. Google: budget alerts in GCP. A runaway loop can cost $1000s in minutes. Set limits at 2x your expected monthly spend.',
    providers: ['All'],
    savings: 'Prevents catastrophic spending',
    effort: 'Low',
    appliesTo: 'All production apps',
  },
];

// ============ MODEL SELECTION GUIDE ============
export const MODEL_SELECTION_GUIDE = [
  {
    useCase: 'General chatbot / assistant',
    recommended: 'GPT-4.1 mini or Claude 3.5 Haiku',
    reasoning: 'Best $/quality for conversational AI. Most users cannot tell the difference from frontier models.',
    budget: '$0.40-0.80/M input',
    alternative: 'Gemini 2.5 Flash ($0.15/M, free tier available)',
  },
  {
    useCase: 'Document analysis / RAG',
    recommended: 'Claude Sonnet 4 (with prompt caching)',
    reasoning: '200K context + 90% cache discount ($0.30/M cached) = cheapest for repeated document queries. Best extraction quality.',
    budget: '$0.30/M cached input',
    alternative: 'Gemini 2.5 Pro ($1.25/M, 2M context for entire codebases)',
  },
  {
    useCase: 'Coding / code generation',
    recommended: 'Claude Sonnet 4 or GPT-4.1',
    reasoning: 'Sonnet 4 is best for multi-file edits + complex refactoring. GPT-4.1 is best for new code generation + debugging.',
    budget: '$2-3/M input',
    alternative: 'o3-mini ($1.1/M, best for debugging + complex logic)',
  },
  {
    useCase: 'High-volume classification / extraction',
    recommended: 'GPT-4.1 nano or Gemini 2.5 Flash',
    reasoning: 'Cheapest options. Gemini Flash has free tier (1500 req/day). GPT-4.1 nano has best structured outputs.',
    budget: '$0.10-0.15/M input',
    alternative: 'Groq Llama 4 Scout ($0.11/M, 500+ tps for speed)',
  },
  {
    useCase: 'Real-time / low-latency',
    recommended: 'Groq Llama 4 Scout or Maverick',
    reasoning: '500+ tokens/sec. 5-10x faster than any other provider. Same model quality.',
    budget: '$0.11-0.20/M input',
    alternative: 'Gemini 2.5 Flash ($0.15/M, 200 tps, free tier)',
  },
  {
    useCase: 'Complex reasoning / math',
    recommended: 'o3-mini or DeepSeek R1',
    reasoning: 'o3-mini is best reasoning $/quality ($1.1/M). R1 is 2x cheaper ($0.55/M) but Chinese-hosted.',
    budget: '$0.55-1.10/M input',
    alternative: 'o3 ($10/M, reserve for hardest problems only)',
  },
  {
    useCase: 'Multimodal (images, audio, video)',
    recommended: 'Gemini 2.5 Flash',
    reasoning: 'Cheapest multimodal ($0.15/M for text+image+audio+video). Free tier. GPT-4.1 is 13x more expensive for vision.',
    budget: '$0.15/M input',
    alternative: 'GPT-4.1 ($2/M vision, better quality but expensive)',
  },
  {
    useCase: 'EU data residency',
    recommended: 'Mistral Large 2 or Small 3',
    reasoning: 'Hosted in EU. GDPR compliant. Quality close to GPT-4.1. Open weights for on-prem.',
    budget: '$0.20-2.00/M input',
    alternative: 'Self-host Llama 4 on EU servers',
  },
  {
    useCase: 'Maximum context (entire codebase)',
    recommended: 'Gemini 2.5 Pro (2M tokens) or Llama 4 Scout (10M tokens)',
    reasoning: 'Gemini 2.5 Pro has 2M context. Llama 4 Scout on Groq has 10M context. Analyze entire repos or document archives.',
    budget: '$0.11-1.25/M input',
    alternative: 'Claude Sonnet 4 (200K, better quality per token)',
  },
  {
    useCase: 'Budget unconstrained (best quality)',
    recommended: 'Claude Opus 4 or o3',
    reasoning: 'Opus 4 is highest quality overall. o3 is best for reasoning. Both very expensive ($15-75/M output).',
    budget: '$10-15/M input, $40-75/M output',
    alternative: 'Claude Sonnet 4 (94% of Opus quality at 5x lower cost)',
  },
  {
    useCase: 'Image generation',
    recommended: 'Flux Pro via Replicate ($0.055/image)',
    reasoning: 'Best open-weights image model. Rivals Midjourney. Self-hostable. Cheapest per image at quality.',
    budget: '$0.055 per image',
    alternative: 'DALL-E 3 via OpenAI ($0.04-0.12/image), Midjourney ($10/mo subscription)',
  },
  {
    useCase: 'Web search + AI (real-time data)',
    recommended: 'Grok 3 (built-in search) or Perplexity API',
    reasoning: 'Grok 3 has web search built in ($5/M). Perplexity API is purpose-built for search + AI ($5/M + $5/1000 searches).',
    budget: '$0.30-5.00/M input',
    alternative: 'Build your own RAG with Tavily/Brave Search + any LLM',
  },
  {
    useCase: 'Fine-tuning / custom models',
    recommended: 'Fine-tune GPT-4o mini or Llama 4 (open weights)',
    reasoning: 'GPT-4o mini fine-tuning is $3/M training tokens. Llama 4 open weights are free to fine-tune. Both can match frontier quality on domain-specific tasks.',
    budget: '$3/M training, $0.15-0.40/M inference',
    alternative: 'Mistral fine-tuning (EU), Cohere custom models (enterprise)',
  },
  {
    useCase: 'Startup / bootstrapped (lowest cost)',
    recommended: 'Gemini 2.5 Flash (free tier) + Groq (free tier) + DeepSeek V3 (cheap)',
    reasoning: 'Gemini Flash: 1500 req/day free. Groq: 14K req/day free. DeepSeek: $0.27/M paid. Total: $0-50/month for most early-stage apps.',
    budget: '$0-50/month',
    alternative: 'Self-host Llama 4 on a $0.50/hr GPU',
  },
  {
    useCase: 'Enterprise / compliance-heavy',
    recommended: 'Azure OpenAI (GPT-4.1) or AWS Bedrock (Claude)',
    reasoning: 'Azure + AWS provide SOC 2, HIPAA, FedRAMP compliance. Same models as direct API but with enterprise governance, VPC, private endpoints.',
    budget: 'Same pricing as direct API + enterprise overhead',
    alternative: 'Mistral (EU), Cohere (enterprise RAG)',
  },
];

// ============ HIDDEN COST WARNINGS ============
export const HIDDEN_COSTS = [
  {
    cost: 'Reasoning tokens (o3, o4-mini, R1, Sonnet 4 extended thinking)',
    description: 'Reasoning models generate hidden "thinking" tokens that are billed as output tokens. A single o3 query can use 10,000+ reasoning tokens at $40/M = $0.40 per query. Always set max_tokens.',
    impact: '$0.10-0.50+ per query',
    mitigation: 'Use o3-mini instead of o3 (9x cheaper). Set max_tokens. Monitor token usage. Use non-reasoning models for simple tasks.',
  },
  {
    cost: 'Vision input token inflation',
    description: 'Images are converted to tokens. A single high-res image can use 1,000+ tokens. GPT-4.1 charges $2/M for vision. Gemini charges $0.15/M. 13x difference.',
    impact: '$0.002 per image (GPT-4.1) vs $0.00015 (Gemini)',
    mitigation: 'Use Gemini for vision. Compress images before sending. Resize to minimum needed resolution.',
  },
  {
    cost: 'Data egress (AWS, Azure)',
    description: 'If you use AWS Bedrock or Azure OpenAI, data egress from their cloud costs $0.09/GB. If your app is not on the same cloud, you pay for every API response transfer.',
    impact: '$0.09/GB egress',
    mitigation: 'Host your app on the same cloud as your LLM provider. Or use direct API (no egress).',
  },
  {
    cost: 'Rate limit overage',
    description: 'Exceeding rate limits can cause retries, which multiply your token usage. A retry loop can 10x your costs. Always implement exponential backoff.',
    impact: '2-10x cost increase during retries',
    mitigation: 'Use exponential backoff. Monitor rate limits. Upgrade tier if hitting limits regularly. Use multiple providers for load balancing.',
  },
  {
    cost: 'Prompt caching TTL (cache misses)',
    description: 'Cached input expires. Anthropic: 5 minutes. OpenAI: 256+ hours. If your cache misses, you pay full price. High-traffic apps benefit most from caching.',
    impact: 'Paying full price when cache expires',
    mitigation: 'Keep traffic high enough to hit cache. Use OpenAI (longer TTL) for low-frequency queries. Use Anthropic (90% discount) for high-frequency.',
  },
  {
    cost: 'Fine-tuning storage',
    description: 'OpenAI charges $2/GB/month for storing fine-tuned models. Anthropic charges $0.50/GB/month. A 1GB fine-tuned model costs $24/year just to store.',
    impact: '$6-24/year per model',
    mitigation: 'Delete unused fine-tuned models. Use open-weights models (free storage).',
  },
  {
    cost: 'Embedding costs (for RAG)',
    description: 'Embeddings are billed separately from chat. OpenAI: $0.13/M tokens. Cohere: $0.10/M. If you re-embed your entire knowledge base monthly, costs add up.',
    impact: '$0.10-0.13/M tokens for embeddings',
    mitigation: 'Cache embeddings in a vector DB (Pinecone, Weaviate). Only re-embed changed documents. Use free embedding models (Sentence Transformers, BGE).',
  },
  {
    cost: 'Stored completions (OpenAI)',
    description: 'OpenAI charges for storing completions data for audit/compliance. $0.06 per 1M tokens stored. Can add up at scale.',
    impact: '$0.06/M tokens stored',
    mitigation: 'Disable stored completions if not needed. Store in your own database instead.',
  },
];
