// Curated database of automation tools.
// Massively expanded v3 — organized by capability for overlap detection.
// Each entry is hand-verified for accuracy as of 2026.

export type ToolCategory =
  | 'integration'
  | 'ai'
  | 'rpa'
  | 'custom'
  | 'purpose-built';
export type Difficulty = 1 | 2 | 3 | 4 | 5;
export type TimeToValue = 'Hours' | 'Days' | 'Weeks' | 'Months';

export type UserEffort =
  | 'upload-and-go'
  | 'configure'
  | 'build-visually'
  | 'write-code';

export type ToolType = 'solution' | 'building-block';

// NEW: Capabilities — used for overlap detection and "do you already have this?" analysis
export type Capability =
  // Document processing
  | 'invoice-extraction'
  | 'receipt-extraction'
  | 'contract-extraction'
  | 'pdf-parsing'
  | 'document-classification'
  | 'ocr'
  // Sales / revenue
  | 'lead-enrichment'
  | 'lead-routing'
  | 'cold-outreach'
  | 'crm-sync'
  | 'sales-sequencing'
  | 'meeting-scheduling'
  // Customer support
  | 'ticket-triage'
  | 'chatbot'
  | 'knowledge-base'
  | 'helpdesk'
  // Workflow / integration
  | 'saas-integration'
  | 'data-routing'
  | 'event-trigger'
  | 'data-transformation'
  | 'api-orchestration'
  // Browser / data scraping
  | 'web-scraping'
  | 'browser-automation'
  | 'form-filling'
  // Data platforms
  | 'spreadsheet-db'
  | 'database'
  | 'internal-tools'
  | 'app-builder'
  // AI / LLM
  | 'text-generation'
  | 'text-classification'
  | 'summarization'
  | 'translation'
  | 'image-generation'
  | 'transcription'
  // Marketing
  | 'email-marketing'
  | 'marketing-automation'
  | 'social-scheduling'
  | 'analytics-reporting'
  // HR
  | 'ats'
  | 'resume-screening'
  | 'onboarding'
  // Finance
  | 'expense-management'
  | 'accounts-payable'
  | 'accounts-receivable'
  | 'erp'
  // Operations
  | 'project-management'
  | 'task-automation'
  | 'scheduling'
  | 'inventory-management'
  // Communication
  | 'team-chat'
  | 'video-conferencing'
  | 'knowledge-sharing';

export interface Tool {
  id: string;
  name: string;
  category: ToolCategory;
  toolType: ToolType;
  userEffort: UserEffort;
  tagline: string;
  website: string;
  pricingUrl: string;
  getStartedUrl: string;
  startingPrice: string;
  freeTier: string | null;
  bestFor: string;
  whatYouDo: string;
  capabilities: Capability[]; // NEW
  industryFit: string[];
  difficulty: Difficulty;
  timeToValue: TimeToValue;
  logoColor: string;
  pros: string[];
  cons: string[];
  // NEW: Aliases — alternative names users might type (e.g., "GSuite", "Google Workspace")
  aliases?: string[];
}

export const TOOLS: Tool[] = [
  // ============ PURPOSE-BUILT: DOCUMENT PROCESSING ============
  {
    id: 'lido',
    name: 'Lido',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'upload-and-go',
    tagline: 'Spreadsheet that automates itself — built for finance & ops',
    website: 'https://lido.app',
    pricingUrl: 'https://lido.app/pricing',
    getStartedUrl: 'https://lido.app/signup',
    startingPrice: '$50/mo',
    freeTier: 'Free tier — 3 docs, 100 rows',
    bestFor: 'Invoice processing, report generation, data cleaning — anything you\'d do in Excel but want automated',
    whatYouDo: 'Upload your spreadsheet or PDF, link your data sources, and Lido auto-extracts, transforms, and outputs. No code, no API keys, no workflow builder — it just works like a smart spreadsheet.',
    capabilities: ['invoice-extraction', 'pdf-parsing', 'data-transformation', 'spreadsheet-db', 'data-routing'],
    industryFit: ['finance', 'retail', 'professional-services', 'logistics', 'healthcare'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#FF6B35',
    pros: ['No code or API keys needed', 'Familiar spreadsheet interface', 'Built-in PDF and email parsing', 'Outputs to email/Slack/sheets automatically'],
    cons: ['Limited to spreadsheet-shaped problems', 'Less flexible than general automation tools'],
  },
  {
    id: 'nanonets',
    name: 'Nanonets',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'upload-and-go',
    tagline: 'Document AI — pre-trained for invoices, receipts, contracts',
    website: 'https://nanonets.com',
    pricingUrl: 'https://nanonets.com/pricing/',
    getStartedUrl: 'https://nanonets.com/signup/',
    startingPrice: '$49/mo',
    freeTier: 'Free tier — 500 docs/mo',
    bestFor: 'Document extraction (invoices, receipts, POs, contracts) without building ML models',
    whatYouDo: 'Pick a pre-trained model (invoice, receipt, ID, contract, etc.), upload your documents, get structured data out. Custom fields via point-and-click UI. No ML expertise needed.',
    capabilities: ['invoice-extraction', 'receipt-extraction', 'contract-extraction', 'document-classification', 'ocr', 'pdf-parsing'],
    industryFit: ['finance', 'healthcare', 'logistics', 'retail', 'manufacturing'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#6366F1',
    pros: ['Pre-trained models for common docs', 'No ML expertise needed', 'Custom fields via UI', 'Outputs to anywhere (sheets, API, webhooks)'],
    cons: ['Limited to document tasks', 'Custom models get expensive'],
  },
  {
    id: 'docparser',
    name: 'Docparser',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'PDF/document data extraction with rule-based parsing',
    website: 'https://docparser.com',
    pricingUrl: 'https://docparser.com/pricing',
    getStartedUrl: 'https://docparser.com/signup',
    startingPrice: '$39/mo',
    freeTier: '14-day trial (no free tier)',
    bestFor: 'Recurring PDFs with consistent structure (invoices, POs, reports) where you need precise data extraction',
    whatYouDo: 'Upload a sample document, drag boxes around the fields you want extracted, save the parser. Future docs of the same type are auto-parsed. Less smart than AI but more predictable.',
    capabilities: ['invoice-extraction', 'pdf-parsing', 'ocr', 'data-routing'],
    industryFit: ['finance', 'logistics', 'manufacturing', 'healthcare'],
    difficulty: 2,
    timeToValue: 'Days',
    logoColor: '#0EA5E9',
    pros: ['More predictable than AI for structured docs', 'Visual parser builder', 'Works on any PDF', 'Strong for regulated industries'],
    cons: ['Requires consistent document structure', 'Less flexible than AI approaches'],
  },
  {
    id: 'base64-ai',
    name: 'Base64.ai',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'upload-and-go',
    tagline: 'Enterprise document AI — 900+ pre-trained document types',
    website: 'https://base64.ai',
    pricingUrl: 'https://base64.ai/pricing',
    getStartedUrl: 'https://base64.ai/contact',
    startingPrice: 'Custom (typically $500+/mo)',
    freeTier: 'Free trial — limited',
    bestFor: 'High-volume document processing across many doc types (invoices, IDs, W-2s, insurance claims, etc.)',
    whatYouDo: 'Upload documents via API or web UI — Base64 auto-detects type and extracts fields. Enterprise-grade with SOC 2, HIPAA, GDPR compliance.',
    capabilities: ['invoice-extraction', 'receipt-extraction', 'contract-extraction', 'document-classification', 'ocr', 'pdf-parsing'],
    industryFit: ['finance', 'healthcare', 'insurance', 'logistics', 'government'],
    difficulty: 2,
    timeToValue: 'Days',
    logoColor: '#000000',
    pros: ['900+ pre-trained document types', 'Enterprise compliance (SOC 2, HIPAA)', 'Auto-detects document type', 'API-first'],
    cons: ['Expensive for small volume', 'Sales-led onboarding'],
  },
  {
    id: 'docsumo',
    name: 'Docsumo',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'upload-and-go',
    tagline: 'Document AI focused on financial documents — invoices, bank statements, tax forms',
    website: 'https://docsumo.com',
    pricingUrl: 'https://docsumo.com/pricing',
    getStartedUrl: 'https://docsumo.com/signup',
    startingPrice: '$100/mo',
    freeTier: '14-day free trial',
    bestFor: 'Financial document automation — invoices, bank statements, tax forms, KYC docs',
    whatYouDo: 'Upload financial docs, Docsumo extracts structured data with 99%+ accuracy, integrates with your accounting/ERP system. Built-in human-in-the-loop review queue.',
    capabilities: ['invoice-extraction', 'receipt-extraction', 'pdf-parsing', 'ocr', 'accounts-payable'],
    industryFit: ['finance', 'banking', 'accounting', 'logistics'],
    difficulty: 2,
    timeToValue: 'Days',
    logoColor: '#7C3AED',
    pros: ['99%+ accuracy on financial docs', 'Built-in review queue', 'Pre-built ERP integrations', 'Strong compliance'],
    cons: ['Focused on financial documents', 'Higher price point'],
  },

  // ============ PURPOSE-BUILT: SALES / REVENUE ============
  {
    id: 'clay',
    name: 'Clay',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Sales/revenue automation with built-in data enrichment',
    website: 'https://clay.com',
    pricingUrl: 'https://clay.com/pricing',
    getStartedUrl: 'https://clay.com/signup',
    startingPrice: '$149/mo',
    freeTier: '14-day trial + free tier with credits',
    bestFor: 'Lead enrichment, prospecting, sales research, outbound personalization',
    whatYouDo: 'Import a list of prospects, drop in enrichment columns (company, role, tech stack, recent news), write AI prompts to personalize outreach. Clay handles all the data fetching and AI calls — no API keys to manage.',
    capabilities: ['lead-enrichment', 'lead-routing', 'crm-sync', 'cold-outreach', 'text-generation', 'data-routing'],
    industryFit: ['technology', 'professional-services', 'finance', 'retail'],
    difficulty: 2,
    timeToValue: 'Hours',
    logoColor: '#10B981',
    pros: ['75+ data providers pre-integrated', 'Built-in AI for personalization', 'No API keys to manage', 'Visual spreadsheet interface'],
    cons: ['Focused on sales/revenue use cases', 'Can get expensive at scale'],
  },
  {
    id: 'apollo',
    name: 'Apollo.io',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'All-in-one sales platform — prospecting + sequencing + CRM',
    website: 'https://apollo.io',
    pricingUrl: 'https://www.apollo.io/pricing',
    getStartedUrl: 'https://apollo.io/signup',
    startingPrice: '$59/mo',
    freeTier: 'Free tier — 60 credits/mo',
    bestFor: 'B2B outbound sales — prospecting, email sequences, call recording, CRM',
    whatYouDo: 'Search 275M+ contacts, save to lists, write email sequences, track opens/clicks. Replaces separate prospecting + sequencing + CRM tools.',
    capabilities: ['lead-enrichment', 'cold-outreach', 'sales-sequencing', 'crm-sync', 'lead-routing'],
    industryFit: ['technology', 'professional-services', 'finance', 'retail'],
    difficulty: 2,
    timeToValue: 'Days',
    logoColor: '#EE4623',
    pros: ['275M+ contact database', 'All-in-one sales platform', 'Generous free tier', 'Built-in email/sequence automation'],
    cons: ['Data quality varies by industry', 'Email deliverability can be a concern', 'Lots of features = learning curve'],
  },
  {
    id: 'outreach',
    name: 'Outreach',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Enterprise sales engagement platform',
    website: 'https://www.outreach.io',
    pricingUrl: 'https://www.outreach.io/pricing',
    getStartedUrl: 'https://www.outreach.io/request-a-demo',
    startingPrice: 'Custom (~$130/user/mo)',
    freeTier: 'No free tier — demo only',
    bestFor: 'Sales teams (10+ reps) running multi-channel outbound sequences at scale',
    whatYouDo: 'Build sequences (email + calls + LinkedIn), manage deal pipeline, coach reps with call recording + AI insights. Enterprise-grade with deep CRM sync.',
    capabilities: ['cold-outreach', 'sales-sequencing', 'crm-sync', 'lead-routing'],
    industryFit: ['technology', 'finance', 'professional-services'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#5B3FBE',
    pros: ['Best-in-class for large sales teams', 'Deep CRM sync', 'Strong coaching/insights', 'Multi-channel sequences'],
    cons: ['Expensive', 'Sales-led onboarding', 'Overkill for small teams'],
  },
  {
    id: 'lemlist',
    name: 'Lemlist',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Cold email platform with AI personalization',
    website: 'https://lemlist.com',
    pricingUrl: 'https://lemlist.com/pricing',
    getStartedUrl: 'https://lemlist.com/signup',
    startingPrice: '$59/mo',
    freeTier: '14-day trial',
    bestFor: 'Cold email campaigns with personalized AI-generated first lines',
    whatYouDo: 'Import leads, write email templates with AI-generated personalized first lines, set up multi-step sequences, track results. Multi-channel (email + LinkedIn + calls).',
    capabilities: ['cold-outreach', 'sales-sequencing', 'lead-enrichment', 'text-generation'],
    industryFit: ['technology', 'professional-services', 'agency'],
    difficulty: 2,
    timeToValue: 'Days',
    logoColor: '#FF4E00',
    pros: ['AI-personalized first lines', 'Multi-channel sequences', 'Strong deliverability features', 'Good for SMBs'],
    cons: ['Less robust than Outreach for enterprise', 'Personalization quality varies'],
  },

  // ============ PURPOSE-BUILT: CUSTOMER SUPPORT ============
  {
    id: 'intercom',
    name: 'Intercom',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'AI-first customer support + engagement platform',
    website: 'https://intercom.com',
    pricingUrl: 'https://intercom.com/pricing',
    getStartedUrl: 'https://intercom.com/signup',
    startingPrice: '$39/seat/mo',
    freeTier: '14-day trial',
    bestFor: 'SaaS companies wanting AI chatbot + helpdesk + proactive outreach in one platform',
    whatYouDo: 'Configure Fin AI chatbot to deflect common questions, route complex ones to agents, build help center articles, send proactive messages. Replaces separate chatbot + helpdesk + knowledge base tools.',
    capabilities: ['ticket-triage', 'chatbot', 'knowledge-base', 'helpdesk', 'text-classification'],
    industryFit: ['technology', 'retail', 'media'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#1F8DED',
    pros: ['AI chatbot (Fin) genuinely deflects tickets', 'All-in-one platform', 'Strong for SaaS', 'Proactive engagement features'],
    cons: ['Expensive at scale', 'Steeper learning curve', 'Best for tech-savvy teams'],
  },
  {
    id: 'zendesk-ai',
    name: 'Zendesk (with AI)',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Helpdesk with built-in AI for triage + suggestions',
    website: 'https://zendesk.com',
    pricingUrl: 'https://zendesk.com/pricing',
    getStartedUrl: 'https://zendesk.com/register',
    startingPrice: '$55/agent/mo',
    freeTier: '30-day trial',
    bestFor: 'Established support teams wanting AI triage + agent assist on top of robust helpdesk',
    whatYouDo: 'Configure AI to auto-classify tickets, suggest responses, detect sentiment. Agents get AI-assisted macros and knowledge suggestions. Strong reporting and SLA management.',
    capabilities: ['ticket-triage', 'chatbot', 'knowledge-base', 'helpdesk', 'text-classification'],
    industryFit: ['retail', 'finance', 'healthcare', 'logistics', 'technology'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#03363D',
    pros: ['Industry-standard helpdesk', 'Strong AI features (Answer Bot, Agent Copilot)', 'Excellent reporting', 'Huge integration ecosystem'],
    cons: ['Expensive', 'Complex setup', 'Per-agent pricing adds up'],
    aliases: ['zendesk'],
  },
  {
    id: 'front',
    name: 'Front',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Shared inbox for teams — email + chat + SMS in one place',
    website: 'https://front.com',
    pricingUrl: 'https://front.com/pricing',
    getStartedUrl: 'https://front.com/signup',
    startingPrice: '$19/seat/mo',
    freeTier: '14-day trial',
    bestFor: 'Operations teams handling shared inboxes (support@, billing@, ops@) with collaboration needs',
    whatYouDo: 'Connect email accounts, assign emails to team members, collaborate internally on responses, automate routing with rules. Less feature-rich than Zendesk for support but better for ops teams.',
    capabilities: ['ticket-triage', 'helpdesk', 'data-routing', 'event-trigger'],
    industryFit: ['finance', 'logistics', 'professional-services', 'retail'],
    difficulty: 2,
    timeToValue: 'Days',
    logoColor: '#FF4E00',
    pros: ['Great for ops teams', 'Shared inbox collaboration', 'Strong automation rules', 'Cheaper than Zendesk'],
    cons: ['Not a full helpdesk', 'Limited AI features', 'Best for email-first teams'],
  },

  // ============ INTEGRATION PLATFORMS ============
  {
    id: 'make',
    name: 'Make',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Visual automation builder for SaaS-to-SaaS workflows',
    website: 'https://www.make.com',
    pricingUrl: 'https://www.make.com/en/pricing',
    getStartedUrl: 'https://www.make.com/en/register',
    startingPrice: '$9/mo',
    freeTier: 'Free forever — 1,000 ops/mo, 2 active scenarios',
    bestFor: 'Connecting 5+ SaaS tools with conditional logic and data transformations. Has built-in OpenAI/Claude modules — no API key needed.',
    whatYouDo: 'Drag-drop a visual workflow: pick a trigger (e.g., new email), add steps (filter, transform, send to another app). Make handles all the API calls. You configure, not code.',
    capabilities: ['saas-integration', 'data-routing', 'data-transformation', 'event-trigger', 'api-orchestration', 'text-generation'],
    industryFit: ['technology', 'retail', 'professional-services', 'media'],
    difficulty: 2,
    timeToValue: 'Hours',
    logoColor: '#6D00CC',
    pros: ['Visual flow builder is intuitive', 'Built-in AI modules (no API key)', 'Cheaper than Zapier at scale', 'Powerful data transformation'],
    cons: ['Learning curve for complex scenarios', 'Smaller app ecosystem than Zapier'],
    aliases: ['integromat'],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Largest integration ecosystem — connects 7,000+ apps',
    website: 'https://zapier.com',
    pricingUrl: 'https://zapier.com/pricing',
    getStartedUrl: 'https://zapier.com/sign-up',
    startingPrice: '$20/mo',
    freeTier: 'Free forever — 100 tasks/mo, 5 single-step zaps',
    bestFor: 'Quick wins between popular SaaS tools with minimal setup. Has built-in OpenAI/Claude/Formatter steps.',
    whatYouDo: 'Pick a trigger app, pick an action app, fill in the mapping. Zapier handles everything. For AI tasks, use Zapier\'s built-in AI steps (no API key needed).',
    capabilities: ['saas-integration', 'data-routing', 'event-trigger', 'data-transformation', 'text-generation'],
    industryFit: ['technology', 'retail', 'professional-services', 'education', 'nonprofit'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#FF4F00',
    pros: ['Largest app ecosystem', 'Easiest to learn', 'Built-in AI steps (no API key)', 'Great templates library'],
    cons: ['Expensive at scale', 'Limited data transformation on lower tiers', 'Single-step zaps only on free tier'],
  },
  {
    id: 'n8n',
    name: 'n8n',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Open-source workflow automation — self-host or cloud',
    website: 'https://n8n.io',
    pricingUrl: 'https://n8n.io/pricing/',
    getStartedUrl: 'https://n8n.io/cloud/',
    startingPrice: '$20/mo (cloud) or free (self-hosted)',
    freeTier: 'Free self-hosted — unlimited workflows',
    bestFor: 'Technical teams who want control and lower costs at scale',
    whatYouDo: 'Self-host or use cloud. Build visual workflows with code nodes for custom logic. Cheaper than Make/Zapier at scale.',
    capabilities: ['saas-integration', 'data-routing', 'event-trigger', 'data-transformation', 'api-orchestration'],
    industryFit: ['technology', 'finance', 'healthcare'],
    difficulty: 3,
    timeToValue: 'Days',
    logoColor: '#FF6D5A',
    pros: ['Self-hostable for data privacy', 'Code nodes for custom logic', 'Cheaper at scale'],
    cons: ['Requires technical knowledge', 'Smaller template library'],
  },
  {
    id: 'workato',
    name: 'Workato',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Enterprise iPaaS with intelligent automation recipes',
    website: 'https://www.workato.com',
    pricingUrl: 'https://www.workato.com/pricing',
    getStartedUrl: 'https://www.workato.com/trial',
    startingPrice: 'Custom (~$10K+/yr)',
    freeTier: '30-day trial',
    bestFor: 'Enterprise teams needing governance, security, and complex workflows',
    whatYouDo: 'Use pre-built "recipes" for common integrations, customize as needed. Enterprise governance, audit logs, role-based access.',
    capabilities: ['saas-integration', 'data-routing', 'data-transformation', 'api-orchestration', 'event-trigger'],
    industryFit: ['finance', 'healthcare', 'manufacturing', 'enterprise'],
    difficulty: 4,
    timeToValue: 'Weeks',
    logoColor: '#2D7DFF',
    pros: ['Enterprise-grade security', 'Recipe intelligence', 'Great for complex ops'],
    cons: ['Expensive', 'Sales-led onboarding', 'Overkill for small teams'],
  },
  {
    id: 'tray-io',
    name: 'Tray.io',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Low-code automation for technical teams',
    website: 'https://tray.io',
    pricingUrl: 'https://tray.io/pricing',
    getStartedUrl: 'https://tray.io/free-trial',
    startingPrice: 'Custom (~$10K+/yr)',
    freeTier: '14-day trial',
    bestFor: 'Technical ops teams who need more power than Make/Zapier but less code than Pipedream',
    whatYouDo: 'Build visual workflows with conditional logic, loops, and custom JS. Strong for complex data transformations at scale.',
    capabilities: ['saas-integration', 'data-routing', 'data-transformation', 'api-orchestration'],
    industryFit: ['technology', 'finance', 'healthcare'],
    difficulty: 4,
    timeToValue: 'Weeks',
    logoColor: '#FF6B6B',
    pros: ['Powerful for complex workflows', 'Better than Make for enterprise', 'Strong data transformation'],
    cons: ['Expensive', 'Steeper learning curve', 'Sales-led onboarding'],
  },
  {
    id: 'pipedream',
    name: 'Pipedream',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'write-code',
    tagline: 'Developer-focused automation with code when you need it',
    website: 'https://pipedream.com',
    pricingUrl: 'https://pipedream.com/pricing',
    getStartedUrl: 'https://pipedream.com/signup',
    startingPrice: '$19/mo',
    freeTier: 'Free tier — 100 credits/mo',
    bestFor: 'Developers who want API integrations with code-level control',
    whatYouDo: 'Write code (Node.js, Python) to handle API calls, with built-in auth management for 2,000+ APIs.',
    capabilities: ['saas-integration', 'api-orchestration', 'data-transformation', 'event-trigger'],
    industryFit: ['technology'],
    difficulty: 4,
    timeToValue: 'Days',
    logoColor: '#38BDF8',
    pros: ['Full code access', 'Great API support', 'Cheap for developers'],
    cons: ['Not for non-technical users', 'Smaller template library'],
  },
  {
    id: 'boomi',
    name: 'Boomi',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Enterprise iPaaS — cloud-native integration platform',
    website: 'https://boomi.com',
    pricingUrl: 'https://boomi.com/pricing',
    getStartedUrl: 'https://boomi.com/free-trial',
    startingPrice: 'Custom (~$12K+/yr)',
    freeTier: '30-day trial',
    bestFor: 'Large enterprises with complex integration needs across many systems',
    whatYouDo: 'Build integration processes visually, deploy to Boomi\'s cloud, monitor with built-in observability.',
    capabilities: ['saas-integration', 'data-routing', 'data-transformation', 'api-orchestration'],
    industryFit: ['finance', 'healthcare', 'manufacturing', 'government'],
    difficulty: 4,
    timeToValue: 'Weeks',
    logoColor: '#FF6B00',
    pros: ['Enterprise-grade', 'Strong for hybrid cloud/on-prem', 'Good Master Data Management'],
    cons: ['Expensive', 'Steeper learning curve', 'Sales-led onboarding'],
  },
  {
    id: 'celigo',
    name: 'Celigo',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'iPaaS with pre-built integration apps for ERP/CRM',
    website: 'https://www.celigo.com',
    pricingUrl: 'https://www.celigo.com/pricing/',
    getStartedUrl: 'https://www.celigo.com/free-trial/',
    startingPrice: '$250/mo+',
    freeTier: '30-day trial',
    bestFor: 'Mid-market teams with NetSuite, Salesforce, or HubSpot at the center',
    whatYouDo: 'Use pre-built integration apps for NetSuite/Salesforce/HubSpot, customize flows visually. Strong for ERP-centric companies.',
    capabilities: ['saas-integration', 'data-routing', 'api-orchestration', 'erp'],
    industryFit: ['retail', 'manufacturing', 'finance', 'logistics'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#00A3E0',
    pros: ['Excellent NetSuite connector', 'Pre-built integration apps', 'Mid-market focused'],
    cons: ['Expensive for small teams', 'Best when you have a flagship system'],
  },

  // ============ BROWSER AUTOMATION ============
  {
    id: 'bardeen',
    name: 'Bardeen',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Browser extension that automates any web task',
    website: 'https://bardeen.ai',
    pricingUrl: 'https://bardeen.ai/pricing',
    getStartedUrl: 'https://bardeen.ai/download',
    startingPrice: '$15/mo',
    freeTier: 'Free tier — 20 credits/mo',
    bestFor: 'Web scraping, data entry, browser-based workflows (LinkedIn, Notion, Google Sheets, etc.)',
    whatYouDo: 'Install the Chrome extension, click "record", do the task once manually. Bardeen learns and repeats it. Has hundreds of pre-built automations for popular sites.',
    capabilities: ['web-scraping', 'browser-automation', 'form-filling', 'data-routing'],
    industryFit: ['technology', 'retail', 'media', 'professional-services'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#7C3AED',
    pros: ['No-code browser automation', 'Hundreds of pre-built workflows', 'Records your actions to learn', 'Free tier is genuinely usable'],
    cons: ['Browser-only — can\'t run server-side', 'Limited to what you can do in a browser'],
  },
  {
    id: 'browse-ai',
    name: 'Browse AI',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Web scraping without code — extract data from any website',
    website: 'https://browse.ai',
    pricingUrl: 'https://browse.ai/pricing',
    getStartedUrl: 'https://browse.ai/signup',
    startingPrice: '$39/mo',
    freeTier: 'Free tier — 50 credits/mo',
    bestFor: 'Monitoring competitors, scraping listings, extracting structured data from any website',
    whatYouDo: 'Install the Chrome extension, navigate to a website, click on the data you want extracted. Browse AI turns your clicks into a scraper that runs on schedule. No code.',
    capabilities: ['web-scraping', 'browser-automation', 'data-routing'],
    industryFit: ['retail', 'media', 'technology', 'professional-services'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#10B981',
    pros: ['Point-and-click scraper builder', 'Monitors websites on schedule', 'Handles pagination and login', 'Pre-built robots for popular sites'],
    cons: ['Limited to public web data', 'Can break when sites change layout'],
  },
  {
    id: 'axiom',
    name: 'Axiom.ai',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Browser automation — no code, just record and replay',
    website: 'https://axiom.ai',
    pricingUrl: 'https://axiom.ai/pricing',
    getStartedUrl: 'https://axiom.ai/signup',
    startingPrice: '$15/mo',
    freeTier: 'Free tier — 2 hours runtime/mo',
    bestFor: 'Browser-based data entry, form filling, repetitive web tasks',
    whatYouDo: 'Install Chrome extension, click "record", perform the task in your browser. Axiom saves the steps and can replay them on schedule or via webhook. No code.',
    capabilities: ['browser-automation', 'form-filling', 'web-scraping'],
    industryFit: ['technology', 'retail', 'professional-services', 'media'],
    difficulty: 2,
    timeToValue: 'Hours',
    logoColor: '#F59E0B',
    pros: ['Records browser actions visually', 'Runs in cloud on schedule', 'Handles complex multi-step flows', 'Generous free tier'],
    cons: ['Browser-only', 'Brittle to UI changes on target sites'],
  },

  // ============ AI BUILDING BLOCKS ============
  {
    id: 'claude-api',
    name: 'Claude API (Anthropic)',
    category: 'ai',
    toolType: 'building-block',
    userEffort: 'write-code',
    tagline: 'Best-in-class for long documents and structured extraction — building block only',
    website: 'https://anthropic.com',
    pricingUrl: 'https://www.anthropic.com/pricing',
    getStartedUrl: 'https://console.anthropic.com',
    startingPrice: '$3/M input, $15/M output (Sonnet)',
    freeTier: '$5 free credits on signup',
    bestFor: 'When you need custom AI logic that purpose-built tools can\'t handle. PREFER using Claude via Make.com or Zapier\'s built-in modules instead of direct API.',
    whatYouDo: 'Write code to call the API, handle errors, manage rate limits. For non-technical users: use Make.com or Zapier\'s Claude modules instead — same model, no code.',
    capabilities: ['text-generation', 'text-classification', 'summarization', 'translation', 'document-classification'],
    industryFit: ['finance', 'healthcare', 'professional-services', 'legal'],
    difficulty: 4,
    timeToValue: 'Days',
    logoColor: '#D97757',
    pros: ['200K context window', 'Best at structured extraction', 'Strong reasoning'],
    cons: ['Requires developer integration', 'No visual builder', 'USE VIA MAKE/ZAPIER unless you have a dev team'],
  },
  {
    id: 'openai-api',
    name: 'OpenAI API',
    category: 'ai',
    toolType: 'building-block',
    userEffort: 'write-code',
    tagline: 'GPT-4o + Whisper + DALL-E — building block only',
    website: 'https://openai.com',
    pricingUrl: 'https://openai.com/api/pricing/',
    getStartedUrl: 'https://platform.openai.com/signup',
    startingPrice: '$5/M input (GPT-4o-mini), $15/M (GPT-4o)',
    freeTier: 'No free tier — pay-as-you-go',
    bestFor: 'When you need custom AI logic that purpose-built tools can\'t handle. PREFER using GPT-4o via Make.com or Zapier\'s built-in modules instead of direct API.',
    whatYouDo: 'Write code to call the API. For non-technical users: use Make.com or Zapier\'s OpenAI modules instead — same model, no code.',
    capabilities: ['text-generation', 'text-classification', 'summarization', 'translation', 'image-generation', 'transcription'],
    industryFit: ['technology', 'retail', 'media', 'education'],
    difficulty: 4,
    timeToValue: 'Days',
    logoColor: '#10A37F',
    pros: ['Most mature ecosystem', 'Multimodal support', 'Best docs/tutorials'],
    cons: ['Requires dev integration', 'USE VIA MAKE/ZAPIER unless you have a dev team'],
  },
  {
    id: 'gemini-api',
    name: 'Google Gemini API',
    category: 'ai',
    toolType: 'building-block',
    userEffort: 'write-code',
    tagline: 'Generous free tier, multimodal, native Google integrations',
    website: 'https://ai.google.dev',
    pricingUrl: 'https://ai.google.dev/pricing',
    getStartedUrl: 'https://aistudio.google.com/app/apikey',
    startingPrice: 'Free tier → $1.25/M input (1.5 Pro)',
    freeTier: 'Free — 15 req/min on Flash, 2 req/min on Pro',
    bestFor: 'Cost-sensitive projects, multimodal tasks, Google Workspace automation',
    whatYouDo: 'Write code to call the API. Best for projects already on Google Cloud or needing multimodal (text + image + video).',
    capabilities: ['text-generation', 'text-classification', 'summarization', 'translation', 'image-generation'],
    industryFit: ['technology', 'education', 'media'],
    difficulty: 4,
    timeToValue: 'Days',
    logoColor: '#4285F4',
    pros: ['Generous free tier', 'Multimodal (text + image + video)', 'Integrates with Google Cloud'],
    cons: ['Smaller ecosystem than OpenAI', 'Less predictable quality'],
  },

  // ============ RPA ============
  {
    id: 'power-automate',
    name: 'Microsoft Power Automate',
    category: 'rpa',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Microsoft RPA + workflow automation, native to M365',
    website: 'https://powerautomate.microsoft.com',
    pricingUrl: 'https://powerautomate.microsoft.com/pricing/',
    getStartedUrl: 'https://powerautomate.microsoft.com/en-us/landing/trial/',
    startingPrice: '$15/user/mo',
    freeTier: '90-day trial',
    bestFor: 'Microsoft-centric organizations with legacy systems',
    whatYouDo: 'Build visual workflows (cloud flows) or record desktop automations (RPA). Native M365 integration. AI Builder for forms processing.',
    capabilities: ['saas-integration', 'browser-automation', 'form-filling', 'data-routing', 'event-trigger', 'ocr'],
    industryFit: ['finance', 'healthcare', 'government', 'manufacturing'],
    difficulty: 3,
    timeToValue: 'Days',
    logoColor: '#0078D4',
    pros: ['Native M365 integration', 'Includes desktop RPA + AI Builder', 'Familiar to MS shops'],
    cons: ['Licensing complex', 'Limited outside Microsoft ecosystem'],
    aliases: ['power automate', 'microsoft flow'],
  },
  {
    id: 'uipath',
    name: 'UiPath',
    category: 'rpa',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Enterprise RPA platform with attended and unattended bots',
    website: 'https://www.uipath.com',
    pricingUrl: 'https://www.uipath.com/pricing',
    getStartedUrl: 'https://www.uipath.com/platform-trial',
    startingPrice: 'Custom (~$3-5K/bot/yr)',
    freeTier: 'Community Plan — free for individuals',
    bestFor: 'Legacy system automation, regulated industries, large-scale RPA programs',
    whatYouDo: 'Build visual workflows in UiPath Studio, deploy bots to Orchestrator. Best for automating legacy desktop apps without APIs.',
    capabilities: ['browser-automation', 'form-filling', 'data-routing', 'ocr', 'data-transformation'],
    industryFit: ['finance', 'healthcare', 'manufacturing', 'government'],
    difficulty: 4,
    timeToValue: 'Weeks',
    logoColor: '#FA4616',
    pros: ['Most mature RPA platform', 'Strong for legacy systems', 'Excellent orchestration'],
    cons: ['Expensive at scale', 'Maintenance overhead', 'Brittle to UI changes'],
  },

  // ============ CUSTOM / APP BUILDERS ============
  {
    id: 'retool',
    name: 'Retool',
    category: 'custom',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Build internal tools fast with drag-drop + SQL',
    website: 'https://retool.com',
    pricingUrl: 'https://retool.com/pricing',
    getStartedUrl: 'https://retool.com/signup/',
    startingPrice: '$10/user/mo',
    freeTier: 'Free — up to 5 users, unlimited apps',
    bestFor: 'Internal admin tools, dashboards, ops workflows',
    whatYouDo: 'Drag-drop UI components, write SQL/JS for logic, connect to any DB/API. Build internal tools 10x faster than custom dev.',
    capabilities: ['internal-tools', 'database', 'api-orchestration', 'data-transformation'],
    industryFit: ['technology', 'finance', 'retail', 'logistics'],
    difficulty: 3,
    timeToValue: 'Days',
    logoColor: '#3D3D3D',
    pros: ['Fast to build internal tools', 'Connects to any DB/API', 'Strong for ops teams'],
    cons: ['Not for external users', 'Per-user pricing adds up'],
  },
  {
    id: 'bubble',
    name: 'Bubble',
    category: 'custom',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'No-code platform for full web applications',
    website: 'https://bubble.io',
    pricingUrl: 'https://bubble.io/pricing',
    getStartedUrl: 'https://bubble.io/register',
    startingPrice: '$32/mo',
    freeTier: 'Free tier — limited to test app',
    bestFor: 'Non-technical founders building production web apps',
    whatYouDo: 'Build full web apps visually — UI, database, logic, workflows. Best for MVPs and SaaS products without code.',
    capabilities: ['app-builder', 'database', 'api-orchestration', 'data-routing'],
    industryFit: ['technology', 'retail', 'media', 'nonprofit'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#000000',
    pros: ['Build full apps without code', 'Strong community/templates', 'Reasonable pricing'],
    cons: ['Performance at scale', 'Learning curve is real', 'Lock-in risk'],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: 'custom',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Spreadsheet-database hybrid with automations and extensions',
    website: 'https://airtable.com',
    pricingUrl: 'https://airtable.com/pricing',
    getStartedUrl: 'https://airtable.com/signup',
    startingPrice: '$20/user/mo',
    freeTier: 'Free — 1K records per base',
    bestFor: 'Operations teams tracking workflows in a spreadsheet-like UI',
    whatYouDo: 'Build databases in a spreadsheet UI, add automations (trigger → action), use extensions for advanced features. Great for ops teams.',
    capabilities: ['spreadsheet-db', 'database', 'data-routing', 'event-trigger', 'project-management'],
    industryFit: ['retail', 'media', 'education', 'nonprofit', 'professional-services'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#FCB400',
    pros: ['Easy to adopt', 'Built-in automations', 'Excellent for ops tracking'],
    cons: ['Limited at scale', 'Per-user pricing', 'Not for transactional apps'],
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'custom',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'All-in-one workspace — docs, databases, automations',
    website: 'https://notion.so',
    pricingUrl: 'https://notion.so/pricing',
    getStartedUrl: 'https://notion.so/signup',
    startingPrice: '$10/user/mo',
    freeTier: 'Free for individuals',
    bestFor: 'Teams wanting docs + lightweight databases + basic automations in one tool',
    whatYouDo: 'Build docs, databases, and wikis. Add simple automations (database triggers → actions). Not as powerful as dedicated tools but very flexible.',
    capabilities: ['spreadsheet-db', 'knowledge-sharing', 'project-management', 'data-routing'],
    industryFit: ['technology', 'media', 'education', 'nonprofit', 'professional-services'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#000000',
    pros: ['Extremely flexible', 'Great for docs + databases', 'Strong team adoption', 'Free for individuals'],
    cons: ['Limited automation power', 'Not for transactional apps', 'Can get messy at scale'],
  },
  {
    id: 'coda',
    name: 'Coda',
    category: 'custom',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Docs that act like apps — formulas, automations, integrations',
    website: 'https://coda.io',
    pricingUrl: 'https://coda.io/pricing',
    getStartedUrl: 'https://coda.io/signup',
    startingPrice: '$16/user/mo (Maker)',
    freeTier: 'Free for individuals',
    bestFor: 'Teams wanting more powerful docs than Notion — formulas, automations, packs',
    whatYouDo: 'Build docs with embedded tables, formulas, automations, and "packs" (integrations). More powerful than Notion for ops workflows.',
    capabilities: ['spreadsheet-db', 'knowledge-sharing', 'data-routing', 'event-trigger', 'api-orchestration'],
    industryFit: ['technology', 'media', 'professional-services', 'nonprofit'],
    difficulty: 3,
    timeToValue: 'Days',
    logoColor: '#7C3AED',
    pros: ['More powerful than Notion', 'Strong formula language', 'Good integration packs'],
    cons: ['Steeper learning curve', 'Smaller community than Notion', 'Per-maker pricing'],
  },
  {
    id: 'smartsheet',
    name: 'Smartsheet',
    category: 'custom',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Enterprise spreadsheet + project management platform',
    website: 'https://smartsheet.com',
    pricingUrl: 'https://smartsheet.com/pricing',
    getStartedUrl: 'https://smartsheet.com/signup',
    startingPrice: '$14/user/mo',
    freeTier: '30-day trial',
    bestFor: 'Enterprise teams needing spreadsheet + project management with governance',
    whatYouDo: 'Build sheets with formulas, automation rules, reports, and dashboards. Strong for regulated industries needing audit trails.',
    capabilities: ['spreadsheet-db', 'project-management', 'data-routing', 'event-trigger'],
    industryFit: ['finance', 'healthcare', 'government', 'manufacturing'],
    difficulty: 2,
    timeToValue: 'Days',
    logoColor: '#0B6AB3',
    pros: ['Enterprise-grade', 'Strong governance/audit', 'Familiar spreadsheet UI', 'Good automations'],
    cons: ['Dated UI', 'Expensive at scale', 'Per-user pricing'],
  },

  // ============ FINANCE / ACCOUNTING ============
  {
    id: 'ramp',
    name: 'Ramp',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'upload-and-go',
    tagline: 'Corporate cards + expense automation + AP',
    website: 'https://ramp.com',
    pricingUrl: 'https://ramp.com/pricing',
    getStartedUrl: 'https://ramp.com/signup',
    startingPrice: 'Free (standard plan)',
    freeTier: 'Free — standard plan',
    bestFor: 'Companies wanting to automate expense management + corporate cards + AP in one platform',
    whatYouDo: 'Issue corporate cards, automate receipt collection and expense categorization, manage AP. Built-in AI extracts receipt data automatically.',
    capabilities: ['expense-management', 'accounts-payable', 'ocr', 'receipt-extraction', 'data-routing'],
    industryFit: ['technology', 'finance', 'professional-services', 'retail'],
    difficulty: 1,
    timeToValue: 'Days',
    logoColor: '#1C1C1C',
    pros: ['Free standard plan', 'AI-powered receipt extraction', 'Cards + expenses + AP in one', 'Strong savings insights'],
    cons: ['US-focused', 'Requires switching corporate cards'],
  },
  {
    id: 'brex',
    name: 'Brex',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'upload-and-go',
    tagline: 'Corporate cards + expenses + banking for startups',
    website: 'https://brex.com',
    pricingUrl: 'https://brex.com/pricing',
    getStartedUrl: 'https://brex.com/signup',
    startingPrice: 'Free (basic) → $99/mo (Pro)',
    freeTier: 'Free basic plan',
    bestFor: 'Startups wanting corporate cards, expenses, and banking in one platform',
    whatYouDo: 'Issue cards, automate expense reports, manage spend limits. Built-in AI for receipt matching and categorization.',
    capabilities: ['expense-management', 'receipt-extraction', 'ocr'],
    industryFit: ['technology', 'professional-services'],
    difficulty: 1,
    timeToValue: 'Days',
    logoColor: '#FF6B00',
    pros: ['Free basic plan', 'AI receipt matching', 'Strong for startups', 'Integrated banking'],
    cons: ['Best for US startups', 'Limited international support'],
  },
  {
    id: 'bill-com',
    name: 'Bill.com',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'AP + AR automation for SMBs',
    website: 'https://bill.com',
    pricingUrl: 'https://bill.com/pricing',
    getStartedUrl: 'https://bill.com/signup',
    startingPrice: '$45/user/mo',
    freeTier: '30-day trial',
    bestFor: 'Small/mid businesses wanting to automate accounts payable and receivable',
    whatYouDo: 'Set up vendor payment workflows, automate invoice approval, sync with accounting software. Built-in OCR for invoice data extraction.',
    capabilities: ['accounts-payable', 'accounts-receivable', 'invoice-extraction', 'ocr', 'data-routing'],
    industryFit: ['finance', 'professional-services', 'retail', 'logistics'],
    difficulty: 2,
    timeToValue: 'Weeks',
    logoColor: '#1B49C6',
    pros: ['Purpose-built for AP/AR', 'Strong accounting integrations', 'Built-in OCR', 'Audit-friendly'],
    cons: ['Per-user pricing', 'Dated UI', 'Best for established businesses'],
  },
  {
    id: 'expensify',
    name: 'Expensify',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'upload-and-go',
    tagline: 'Expense reports + receipts + corporate cards',
    website: 'https://expensify.com',
    pricingUrl: 'https://expensify.com/pricing',
    getStartedUrl: 'https://expensify.com/signup',
    startingPrice: '$5/user/mo (Control plan)',
    freeTier: 'Free for individuals (basic)',
    bestFor: 'Teams wanting simple expense report automation with receipt scanning',
    whatYouDo: 'Snap photos of receipts, Expensify auto-extracts data, generates reports, syncs with accounting. Strong mobile app.',
    capabilities: ['expense-management', 'receipt-extraction', 'ocr'],
    industryFit: ['professional-services', 'technology', 'finance', 'retail'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#00A82D',
    pros: ['Easy receipt scanning', 'Strong mobile app', 'Good accounting integrations', 'Reasonable pricing'],
    cons: ['Limited AP capabilities', 'Less modern than Ramp/Brex', 'Per-user pricing'],
  },

  // ============ MARKETING ============
  {
    id: 'hubspot',
    name: 'HubSpot',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'All-in-one CRM + marketing + sales + service',
    website: 'https://hubspot.com',
    pricingUrl: 'https://hubspot.com/pricing',
    getStartedUrl: 'https://hubspot.com/signup',
    startingPrice: 'Free (CRM) → $890/mo (Professional)',
    freeTier: 'Free CRM forever',
    bestFor: 'Companies wanting CRM + marketing automation + sales + support in one platform',
    whatYouDo: 'Use free CRM, add paid hubs for marketing automation, sales sequences, or service. Built-in workflows, email automation, lead scoring.',
    capabilities: ['crm-sync', 'lead-routing', 'marketing-automation', 'email-marketing', 'sales-sequencing', 'helpdesk', 'data-routing'],
    industryFit: ['technology', 'retail', 'professional-services', 'media'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#FF7A59',
    pros: ['All-in-one platform', 'Free CRM is genuinely useful', 'Strong automation workflows', 'Huge integration ecosystem'],
    cons: ['Expensive at scale', 'Marketing Hub pricing jumps dramatically', 'Lots of features = complexity'],
  },
  {
    id: 'customer-io',
    name: 'Customer.io',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Behavior-driven messaging — email, push, SMS, in-app',
    website: 'https://customer.io',
    pricingUrl: 'https://customer.io/pricing',
    getStartedUrl: 'https://customer.io/signup',
    startingPrice: '$150/mo',
    freeTier: '14-day trial',
    bestFor: 'Product teams wanting behavior-triggered messaging across channels',
    whatYouDo: 'Connect your product analytics, build visual workflows (user does X → send message Y), send via email/push/SMS/in-app. Strong for SaaS lifecycle marketing.',
    capabilities: ['marketing-automation', 'email-marketing', 'event-trigger', 'data-routing'],
    industryFit: ['technology', 'media'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#FF4F00',
    pros: ['Best for behavior-triggered messaging', 'Multi-channel', 'Strong visual workflow builder', 'API-first'],
    cons: ['Focused on product companies', 'Pricing scales with messages', 'Requires dev setup'],
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Email + SMS marketing for e-commerce',
    website: 'https://klaviyo.com',
    pricingUrl: 'https://klaviyo.com/pricing',
    getStartedUrl: 'https://klaviyo.com/signup',
    startingPrice: '$45/mo (250 contacts)',
    freeTier: 'Free up to 250 contacts',
    bestFor: 'E-commerce brands wanting email + SMS marketing with strong Shopify/magento integration',
    whatYouDo: 'Sync your store data, build segments, send behavioral email/SMS campaigns, track revenue attribution. Best-in-class for e-commerce.',
    capabilities: ['marketing-automation', 'email-marketing', 'data-routing', 'analytics-reporting'],
    industryFit: ['retail', 'e-commerce', 'consumer'],
    difficulty: 2,
    timeToValue: 'Days',
    logoColor: '#1F1F1F',
    pros: ['Best for e-commerce', 'Strong Shopify integration', 'Excellent analytics', 'Generous free tier'],
    cons: ['E-commerce focused', 'Pricing scales with contacts', 'Less flexible than Customer.io for non-ecommerce'],
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Email marketing + basic automation for SMBs',
    website: 'https://mailchimp.com',
    pricingUrl: 'https://mailchimp.com/pricing',
    getStartedUrl: 'https://mailchimp.com/signup',
    startingPrice: '$13/mo (Essentials)',
    freeTier: 'Free up to 500 contacts',
    bestFor: 'Small businesses wanting simple email marketing with basic automations',
    whatYouDo: 'Build email campaigns visually, set up simple automations (welcome series, abandoned cart), track opens/clicks. Easy to learn.',
    capabilities: ['email-marketing', 'marketing-automation'],
    industryFit: ['retail', 'media', 'nonprofit', 'professional-services'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#FFE01B',
    pros: ['Easy to use', 'Generous free tier', 'Good for beginners', 'Strong templates'],
    cons: ['Limited automation power', 'Pricing jumps with contacts', 'Less sophisticated than Klaviyo/Customer.io'],
  },
  {
    id: 'mailerlite',
    name: 'MailerLite',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Affordable email marketing with automations',
    website: 'https://mailerlite.com',
    pricingUrl: 'https://mailerlite.com/pricing',
    getStartedUrl: 'https://mailerlite.com/signup',
    startingPrice: '$10/mo (Growing)',
    freeTier: 'Free up to 1,000 subscribers',
    bestFor: 'Creators and small businesses wanting affordable email + automations',
    whatYouDo: 'Build emails visually, set up automation workflows, segment subscribers, send. Generous free tier for getting started.',
    capabilities: ['email-marketing', 'marketing-automation'],
    industryFit: ['media', 'nonprofit', 'professional-services', 'education'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#00A89C',
    pros: ['Generous free tier', 'Affordable paid plans', 'Clean UI', 'Good automation features'],
    cons: ['Smaller integration ecosystem', 'Less powerful than premium tools', 'Limited A/B testing on lower tiers'],
  },

  // ============ HR / PEOPLE OPS ============
  {
    id: 'greenhouse',
    name: 'Greenhouse',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Enterprise ATS with structured hiring',
    website: 'https://greenhouse.io',
    pricingUrl: 'https://greenhouse.io/pricing',
    getStartedUrl: 'https://greenhouse.io/demo',
    startingPrice: 'Custom (~$6K+/yr)',
    freeTier: 'No free tier',
    bestFor: 'Companies doing 50+ hires/year wanting structured, data-driven recruiting',
    whatYouDo: 'Build structured interview kits, manage candidate pipeline, automate scheduling + communications. Strong reporting for hiring analytics.',
    capabilities: ['ats', 'resume-screening', 'onboarding', 'data-routing'],
    industryFit: ['technology', 'finance', 'professional-services'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#00A06B',
    pros: ['Best-in-class structured hiring', 'Strong reporting', 'Excellent integrations', 'Audit trail for compliance'],
    cons: ['Expensive', 'Sales-led onboarding', 'Overkill for small teams'],
  },
  {
    id: 'lever',
    name: 'Lever',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Modern ATS + CRM for growing companies',
    website: 'https://lever.co',
    pricingUrl: 'https://lever.co/pricing',
    getStartedUrl: 'https://lever.co/demo',
    startingPrice: 'Custom (~$3K+/yr)',
    freeTier: 'No free tier',
    bestFor: 'Tech companies wanting ATS + candidate CRM in one platform',
    whatYouDo: 'Manage candidate pipeline, nurture talent with CRM sequences, schedule interviews, collect feedback. Strong for tech hiring.',
    capabilities: ['ats', 'resume-screening', 'crm-sync', 'data-routing'],
    industryFit: ['technology', 'media', 'professional-services'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#A3E635',
    pros: ['Modern UI', 'ATS + CRM in one', 'Strong for tech hiring', 'Good automations'],
    cons: ['Expensive', 'Less structured than Greenhouse', 'Best for tech companies'],
  },
  {
    id: 'ashby',
    name: 'Ashby',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'All-in-one recruiting platform — ATS + analytics + CRM',
    website: 'https://ashbyhq.com',
    pricingUrl: 'https://ashbyhq.com/pricing',
    getStartedUrl: 'https://ashbyhq.com/signup',
    startingPrice: '$300/mo+',
    freeTier: 'No free tier',
    bestFor: 'Modern tech companies wanting unified ATS + advanced analytics',
    whatYouDo: 'Manage pipeline, build custom dashboards, automate scheduling + comms. Excellent analytics for hiring funnel optimization.',
    capabilities: ['ats', 'resume-screening', 'crm-sync', 'analytics-reporting', 'data-routing'],
    industryFit: ['technology'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#7C3AED',
    pros: ['Best analytics in ATS market', 'Modern all-in-one platform', 'Strong automations', 'Good for data-driven teams'],
    cons: ['Newer, less proven', 'Expensive', 'Best for tech companies'],
  },
  {
    id: 'bamboohr',
    name: 'BambooHR',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'HRIS for SMBs — employee data + onboarding + time off',
    website: 'https://bamboohr.com',
    pricingUrl: 'https://bamboohr.com/pricing',
    getStartedUrl: 'https://bamboohr.com/signup',
    startingPrice: 'Custom (~$6/employee/mo)',
    freeTier: 'No free tier — 7-day trial',
    bestFor: 'SMBs wanting core HRIS (employee data, onboarding, time off, basic reporting)',
    whatYouDo: 'Manage employee records, automate onboarding workflows, track time off, generate reports. Good for companies graduating from spreadsheets.',
    capabilities: ['onboarding', 'data-routing', 'event-trigger'],
    industryFit: ['technology', 'retail', 'professional-services', 'nonprofit'],
    difficulty: 2,
    timeToValue: 'Weeks',
    logoColor: '#73C41D',
    pros: ['Easy to use', 'Good for SMBs', 'Strong onboarding workflows', 'Reasonable pricing'],
    cons: ['Limited ATS features', 'Less powerful than enterprise HRIS', 'Per-employee pricing'],
  },

  // ============ COMMUNICATION / COLLABORATION ============
  {
    id: 'slack',
    name: 'Slack',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Team chat + workflow builder + app directory',
    website: 'https://slack.com',
    pricingUrl: 'https://slack.com/pricing',
    getStartedUrl: 'https://slack.com/signup',
    startingPrice: '$7/user/mo (Pro)',
    freeTier: 'Free — 90 days message history',
    bestFor: 'Team communication with built-in workflow automation and 2,600+ integrations',
    whatYouDo: 'Chat with team, build workflows in Workflow Builder (no code), integrate with 2,600+ apps. Often underutilized for automation.',
    capabilities: ['team-chat', 'data-routing', 'event-trigger', 'knowledge-sharing'],
    industryFit: ['technology', 'media', 'finance', 'professional-services'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#4A154B',
    pros: ['Industry-standard team chat', 'Workflow Builder for no-code automations', 'Huge integration ecosystem', 'Free tier is usable'],
    cons: ['Per-user pricing adds up', 'Message history limited on free tier', 'Workflows are basic'],
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Team chat + video + collaboration (native to M365)',
    website: 'https://teams.microsoft.com',
    pricingUrl: 'https://microsoft.com/microsoft-teams/group-chat-software',
    getStartedUrl: 'https://teams.microsoft.com/signup',
    startingPrice: '$4/user/mo (M365 Business Basic)',
    freeTier: 'Free tier (limited)',
    bestFor: 'Microsoft-centric organizations wanting chat + video + collaboration in one tool',
    whatYouDo: 'Chat, video calls, file collaboration. Native M365 integration. Power Automate workflows can trigger from Teams events.',
    capabilities: ['team-chat', 'video-conferencing', 'knowledge-sharing', 'event-trigger'],
    industryFit: ['finance', 'healthcare', 'government', 'manufacturing', 'enterprise'],
    difficulty: 2,
    timeToValue: 'Days',
    logoColor: '#5059C9',
    pros: ['Native M365 integration', 'Includes video + chat + files', 'Strong for enterprise', 'Power Automate integration'],
    cons: ['Less polished than Slack', 'Best with M365 subscription', 'Limited third-party integrations'],
    aliases: ['microsoft teams', 'ms teams'],
  },
  {
    id: 'zoom',
    name: 'Zoom',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Video conferencing + AI companion for transcripts/summaries',
    website: 'https://zoom.us',
    pricingUrl: 'https://zoom.us/pricing',
    getStartedUrl: 'https://zoom.us/signup',
    startingPrice: '$13/user/mo (Pro)',
    freeTier: 'Free — 40-min meetings',
    bestFor: 'Video conferencing with built-in AI transcription and meeting summaries',
    whatYouDo: 'Host video meetings, AI companion auto-generates transcripts + summaries + action items. Integrates with calendar + CRM.',
    capabilities: ['video-conferencing', 'transcription', 'summarization'],
    industryFit: ['technology', 'finance', 'professional-services', 'education', 'media'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#2D8CFF',
    pros: ['Best video quality', 'AI companion for summaries', 'Strong integrations', 'Free tier available'],
    cons: ['Per-host pricing', 'Free tier limits meeting length', 'AI features cost extra'],
  },

  // ============ ERP / DATABASE ============
  {
    id: 'netsuite',
    name: 'Oracle NetSuite',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Cloud ERP — financials + inventory + CRM + ecommerce',
    website: 'https://netsuite.com',
    pricingUrl: 'https://netsuite.com/portal/products/pricing.shtml',
    getStartedUrl: 'https://netsuite.com/portal/free-trial.shtml',
    startingPrice: '$999/mo + $99/user/mo',
    freeTier: 'No free tier',
    bestFor: 'Mid-market companies wanting unified ERP (financials, inventory, CRM, ecommerce)',
    whatYouDo: 'Configure modules (financials, inventory, CRM, ecommerce), build workflows, run reports. Powerful but complex.',
    capabilities: ['erp', 'accounts-payable', 'accounts-receivable', 'inventory-management', 'crm-sync', 'data-routing'],
    industryFit: ['retail', 'manufacturing', 'logistics', 'finance', 'professional-services'],
    difficulty: 5,
    timeToValue: 'Months',
    logoColor: '#0F6FCC',
    pros: ['Unified ERP platform', 'Scales with business', 'Strong financial management', 'Huge customization'],
    cons: ['Expensive', 'Complex implementation (months)', 'Requires admin expertise', 'Dated UI'],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'custom',
    toolType: 'solution',
    userEffort: 'write-code',
    tagline: 'Open-source Firebase alternative — Postgres + auth + storage',
    website: 'https://supabase.com',
    pricingUrl: 'https://supabase.com/pricing',
    getStartedUrl: 'https://supabase.com/dashboard',
    startingPrice: '$25/mo',
    freeTier: 'Free — 500MB DB, 50K MAU auth, 1GB storage',
    bestFor: 'Full-stack developers building production apps',
    whatYouDo: 'Get a Postgres DB + auth + storage + realtime subscriptions. Write code to build apps. Open-source, can self-host.',
    capabilities: ['database', 'api-orchestration'],
    industryFit: ['technology', 'retail', 'media', 'education'],
    difficulty: 4,
    timeToValue: 'Hours',
    logoColor: '#3ECF8E',
    pros: ['Open-source', 'Postgres with realtime', 'Generous free tier', 'Self-hostable'],
    cons: ['Requires dev knowledge', 'Self-host option has overhead'],
  },

  // ============ PROJECT MANAGEMENT ============
  {
    id: 'asana',
    name: 'Asana',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Project management with automation rules',
    website: 'https://asana.com',
    pricingUrl: 'https://asana.com/pricing',
    getStartedUrl: 'https://asana.com/signup',
    startingPrice: '$11/user/mo (Starter)',
    freeTier: 'Free up to 10 users',
    bestFor: 'Teams wanting project tracking with simple automation (status changes, assignments, notifications)',
    whatYouDo: 'Create projects + tasks, set up automation rules (when X → do Y), track progress. Strong for ops and project teams.',
    capabilities: ['project-management', 'task-automation', 'event-trigger', 'data-routing'],
    industryFit: ['technology', 'media', 'professional-services', 'nonprofit'],
    difficulty: 1,
    timeToValue: 'Days',
    logoColor: '#F06A6A',
    pros: ['Easy to use', 'Good automation rules', 'Generous free tier', 'Strong integrations'],
    cons: ['Limited at scale', 'Per-user pricing', 'Less flexible than custom tools'],
  },
  {
    id: 'monday',
    name: 'Monday.com',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Work OS — project management + CRM + custom workflows',
    website: 'https://monday.com',
    pricingUrl: 'https://monday.com/pricing',
    getStartedUrl: 'https://monday.com/signup',
    startingPrice: '$9/user/mo (Basic)',
    freeTier: 'Free up to 2 users',
    bestFor: 'Teams wanting flexible visual boards for project + CRM + ops tracking',
    whatYouDo: 'Build visual boards (tables) with custom columns, set up automations (when X → do Y), track anything. Very flexible.',
    capabilities: ['project-management', 'task-automation', 'crm-sync', 'event-trigger', 'data-routing'],
    industryFit: ['technology', 'retail', 'professional-services', 'media'],
    difficulty: 2,
    timeToValue: 'Days',
    logoColor: '#FF3D57',
    pros: ['Very flexible visual boards', 'Strong automations', 'Good for ops + CRM + PM', 'Easy to learn'],
    cons: ['Per-user pricing adds up', 'Limited free tier', 'Can get messy without governance'],
    aliases: ['monday'],
  },
  {
    id: 'linear',
    name: 'Linear',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Issue tracking built for software teams',
    website: 'https://linear.app',
    pricingUrl: 'https://linear.app/pricing',
    getStartedUrl: 'https://linear.app/signup',
    startingPrice: '$8/user/mo (Standard)',
    freeTier: 'Free up to 250 issues',
    bestFor: 'Software teams wanting fast, opinionated issue tracking',
    whatYouDo: 'Track issues, sprints, projects. Built-in automations for status changes, assignments, syncing with GitHub.',
    capabilities: ['project-management', 'task-automation', 'event-trigger'],
    industryFit: ['technology'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#5E6AD2',
    pros: ['Fast and opinionated', 'Excellent UX', 'Strong GitHub integration', 'Good automations'],
    cons: ['Software-focused', 'Limited for non-dev teams', 'Less flexible than Jira'],
  },
  {
    id: 'jira',
    name: 'Jira',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Enterprise issue tracking + project management',
    website: 'https://atlassian.com/software/jira',
    pricingUrl: 'https://atlassian.com/software/jira/pricing',
    getStartedUrl: 'https://atlassian.com/software/jira/free',
    startingPrice: '$8/user/mo (Standard)',
    freeTier: 'Free up to 10 users',
    bestFor: 'Software teams wanting customizable issue tracking at scale',
    whatYouDo: 'Configure workflows, custom fields, boards. Build automation rules. Powerful but complex.',
    capabilities: ['project-management', 'task-automation', 'event-trigger', 'data-routing'],
    industryFit: ['technology', 'finance', 'enterprise'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#0052CC',
    pros: ['Most powerful issue tracking', 'Highly customizable', 'Strong automations', 'Generous free tier'],
    cons: ['Complex to configure', 'Dated UI', 'Slow for small teams'],
  },

  // ============ ANALYTICS ============
  {
    id: 'google-analytics',
    name: 'Google Analytics 4',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Free web + app analytics with AI insights',
    website: 'https://analytics.google.com',
    pricingUrl: 'https://analytics.google.com',
    getStartedUrl: 'https://analytics.google.com',
    startingPrice: 'Free (Standard)',
    freeTier: 'Free forever (Standard)',
    bestFor: 'Any company wanting free web/app analytics with AI-powered insights',
    whatYouDo: 'Install tracking code, configure events, view reports. AI Insights surface anomalies and trends automatically.',
    capabilities: ['analytics-reporting', 'data-routing'],
    industryFit: ['retail', 'technology', 'media', 'education', 'nonprofit'],
    difficulty: 3,
    timeToValue: 'Days',
    logoColor: '#E37400',
    pros: ['Free', 'Industry standard', 'AI-powered insights', 'Strong for e-commerce'],
    cons: ['Steep learning curve', 'Sampling on high volume', 'Privacy concerns'],
    aliases: ['ga4', 'google analytics', 'universal analytics'],
  },
];

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find((t) => t.id === id);
}

export function getToolsByIds(ids: string[]): Tool[] {
  return ids
    .map((id) => getToolById(id))
    .filter((t): t is Tool => t !== undefined);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getNoCodeTools(): Tool[] {
  return TOOLS.filter((t) => t.userEffort !== 'write-code');
}

// NEW: Find tools by capability — used for "do you already have a tool that does X?"
export function getToolsByCapability(capability: Capability): Tool[] {
  return TOOLS.filter((t) => t.capabilities.includes(capability));
}

// NEW: Find tools by name (case-insensitive, includes aliases)
export function findToolByName(name: string): Tool | undefined {
  const normalized = name.toLowerCase().trim();
  return TOOLS.find(
    (t) =>
      t.name.toLowerCase() === normalized ||
      t.id.toLowerCase() === normalized ||
      (t.aliases && t.aliases.some((a) => a.toLowerCase() === normalized))
  );
}

// NEW: Detect overlap between two tools (share at least 2 capabilities)
export function toolsOverlap(tool1: Tool, tool2: Tool): Capability[] {
  return tool1.capabilities.filter((c) => tool2.capabilities.includes(c));
}
