// Curated database of automation tools.
// Each entry is hand-verified for accuracy as of 2026.
// Pricing changes frequently — verify before publishing.

export type ToolCategory = 'integration' | 'ai' | 'rpa' | 'custom';
export type Difficulty = 1 | 2 | 3 | 4 | 5; // 1 = easiest, 5 = hardest
export type TimeToValue = 'Hours' | 'Days' | 'Weeks' | 'Months';

export interface Tool {
  id: string;
  name: string;
  category: ToolCategory;
  tagline: string;
  website: string;
  pricingUrl: string;
  getStartedUrl: string;
  startingPrice: string;
  freeTier: string | null;
  bestFor: string;
  industryFit: string[]; // industries where this tool shines
  difficulty: Difficulty;
  timeToValue: TimeToValue;
  logoColor: string; // hex color for the logo placeholder
  pros: string[];
  cons: string[];
}

export const TOOLS: Tool[] = [
  // ============ INTEGRATION ============
  {
    id: 'make',
    name: 'Make',
    category: 'integration',
    tagline: 'Visual automation builder for SaaS-to-SaaS workflows',
    website: 'https://www.make.com',
    pricingUrl: 'https://www.make.com/en/pricing',
    getStartedUrl: 'https://www.make.com/en/register',
    startingPrice: '$9/mo',
    freeTier: 'Free forever — 1,000 ops/mo, 2 active scenarios',
    bestFor: 'Connecting 5+ SaaS tools with conditional logic and data transformations',
    industryFit: ['technology', 'retail', 'professional-services', 'media'],
    difficulty: 2,
    timeToValue: 'Hours',
    logoColor: '#6D00CC',
    pros: ['Visual flow builder is intuitive', 'Cheaper than Zapier at scale', 'Powerful data transformation'],
    cons: ['Learning curve for complex scenarios', 'Smaller app ecosystem than Zapier'],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'integration',
    tagline: 'Largest integration ecosystem — connects 7,000+ apps',
    website: 'https://zapier.com',
    pricingUrl: 'https://zapier.com/pricing',
    getStartedUrl: 'https://zapier.com/sign-up',
    startingPrice: '$20/mo',
    freeTier: 'Free forever — 100 tasks/mo, 5 single-step zaps',
    bestFor: 'Quick wins between popular SaaS tools with minimal setup',
    industryFit: ['technology', 'retail', 'professional-services', 'education', 'nonprofit'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#FF4F00',
    pros: ['Largest app ecosystem', 'Easiest to learn', 'Great templates'],
    cons: ['Expensive at scale', 'Limited data transformation', 'Single-step zaps only on free tier'],
  },
  {
    id: 'n8n',
    name: 'n8n',
    category: 'integration',
    tagline: 'Open-source workflow automation — self-host or cloud',
    website: 'https://n8n.io',
    pricingUrl: 'https://n8n.io/pricing/',
    getStartedUrl: 'https://n8n.io/cloud/',
    startingPrice: '$20/mo (cloud) or free (self-hosted)',
    freeTier: 'Free self-hosted — unlimited workflows',
    bestFor: 'Technical teams who want control and lower costs at scale',
    industryFit: ['technology', 'finance', 'healthcare'],
    difficulty: 3,
    timeToValue: 'Days',
    logoColor: '#FF6D5A',
    pros: ['Self-hostable for data privacy', 'Code nodes for custom logic', 'Cheaper at scale'],
    cons: ['Requires technical knowledge', 'Smaller template library'],
  },
  {
    id: 'workato',
    name: 'Workato',
    category: 'integration',
    tagline: 'Enterprise iPaaS with intelligent automation recipes',
    website: 'https://www.workato.com',
    pricingUrl: 'https://www.workato.com/pricing',
    getStartedUrl: 'https://www.workato.com/trial',
    startingPrice: 'Custom (~$10K+/yr)',
    freeTier: '30-day trial',
    bestFor: 'Enterprise teams needing governance, security, and complex workflows',
    industryFit: ['finance', 'healthcare', 'manufacturing', 'enterprise'],
    difficulty: 4,
    timeToValue: 'Weeks',
    logoColor: '#2D7DFF',
    pros: ['Enterprise-grade security', 'Recipe intelligence', 'Great for complex ops'],
    cons: ['Expensive', 'Sales-led onboarding', 'Overkill for small teams'],
  },
  {
    id: 'pipedream',
    name: 'Pipedream',
    category: 'integration',
    tagline: 'Developer-focused automation with code when you need it',
    website: 'https://pipedream.com',
    pricingUrl: 'https://pipedream.com/pricing',
    getStartedUrl: 'https://pipedream.com/signup',
    startingPrice: '$19/mo',
    freeTier: 'Free tier — 100 credits/mo',
    bestFor: 'Developers who want API integrations with code-level control',
    industryFit: ['technology'],
    difficulty: 4,
    timeToValue: 'Days',
    logoColor: '#38BDF8',
    pros: ['Full code access', 'Great API support', 'Cheap for developers'],
    cons: ['Not for non-technical users', 'Smaller template library'],
  },
  {
    id: 'celigo',
    name: 'Celigo',
    category: 'integration',
    tagline: 'iPaaS with pre-built integration apps for ERP/CRM',
    website: 'https://www.celigo.com',
    pricingUrl: 'https://www.celigo.com/pricing/',
    getStartedUrl: 'https://www.celigo.com/free-trial/',
    startingPrice: '$250/mo+',
    freeTier: '30-day trial',
    bestFor: 'Mid-market teams with NetSuite, Salesforce, or HubSpot at the center',
    industryFit: ['retail', 'manufacturing', 'finance', 'logistics'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#00A3E0',
    pros: ['Excellent NetSuite connector', 'Pre-built integration apps', 'Mid-market focused'],
    cons: ['Expensive for small teams', 'Best when you have a flagship system'],
  },

  // ============ AI / LLM ============
  {
    id: 'claude-api',
    name: 'Claude API (Anthropic)',
    category: 'ai',
    tagline: 'Best-in-class for long documents and structured extraction',
    website: 'https://anthropic.com',
    pricingUrl: 'https://www.anthropic.com/pricing',
    getStartedUrl: 'https://console.anthropic.com',
    startingPrice: '$3/M input, $15/M output (Sonnet)',
    freeTier: '$5 free credits on signup',
    bestFor: 'Document processing, extraction, classification, long-context analysis',
    industryFit: ['finance', 'healthcare', 'professional-services', 'legal'],
    difficulty: 4,
    timeToValue: 'Days',
    logoColor: '#D97757',
    pros: ['200K context window', 'Best at structured extraction', 'Strong reasoning'],
    cons: ['Requires developer integration', 'No visual builder'],
  },
  {
    id: 'openai-api',
    name: 'OpenAI API',
    category: 'ai',
    tagline: 'GPT-4o + Whisper + DALL-E in one API',
    website: 'https://openai.com',
    pricingUrl: 'https://openai.com/api/pricing/',
    getStartedUrl: 'https://platform.openai.com/signup',
    startingPrice: '$5/M input (GPT-4o-mini), $15/M (GPT-4o)',
    freeTier: 'No free tier — pay-as-you-go',
    bestFor: 'General AI tasks, multimodal (text + image + audio) workflows',
    industryFit: ['technology', 'retail', 'media', 'education'],
    difficulty: 4,
    timeToValue: 'Days',
    logoColor: '#10A37F',
    pros: ['Most mature ecosystem', 'Multimodal support', 'Best docs/tutorials'],
    cons: ['Pricing can balloon', 'Quality variable across models'],
  },
  {
    id: 'gemini-api',
    name: 'Google Gemini API',
    category: 'ai',
    tagline: 'Generous free tier, multimodal, native Google integrations',
    website: 'https://ai.google.dev',
    pricingUrl: 'https://ai.google.dev/pricing',
    getStartedUrl: 'https://aistudio.google.com/app/apikey',
    startingPrice: 'Free tier → $1.25/M input (1.5 Pro)',
    freeTier: 'Free — 15 req/min on Flash, 2 req/min on Pro',
    bestFor: 'Cost-sensitive projects, multimodal tasks, Google Workspace automation',
    industryFit: ['technology', 'education', 'media'],
    difficulty: 4,
    timeToValue: 'Days',
    logoColor: '#4285F4',
    pros: ['Generous free tier', 'Multimodal (text + image + video)', 'Integrates with Google Cloud'],
    cons: ['Smaller ecosystem than OpenAI', 'Less predictable quality'],
  },
  {
    id: 'groq',
    name: 'Groq',
    category: 'ai',
    tagline: 'Ultra-fast LLM inference for Llama models',
    website: 'https://groq.com',
    pricingUrl: 'https://console.groq.com/docs/rate-limits',
    getStartedUrl: 'https://console.groq.com/keys',
    startingPrice: 'Free tier → pay-as-you-go',
    freeTier: 'Free — 30 req/min, 14K req/day on Llama 3.3 70B',
    bestFor: 'High-volume, low-latency LLM calls where speed matters',
    industryFit: ['technology'],
    difficulty: 4,
    timeToValue: 'Hours',
    logoColor: '#F55036',
    pros: ['Incredibly fast (500+ tokens/sec)', 'Generous free tier', 'OpenAI-compatible'],
    cons: ['Limited to Llama/Mixtral models', 'No fine-tuning yet'],
  },
  {
    id: 'mistral',
    name: 'Mistral API',
    category: 'ai',
    tagline: 'Open-weight models with strong reasoning and function calling',
    website: 'https://mistral.ai',
    pricingUrl: 'https://mistral.ai/products/la-plateforme#pricing',
    getStartedUrl: 'https://console.mistral.ai/',
    startingPrice: '$0.15/M input (Small), $2/M (Large)',
    freeTier: 'Free tier on la Plateforme',
    bestFor: 'European data residency, function calling, on-prem options',
    industryFit: ['finance', 'healthcare', 'government'],
    difficulty: 4,
    timeToValue: 'Days',
    logoColor: '#FF7000',
    pros: ['Open-weight models', 'EU data residency', 'Strong function calling'],
    cons: ['Smaller ecosystem', 'Less polished tooling'],
  },

  // ============ RPA ============
  {
    id: 'power-automate',
    name: 'Microsoft Power Automate',
    category: 'rpa',
    tagline: 'Microsoft RPA + workflow automation, native to M365',
    website: 'https://powerautomate.microsoft.com',
    pricingUrl: 'https://powerautomate.microsoft.com/pricing/',
    getStartedUrl: 'https://powerautomate.microsoft.com/en-us/landing/trial/',
    startingPrice: '$15/user/mo',
    freeTier: '90-day trial',
    bestFor: 'Microsoft-centric organizations with legacy systems',
    industryFit: ['finance', 'healthcare', 'government', 'manufacturing'],
    difficulty: 3,
    timeToValue: 'Days',
    logoColor: '#0078D4',
    pros: ['Native M365 integration', 'Includes desktop RPA', 'Familiar to MS shops'],
    cons: ['Licensing complex', 'Limited outside Microsoft ecosystem'],
  },
  {
    id: 'uipath',
    name: 'UiPath',
    category: 'rpa',
    tagline: 'Enterprise RPA platform with attended and unattended bots',
    website: 'https://www.uipath.com',
    pricingUrl: 'https://www.uipath.com/pricing',
    getStartedUrl: 'https://www.uipath.com/platform-trial',
    startingPrice: 'Custom (~$3-5K/bot/yr)',
    freeTier: 'Community Plan — free for individuals',
    bestFor: 'Legacy system automation, regulated industries, large-scale RPA programs',
    industryFit: ['finance', 'healthcare', 'manufacturing', 'government'],
    difficulty: 4,
    timeToValue: 'Weeks',
    logoColor: '#FA4616',
    pros: ['Most mature RPA platform', 'Strong for legacy systems', 'Excellent orchestration'],
    cons: ['Expensive at scale', 'Maintenance overhead', 'Brittle to UI changes'],
  },
  {
    id: 'automation-anywhere',
    name: 'Automation Anywhere',
    category: 'rpa',
    tagline: 'Cloud-native RPA with built-in AI and analytics',
    website: 'https://www.automationanywhere.com',
    pricingUrl: 'https://www.automationanywhere.com/products/pricing',
    getStartedUrl: 'https://www.automationanywhere.com/products/community-edition',
    startingPrice: 'Custom (~$1.5-3K/bot/yr)',
    freeTier: 'Community Edition — free for individuals',
    bestFor: 'Cloud-first enterprises, AI-augmented RPA workflows',
    industryFit: ['finance', 'healthcare', 'logistics'],
    difficulty: 4,
    timeToValue: 'Weeks',
    logoColor: '#00A4EF',
    pros: ['Cloud-native', 'Strong AI integration', 'Good analytics'],
    cons: ['Smaller market share than UiPath', 'Less certified developers'],
  },

  // ============ CUSTOM ============
  {
    id: 'retool',
    name: 'Retool',
    category: 'custom',
    tagline: 'Build internal tools fast with drag-drop + SQL',
    website: 'https://retool.com',
    pricingUrl: 'https://retool.com/pricing',
    getStartedUrl: 'https://retool.com/signup/',
    startingPrice: '$10/user/mo',
    freeTier: 'Free — up to 5 users, unlimited apps',
    bestFor: 'Internal admin tools, dashboards, ops workflows',
    industryFit: ['technology', 'finance', 'retail', 'logistics'],
    difficulty: 3,
    timeToValue: 'Days',
    logoColor: '#3D3D3D',
    pros: ['Fast to build internal tools', 'Connects to any DB/API', 'Strong for ops teams'],
    cons: ['Not for external users', 'Per-user pricing adds up'],
  },
  {
    id: 'bubble',
    name: 'Bubble',
    category: 'custom',
    tagline: 'No-code platform for full web applications',
    website: 'https://bubble.io',
    pricingUrl: 'https://bubble.io/pricing',
    getStartedUrl: 'https://bubble.io/register',
    startingPrice: '$32/mo',
    freeTier: 'Free tier — limited to test app',
    bestFor: 'Non-technical founders building production web apps',
    industryFit: ['technology', 'retail', 'media', 'nonprofit'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#000000',
    pros: ['Build full apps without code', 'Strong community/templates', 'Reasonable pricing'],
    cons: ['Performance at scale', 'Learning curve is real', 'Lock-in risk'],
  },
  {
    id: 'xano',
    name: 'Xano',
    category: 'custom',
    tagline: 'No-code backend with database, API, and logic',
    website: 'https://xano.com',
    pricingUrl: 'https://xano.com/pricing/',
    getStartedUrl: 'https://app.xano.com/#/signup',
    startingPrice: '$59/mo',
    freeTier: 'Free tier — 5K records',
    bestFor: 'Frontend devs who need a backend fast',
    industryFit: ['technology', 'retail', 'media'],
    difficulty: 3,
    timeToValue: 'Days',
    logoColor: '#7C3AED',
    pros: ['Fast backend setup', 'Scalable Postgres', 'Branching environments'],
    cons: ['Pricing scales with usage', 'Limited to backend (need frontend)'],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'custom',
    tagline: 'Open-source Firebase alternative — Postgres + auth + storage',
    website: 'https://supabase.com',
    pricingUrl: 'https://supabase.com/pricing',
    getStartedUrl: 'https://supabase.com/dashboard',
    startingPrice: '$25/mo',
    freeTier: 'Free — 500MB DB, 50K MAU auth, 1GB storage',
    bestFor: 'Full-stack developers building production apps',
    industryFit: ['technology', 'retail', 'media', 'education'],
    difficulty: 4,
    timeToValue: 'Hours',
    logoColor: '#3ECF8E',
    pros: ['Open-source', 'Postgres with realtime', 'Generous free tier'],
    cons: ['Requires dev knowledge', 'Self-host option has overhead'],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: 'custom',
    tagline: 'Spreadsheet-database hybrid with automations and extensions',
    website: 'https://airtable.com',
    pricingUrl: 'https://airtable.com/pricing',
    getStartedUrl: 'https://airtable.com/signup',
    startingPrice: '$20/user/mo',
    freeTier: 'Free — 1K records per base',
    bestFor: 'Operations teams tracking workflows in a spreadsheet-like UI',
    industryFit: ['retail', 'media', 'education', 'nonprofit', 'professional-services'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#FCB400',
    pros: ['Easy to adopt', 'Built-in automations', 'Excellent for ops tracking'],
    cons: ['Limited at scale', 'Per-user pricing', 'Not for transactional apps'],
  },
];

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find((t) => t.id === id);
}

export function getToolsByIds(ids: string[]): Tool[] {
  return ids
    .map((id) => getToolById(id))
    .filter((t): t is Tool => t !== undefined);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}
