// Curated database of automation tools.
// Each entry is hand-verified for accuracy as of 2026.
// Pricing changes frequently — verify before publishing.

export type ToolCategory =
  | 'integration'
  | 'ai'
  | 'rpa'
  | 'custom'
  | 'purpose-built'; // NEW: end-to-end tools built for specific tasks
export type Difficulty = 1 | 2 | 3 | 4 | 5; // 1 = easiest, 5 = hardest
export type TimeToValue = 'Hours' | 'Days' | 'Weeks' | 'Months';

// NEW: distinguishes tools where users CONFIGURE vs BUILD vs CODE
export type UserEffort =
  | 'upload-and-go' // lowest effort — upload files, get results
  | 'configure' // connect accounts, fill in templates, set rules
  | 'build-visually' // drag-drop workflow builder
  | 'write-code'; // highest effort — developer integration required

// NEW: distinguishes tools that solve a problem end-to-end
// vs building blocks (raw APIs) that require dev work
export type ToolType = 'solution' | 'building-block';

export interface Tool {
  id: string;
  name: string;
  category: ToolCategory;
  toolType: ToolType; // NEW
  userEffort: UserEffort; // NEW
  tagline: string;
  website: string;
  pricingUrl: string;
  getStartedUrl: string;
  startingPrice: string;
  freeTier: string | null;
  bestFor: string;
  whatYouDo: string; // NEW: plain English description of what the user actually does
  industryFit: string[];
  difficulty: Difficulty;
  timeToValue: TimeToValue;
  logoColor: string;
  pros: string[];
  cons: string[];
}

export const TOOLS: Tool[] = [
  // ============ PURPOSE-BUILT SOLUTIONS (lowest user effort) ============
  {
    id: 'lido',
    name: 'Lido',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'upload-and-go',
    tagline: 'Spreadsheet that automates itself — built for finance & ops',
    website: 'https://lido.app',
    pricingUrl: 'https://lido.app/pricing',
    getStartedUrl: 'https://lido.app/signup',
    startingPrice: '$50/mo',
    freeTier: 'Free tier — 3 docs, 100 rows',
    bestFor: 'Invoice processing, report generation, data cleaning — anything you\'d do in Excel but want automated',
    whatYouDo: 'Upload your spreadsheet or PDF, link your data sources, and Lido auto-extracts, transforms, and outputs. No code, no API keys, no workflow builder — it just works like a smart spreadsheet.',
    industryFit: ['finance', 'retail', 'professional-services', 'logistics', 'healthcare'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#FF6B35',
    pros: ['No code or API keys needed', 'Familiar spreadsheet interface', 'Built-in PDF and email parsing', 'Outputs to email/Slack/sheets automatically'],
    cons: ['Limited to spreadsheet-shaped problems', 'Less flexible than general automation tools'],
  },
  {
    id: 'clay',
    name: 'Clay',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Sales/revenue automation with built-in data enrichment',
    website: 'https://clay.com',
    pricingUrl: 'https://clay.com/pricing',
    getStartedUrl: 'https://clay.com/signup',
    startingPrice: '$149/mo',
    freeTier: '14-day trial + free tier with credits',
    bestFor: 'Lead enrichment, prospecting, sales research, outbound personalization',
    whatYouDo: 'Import a list of prospects, drop in enrichment columns (company, role, tech stack, recent news), write AI prompts to personalize outreach. Clay handles all the data fetching and AI calls — no API keys to manage.',
    industryFit: ['technology', 'professional-services', 'finance', 'retail'],
    difficulty: 2,
    timeToValue: 'Hours',
    logoColor: '#10B981',
    pros: ['75+ data providers pre-integrated', 'Built-in AI for personalization', 'No API keys to manage', 'Visual spreadsheet interface'],
    cons: ['Focused on sales/revenue use cases', 'Can get expensive at scale'],
  },
  {
    id: 'bardeen',
    name: 'Bardeen',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Browser extension that automates any web task',
    website: 'https://bardeen.ai',
    pricingUrl: 'https://bardeen.ai/pricing',
    getStartedUrl: 'https://bardeen.ai/download',
    startingPrice: '$15/mo',
    freeTier: 'Free tier — 20 credits/mo',
    bestFor: 'Web scraping, data entry, browser-based workflows (LinkedIn, Notion, Google Sheets, etc.)',
    whatYouDo: 'Install the Chrome extension, click "record", do the task once manually. Bardeen learns and repeats it. Has hundreds of pre-built automations for popular sites.',
    industryFit: ['technology', 'retail', 'media', 'professional-services'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#7C3AED',
    pros: ['No-code browser automation', 'Hundreds of pre-built workflows', 'Records your actions to learn', 'Free tier is genuinely usable'],
    cons: ['Browser-only — can\'t run server-side', 'Limited to what you can do in a browser'],
  },
  {
    id: 'nanonets',
    name: 'Nanonets',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'upload-and-go',
    tagline: 'Document AI — pre-trained for invoices, receipts, contracts',
    website: 'https://nanonets.com',
    pricingUrl: 'https://nanonets.com/pricing/',
    getStartedUrl: 'https://nanonets.com/signup/',
    startingPrice: '$49/mo',
    freeTier: 'Free tier — 500 docs/mo',
    bestFor: 'Document extraction (invoices, receipts, POs, contracts) without building ML models',
    whatYouDo: 'Pick a pre-trained model (invoice, receipt, ID, contract, etc.), upload your documents, get structured data out. Custom fields via point-and-click UI. No ML expertise needed.',
    industryFit: ['finance', 'healthcare', 'logistics', 'retail', 'manufacturing'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#6366F1',
    pros: ['Pre-trained models for common docs', 'No ML expertise needed', 'Custom fields via UI', 'Outputs to anywhere (sheets, API, webhooks)'],
    cons: ['Limited to document tasks', 'Custom models get expensive'],
  },
  {
    id: 'docparser',
    name: 'Docparser',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'PDF/document data extraction with rule-based parsing',
    website: 'https://docparser.com',
    pricingUrl: 'https://docparser.com/pricing',
    getStartedUrl: 'https://docparser.com/signup',
    startingPrice: '$39/mo',
    freeTier: '14-day trial (no free tier)',
    bestFor: 'Recurring PDFs with consistent structure (invoices, POs, reports) where you need precise data extraction',
    whatYouDo: 'Upload a sample document, drag boxes around the fields you want extracted, save the parser. Future docs of the same type are auto-parsed. Less smart than AI but more predictable.',
    industryFit: ['finance', 'logistics', 'manufacturing', 'healthcare'],
    difficulty: 2,
    timeToValue: 'Days',
    logoColor: '#0EA5E9',
    pros: ['More predictable than AI for structured docs', 'Visual parser builder', 'Works on any PDF', 'Strong for regulated industries'],
    cons: ['Requires consistent document structure', 'Less flexible than AI approaches'],
  },
  {
    id: 'browse-ai',
    name: 'Browse AI',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Web scraping without code — extract data from any website',
    website: 'https://browse.ai',
    pricingUrl: 'https://browse.ai/pricing',
    getStartedUrl: 'https://browse.ai/signup',
    startingPrice: '$39/mo',
    freeTier: 'Free tier — 50 credits/mo',
    bestFor: 'Monitoring competitors, scraping listings, extracting structured data from any website',
    whatYouDo: 'Install the Chrome extension, navigate to a website, click on the data you want extracted. Browse AI turns your clicks into a scraper that runs on schedule. No code.',
    industryFit: ['retail', 'media', 'technology', 'professional-services'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#10B981',
    pros: ['Point-and-click scraper builder', 'Monitors websites on schedule', 'Handles pagination and login', 'Pre-built robots for popular sites'],
    cons: ['Limited to public web data', 'Can break when sites change layout'],
  },
  {
    id: 'axiom',
    name: 'Axiom.ai',
    category: 'purpose-built',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Browser automation — no code, just record and replay',
    website: 'https://axiom.ai',
    pricingUrl: 'https://axiom.ai/pricing',
    getStartedUrl: 'https://axiom.ai/signup',
    startingPrice: '$15/mo',
    freeTier: 'Free tier — 2 hours runtime/mo',
    bestFor: 'Browser-based data entry, form filling, repetitive web tasks',
    whatYouDo: 'Install Chrome extension, click "record", perform the task in your browser. Axiom saves the steps and can replay them on schedule or via webhook. No code.',
    industryFit: ['technology', 'retail', 'professional-services', 'media'],
    difficulty: 2,
    timeToValue: 'Hours',
    logoColor: '#F59E0B',
    pros: ['Records browser actions visually', 'Runs in cloud on schedule', 'Handles complex multi-step flows', 'Generous free tier'],
    cons: ['Browser-only', 'Brittle to UI changes on target sites'],
  },

  // ============ INTEGRATION (visual workflow builders) ============
  {
    id: 'make',
    name: 'Make',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Visual automation builder for SaaS-to-SaaS workflows',
    website: 'https://www.make.com',
    pricingUrl: 'https://www.make.com/en/pricing',
    getStartedUrl: 'https://www.make.com/en/register',
    startingPrice: '$9/mo',
    freeTier: 'Free forever — 1,000 ops/mo, 2 active scenarios',
    bestFor: 'Connecting 5+ SaaS tools with conditional logic and data transformations. Has built-in OpenAI/Claude modules — no API key needed.',
    whatYouDo: 'Drag-drop a visual workflow: pick a trigger (e.g., new email), add steps (filter, transform, send to another app). Make handles all the API calls. You configure, not code.',
    industryFit: ['technology', 'retail', 'professional-services', 'media'],
    difficulty: 2,
    timeToValue: 'Hours',
    logoColor: '#6D00CC',
    pros: ['Visual flow builder is intuitive', 'Built-in AI modules (no API key)', 'Cheaper than Zapier at scale', 'Powerful data transformation'],
    cons: ['Learning curve for complex scenarios', 'Smaller app ecosystem than Zapier'],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Largest integration ecosystem — connects 7,000+ apps',
    website: 'https://zapier.com',
    pricingUrl: 'https://zapier.com/pricing',
    getStartedUrl: 'https://zapier.com/sign-up',
    startingPrice: '$20/mo',
    freeTier: 'Free forever — 100 tasks/mo, 5 single-step zaps',
    bestFor: 'Quick wins between popular SaaS tools with minimal setup. Has built-in OpenAI/Claude/Formatter steps.',
    whatYouDo: 'Pick a trigger app, pick an action app, fill in the mapping. Zapier handles everything. For AI tasks, use Zapier\'s built-in AI steps (no API key needed).',
    industryFit: ['technology', 'retail', 'professional-services', 'education', 'nonprofit'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#FF4F00',
    pros: ['Largest app ecosystem', 'Easiest to learn', 'Built-in AI steps (no API key)', 'Great templates library'],
    cons: ['Expensive at scale', 'Limited data transformation on lower tiers', 'Single-step zaps only on free tier'],
  },
  {
    id: 'n8n',
    name: 'n8n',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Open-source workflow automation — self-host or cloud',
    website: 'https://n8n.io',
    pricingUrl: 'https://n8n.io/pricing/',
    getStartedUrl: 'https://n8n.io/cloud/',
    startingPrice: '$20/mo (cloud) or free (self-hosted)',
    freeTier: 'Free self-hosted — unlimited workflows',
    bestFor: 'Technical teams who want control and lower costs at scale',
    industryFit: ['technology', 'finance', 'healthcare'],
    difficulty: 3,
    timeToValue: 'Days',
    logoColor: '#FF6D5A',
    pros: ['Self-hostable for data privacy', 'Code nodes for custom logic', 'Cheaper at scale'],
    cons: ['Requires technical knowledge', 'Smaller template library'],
  },
  {
    id: 'workato',
    name: 'Workato',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Enterprise iPaaS with intelligent automation recipes',
    website: 'https://www.workato.com',
    pricingUrl: 'https://www.workato.com/pricing',
    getStartedUrl: 'https://www.workato.com/trial',
    startingPrice: 'Custom (~$10K+/yr)',
    freeTier: '30-day trial',
    bestFor: 'Enterprise teams needing governance, security, and complex workflows',
    industryFit: ['finance', 'healthcare', 'manufacturing', 'enterprise'],
    difficulty: 4,
    timeToValue: 'Weeks',
    logoColor: '#2D7DFF',
    pros: ['Enterprise-grade security', 'Recipe intelligence', 'Great for complex ops'],
    cons: ['Expensive', 'Sales-led onboarding', 'Overkill for small teams'],
  },
  {
    id: 'pipedream',
    name: 'Pipedream',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'write-code',
    tagline: 'Developer-focused automation with code when you need it',
    website: 'https://pipedream.com',
    pricingUrl: 'https://pipedream.com/pricing',
    getStartedUrl: 'https://pipedream.com/signup',
    startingPrice: '$19/mo',
    freeTier: 'Free tier — 100 credits/mo',
    bestFor: 'Developers who want API integrations with code-level control',
    industryFit: ['technology'],
    difficulty: 4,
    timeToValue: 'Days',
    logoColor: '#38BDF8',
    pros: ['Full code access', 'Great API support', 'Cheap for developers'],
    cons: ['Not for non-technical users', 'Smaller template library'],
  },
  {
    id: 'celigo',
    name: 'Celigo',
    category: 'integration',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'iPaaS with pre-built integration apps for ERP/CRM',
    website: 'https://www.celigo.com',
    pricingUrl: 'https://www.celigo.com/pricing/',
    getStartedUrl: 'https://www.celigo.com/free-trial/',
    startingPrice: '$250/mo+',
    freeTier: '30-day trial',
    bestFor: 'Mid-market teams with NetSuite, Salesforce, or HubSpot at the center',
    industryFit: ['retail', 'manufacturing', 'finance', 'logistics'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#00A3E0',
    pros: ['Excellent NetSuite connector', 'Pre-built integration apps', 'Mid-market focused'],
    cons: ['Expensive for small teams', 'Best when you have a flagship system'],
  },

  // ============ AI BUILDING BLOCKS (use only via wrappers like Make/Zapier, not standalone) ============
  {
    id: 'claude-api',
    name: 'Claude API (Anthropic)',
    category: 'ai',
    toolType: 'building-block',
    userEffort: 'write-code',
    tagline: 'Best-in-class for long documents and structured extraction — building block only',
    website: 'https://anthropic.com',
    pricingUrl: 'https://www.anthropic.com/pricing',
    getStartedUrl: 'https://console.anthropic.com',
    startingPrice: '$3/M input, $15/M output (Sonnet)',
    freeTier: '$5 free credits on signup',
    bestFor: 'When you need custom AI logic that purpose-built tools can\'t handle. PREFER using Claude via Make.com or Zapier\'s built-in modules instead of direct API.',
    whatYouDo: 'Write code to call the API, handle errors, manage rate limits. For non-technical users: use Make.com or Zapier\'s Claude modules instead — same model, no code.',
    industryFit: ['finance', 'healthcare', 'professional-services', 'legal'],
    difficulty: 4,
    timeToValue: 'Days',
    logoColor: '#D97757',
    pros: ['200K context window', 'Best at structured extraction', 'Strong reasoning'],
    cons: ['Requires developer integration', 'No visual builder', 'USE VIA MAKE/ZAPIER unless you have a dev team'],
  },
  {
    id: 'openai-api',
    name: 'OpenAI API',
    category: 'ai',
    toolType: 'building-block',
    userEffort: 'write-code',
    tagline: 'GPT-4o + Whisper + DALL-E — building block only',
    website: 'https://openai.com',
    pricingUrl: 'https://openai.com/api/pricing/',
    getStartedUrl: 'https://platform.openai.com/signup',
    startingPrice: '$5/M input (GPT-4o-mini), $15/M (GPT-4o)',
    freeTier: 'No free tier — pay-as-you-go',
    bestFor: 'When you need custom AI logic that purpose-built tools can\'t handle. PREFER using GPT-4o via Make.com or Zapier\'s built-in modules instead of direct API.',
    whatYouDo: 'Write code to call the API. For non-technical users: use Make.com or Zapier\'s OpenAI modules instead — same model, no code.',
    industryFit: ['technology', 'retail', 'media', 'education'],
    difficulty: 4,
    timeToValue: 'Days',
    logoColor: '#10A37F',
    pros: ['Most mature ecosystem', 'Multimodal support', 'Best docs/tutorials'],
    cons: ['Requires dev integration', 'USE VIA MAKE/ZAPIER unless you have a dev team'],
  },

  // ============ RPA ============
  {
    id: 'power-automate',
    name: 'Microsoft Power Automate',
    category: 'rpa',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Microsoft RPA + workflow automation, native to M365',
    website: 'https://powerautomate.microsoft.com',
    pricingUrl: 'https://powerautomate.microsoft.com/pricing/',
    getStartedUrl: 'https://powerautomate.microsoft.com/en-us/landing/trial/',
    startingPrice: '$15/user/mo',
    freeTier: '90-day trial',
    bestFor: 'Microsoft-centric organizations with legacy systems',
    industryFit: ['finance', 'healthcare', 'government', 'manufacturing'],
    difficulty: 3,
    timeToValue: 'Days',
    logoColor: '#0078D4',
    pros: ['Native M365 integration', 'Includes desktop RPA + AI Builder', 'Familiar to MS shops'],
    cons: ['Licensing complex', 'Limited outside Microsoft ecosystem'],
  },
  {
    id: 'uipath',
    name: 'UiPath',
    category: 'rpa',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Enterprise RPA platform with attended and unattended bots',
    website: 'https://www.uipath.com',
    pricingUrl: 'https://www.uipath.com/pricing',
    getStartedUrl: 'https://www.uipath.com/platform-trial',
    startingPrice: 'Custom (~$3-5K/bot/yr)',
    freeTier: 'Community Plan — free for individuals',
    bestFor: 'Legacy system automation, regulated industries, large-scale RPA programs',
    industryFit: ['finance', 'healthcare', 'manufacturing', 'government'],
    difficulty: 4,
    timeToValue: 'Weeks',
    logoColor: '#FA4616',
    pros: ['Most mature RPA platform', 'Strong for legacy systems', 'Excellent orchestration'],
    cons: ['Expensive at scale', 'Maintenance overhead', 'Brittle to UI changes'],
  },

  // ============ CUSTOM ============
  {
    id: 'retool',
    name: 'Retool',
    category: 'custom',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'Build internal tools fast with drag-drop + SQL',
    website: 'https://retool.com',
    pricingUrl: 'https://retool.com/pricing',
    getStartedUrl: 'https://retool.com/signup/',
    startingPrice: '$10/user/mo',
    freeTier: 'Free — up to 5 users, unlimited apps',
    bestFor: 'Internal admin tools, dashboards, ops workflows',
    industryFit: ['technology', 'finance', 'retail', 'logistics'],
    difficulty: 3,
    timeToValue: 'Days',
    logoColor: '#3D3D3D',
    pros: ['Fast to build internal tools', 'Connects to any DB/API', 'Strong for ops teams'],
    cons: ['Not for external users', 'Per-user pricing adds up'],
  },
  {
    id: 'bubble',
    name: 'Bubble',
    category: 'custom',
    toolType: 'solution',
    userEffort: 'build-visually',
    tagline: 'No-code platform for full web applications',
    website: 'https://bubble.io',
    pricingUrl: 'https://bubble.io/pricing',
    getStartedUrl: 'https://bubble.io/register',
    startingPrice: '$32/mo',
    freeTier: 'Free tier — limited to test app',
    bestFor: 'Non-technical founders building production web apps',
    industryFit: ['technology', 'retail', 'media', 'nonprofit'],
    difficulty: 3,
    timeToValue: 'Weeks',
    logoColor: '#000000',
    pros: ['Build full apps without code', 'Strong community/templates', 'Reasonable pricing'],
    cons: ['Performance at scale', 'Learning curve is real', 'Lock-in risk'],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: 'custom',
    toolType: 'solution',
    userEffort: 'configure',
    tagline: 'Spreadsheet-database hybrid with automations and extensions',
    website: 'https://airtable.com',
    pricingUrl: 'https://airtable.com/pricing',
    getStartedUrl: 'https://airtable.com/signup',
    startingPrice: '$20/user/mo',
    freeTier: 'Free — 1K records per base',
    bestFor: 'Operations teams tracking workflows in a spreadsheet-like UI',
    industryFit: ['retail', 'media', 'education', 'nonprofit', 'professional-services'],
    difficulty: 1,
    timeToValue: 'Hours',
    logoColor: '#FCB400',
    pros: ['Easy to adopt', 'Built-in automations', 'Excellent for ops tracking'],
    cons: ['Limited at scale', 'Per-user pricing', 'Not for transactional apps'],
  },
];

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find((t) => t.id === id);
}

export function getToolsByIds(ids: string[]): Tool[] {
  return ids
    .map((id) => getToolById(id))
    .filter((t): t is Tool => t !== undefined);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

// NEW: helper to get tools where users don't need to write code
export function getNoCodeTools(): Tool[] {
  return TOOLS.filter((t) => t.userEffort !== 'write-code');
}
